// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"io"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// CatalogRefresh is an object representing the database table.
type CatalogRefresh struct {
	ID          string           `db:"id,pk" `
	Provider    string           `db:"provider" `
	Status      string           `db:"status" `
	StartedAt   string           `db:"started_at" `
	CompletedAt sql.Null[string] `db:"completed_at" `
	Error       sql.Null[string] `db:"error" `
}

// CatalogRefreshSlice is an alias for a slice of pointers to CatalogRefresh.
// This should almost always be used instead of []*CatalogRefresh.
type CatalogRefreshSlice []*CatalogRefresh

// CatalogRefreshes contains methods to work with the catalog_refreshes table
var CatalogRefreshes = sqlite.NewTablex[*CatalogRefresh, CatalogRefreshSlice, *CatalogRefreshSetter]("", "catalog_refreshes", buildCatalogRefreshColumns("catalog_refreshes"), catalogRefreshScanMapper)

// CatalogRefreshesQuery is a query on the catalog_refreshes table
type CatalogRefreshesQuery = *sqlite.ViewQuery[*CatalogRefresh, CatalogRefreshSlice]

func buildCatalogRefreshColumns(tableName string) catalogRefreshColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "provider", "status", "started_at", "completed_at", "error",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return catalogRefreshColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildCatalogRefreshColumn(tableName, "id"),
		Provider:    buildCatalogRefreshColumn(tableName, "provider"),
		Status:      buildCatalogRefreshColumn(tableName, "status"),
		StartedAt:   buildCatalogRefreshColumn(tableName, "started_at"),
		CompletedAt: buildCatalogRefreshColumn(tableName, "completed_at"),
		Error:       buildCatalogRefreshColumn(tableName, "error"),
	}
}

type catalogRefreshColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          catalogRefreshColumn
	Provider    catalogRefreshColumn
	Status      catalogRefreshColumn
	StartedAt   catalogRefreshColumn
	CompletedAt catalogRefreshColumn
	Error       catalogRefreshColumn
}

// Alias returns the current table alias for the columns set.
func (c catalogRefreshColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (catalogRefreshColumns) AliasedAs(tableName string) catalogRefreshColumns {
	return buildCatalogRefreshColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c catalogRefreshColumns) Unqualified() catalogRefreshColumns {
	return buildCatalogRefreshColumns("")
}

func buildCatalogRefreshColumn(alias, name string) catalogRefreshColumn {
	return catalogRefreshColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type catalogRefreshColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c catalogRefreshColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c catalogRefreshColumn) ShouldOmitParens() bool {
	return true
}

// CatalogRefreshSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type CatalogRefreshSetter struct {
	ID          *string           `db:"id,pk" `
	Provider    *string           `db:"provider" `
	Status      *string           `db:"status" `
	StartedAt   *string           `db:"started_at" `
	CompletedAt *sql.Null[string] `db:"completed_at" `
	Error       *sql.Null[string] `db:"error" `
}

func (s CatalogRefreshSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.Provider != nil {
		vals = append(vals, "provider")
	}
	if s.Status != nil {
		vals = append(vals, "status")
	}
	if s.StartedAt != nil {
		vals = append(vals, "started_at")
	}
	if s.CompletedAt != nil {
		vals = append(vals, "completed_at")
	}
	if s.Error != nil {
		vals = append(vals, "error")
	}
	return vals
}

func (s CatalogRefreshSetter) Overwrite(t *CatalogRefresh) {
	if s.ID != nil {
		t.ID = func() string {
			if s.ID == nil {
				return *new(string)
			}
			return *s.ID
		}()
	}
	if s.Provider != nil {
		t.Provider = func() string {
			if s.Provider == nil {
				return *new(string)
			}
			return *s.Provider
		}()
	}
	if s.Status != nil {
		t.Status = func() string {
			if s.Status == nil {
				return *new(string)
			}
			return *s.Status
		}()
	}
	if s.StartedAt != nil {
		t.StartedAt = func() string {
			if s.StartedAt == nil {
				return *new(string)
			}
			return *s.StartedAt
		}()
	}
	if s.CompletedAt != nil {
		t.CompletedAt = func() sql.Null[string] {
			if s.CompletedAt == nil {
				return *new(sql.Null[string])
			}
			v := s.CompletedAt
			return *v
		}()
	}
	if s.Error != nil {
		t.Error = func() sql.Null[string] {
			if s.Error == nil {
				return *new(sql.Null[string])
			}
			v := s.Error
			return *v
		}()
	}
}

func (s *CatalogRefreshSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return CatalogRefreshes.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.ID == nil {
						return *new(string)
					}
					return *s.ID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "provider":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Provider == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.Provider == nil {
						return *new(string)
					}
					return *s.Provider
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "status":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Status == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.Status == nil {
						return *new(string)
					}
					return *s.Status
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "started_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.StartedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.StartedAt == nil {
						return *new(string)
					}
					return *s.StartedAt
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "completed_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.CompletedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.CompletedAt == nil {
						return *new(sql.Null[string])
					}
					v := s.CompletedAt
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "error":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Error == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.Error == nil {
						return *new(sql.Null[string])
					}
					v := s.Error
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s CatalogRefreshSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s CatalogRefreshSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.Provider != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "provider")...),
			sqlite.Arg(s.Provider),
		}})
	}

	if s.Status != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "status")...),
			sqlite.Arg(s.Status),
		}})
	}

	if s.StartedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "started_at")...),
			sqlite.Arg(s.StartedAt),
		}})
	}

	if s.CompletedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "completed_at")...),
			sqlite.Arg(s.CompletedAt),
		}})
	}

	if s.Error != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "error")...),
			sqlite.Arg(s.Error),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func catalogRefreshScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*CatalogRefresh, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *CatalogRefresh) any
	}
	targets := make([]target, 0, 6)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *CatalogRefresh) any { return &o.ID }})
		case "provider":
			targets = append(targets, target{i, func(o *CatalogRefresh) any { return &o.Provider }})
		case "status":
			targets = append(targets, target{i, func(o *CatalogRefresh) any { return &o.Status }})
		case "started_at":
			targets = append(targets, target{i, func(o *CatalogRefresh) any { return &o.StartedAt }})
		case "completed_at":
			targets = append(targets, target{i, func(o *CatalogRefresh) any { return &o.CompletedAt }})
		case "error":
			targets = append(targets, target{i, func(o *CatalogRefresh) any { return &o.Error }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(CatalogRefresh)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*CatalogRefresh, error) {
			return v.(*CatalogRefresh), nil
		}
}

// FindCatalogRefresh retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCatalogRefresh(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*CatalogRefresh, error) {
	if len(cols) == 0 {
		return CatalogRefreshes.Query(
			sm.Where(CatalogRefreshes.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return CatalogRefreshes.Query(
		sm.Where(CatalogRefreshes.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(CatalogRefreshes.Columns.Only(cols...)),
	).One(ctx, exec)
}

// CatalogRefreshExists checks the presence of a single record by primary key
func CatalogRefreshExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return CatalogRefreshes.Query(
		sm.Where(CatalogRefreshes.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after CatalogRefresh is retrieved from the database
func (o *CatalogRefresh) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = CatalogRefreshes.AfterSelectHooks.RunHooks(ctx, exec, CatalogRefreshSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = CatalogRefreshes.AfterInsertHooks.RunHooks(ctx, exec, CatalogRefreshSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = CatalogRefreshes.AfterUpdateHooks.RunHooks(ctx, exec, CatalogRefreshSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = CatalogRefreshes.AfterDeleteHooks.RunHooks(ctx, exec, CatalogRefreshSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the CatalogRefresh
func (o *CatalogRefresh) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *CatalogRefresh) pkEQ() dialect.Expression {
	return sqlite.Quote("catalog_refreshes", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the CatalogRefresh
func (o *CatalogRefresh) Update(ctx context.Context, exec bob.Executor, s *CatalogRefreshSetter) error {
	v, err := CatalogRefreshes.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single CatalogRefresh record with an executor
func (o *CatalogRefresh) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := CatalogRefreshes.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the CatalogRefresh using the executor
func (o *CatalogRefresh) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := CatalogRefreshes.Query(
		sm.Where(CatalogRefreshes.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after CatalogRefreshSlice is retrieved from the database
func (o CatalogRefreshSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = CatalogRefreshes.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = CatalogRefreshes.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = CatalogRefreshes.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = CatalogRefreshes.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o CatalogRefreshSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("catalog_refreshes", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o CatalogRefreshSlice) copyMatchingRows(from ...*CatalogRefresh) {
	fromByPK := make(map[string]*CatalogRefresh, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}

		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o CatalogRefreshSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return CatalogRefreshes.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *CatalogRefresh:
				o.copyMatchingRows(retrieved)
			case []*CatalogRefresh:
				o.copyMatchingRows(retrieved...)
			case CatalogRefreshSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a CatalogRefresh or a slice of CatalogRefresh
				// then run the AfterUpdateHooks on the slice
				_, err = CatalogRefreshes.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o CatalogRefreshSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return CatalogRefreshes.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *CatalogRefresh:
				o.copyMatchingRows(retrieved)
			case []*CatalogRefresh:
				o.copyMatchingRows(retrieved...)
			case CatalogRefreshSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a CatalogRefresh or a slice of CatalogRefresh
				// then run the AfterDeleteHooks on the slice
				_, err = CatalogRefreshes.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o CatalogRefreshSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals CatalogRefreshSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := CatalogRefreshes.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o CatalogRefreshSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := CatalogRefreshes.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o CatalogRefreshSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := CatalogRefreshes.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}
