// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"io"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// ClientAPIKey is an object representing the database table.
type ClientAPIKey struct {
	ID         string           `db:"id,pk" `
	Label      string           `db:"label" `
	KeyHash    string           `db:"key_hash" `
	KeyPrefix  string           `db:"key_prefix" `
	CreatedAt  string           `db:"created_at" `
	LastUsedAt sql.Null[string] `db:"last_used_at" `
	RevokedAt  sql.Null[string] `db:"revoked_at" `
}

// ClientAPIKeySlice is an alias for a slice of pointers to ClientAPIKey.
// This should almost always be used instead of []*ClientAPIKey.
type ClientAPIKeySlice []*ClientAPIKey

// ClientAPIKeys contains methods to work with the client_api_keys table
var ClientAPIKeys = sqlite.NewTablex[*ClientAPIKey, ClientAPIKeySlice, *ClientAPIKeySetter]("", "client_api_keys", buildClientAPIKeyColumns("client_api_keys"), clientAPIKeyScanMapper)

// ClientAPIKeysQuery is a query on the client_api_keys table
type ClientAPIKeysQuery = *sqlite.ViewQuery[*ClientAPIKey, ClientAPIKeySlice]

func buildClientAPIKeyColumns(tableName string) clientAPIKeyColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "label", "key_hash", "key_prefix", "created_at", "last_used_at", "revoked_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return clientAPIKeyColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildClientAPIKeyColumn(tableName, "id"),
		Label:       buildClientAPIKeyColumn(tableName, "label"),
		KeyHash:     buildClientAPIKeyColumn(tableName, "key_hash"),
		KeyPrefix:   buildClientAPIKeyColumn(tableName, "key_prefix"),
		CreatedAt:   buildClientAPIKeyColumn(tableName, "created_at"),
		LastUsedAt:  buildClientAPIKeyColumn(tableName, "last_used_at"),
		RevokedAt:   buildClientAPIKeyColumn(tableName, "revoked_at"),
	}
}

type clientAPIKeyColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         clientAPIKeyColumn
	Label      clientAPIKeyColumn
	KeyHash    clientAPIKeyColumn
	KeyPrefix  clientAPIKeyColumn
	CreatedAt  clientAPIKeyColumn
	LastUsedAt clientAPIKeyColumn
	RevokedAt  clientAPIKeyColumn
}

// Alias returns the current table alias for the columns set.
func (c clientAPIKeyColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (clientAPIKeyColumns) AliasedAs(tableName string) clientAPIKeyColumns {
	return buildClientAPIKeyColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c clientAPIKeyColumns) Unqualified() clientAPIKeyColumns {
	return buildClientAPIKeyColumns("")
}

func buildClientAPIKeyColumn(alias, name string) clientAPIKeyColumn {
	return clientAPIKeyColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type clientAPIKeyColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c clientAPIKeyColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c clientAPIKeyColumn) ShouldOmitParens() bool {
	return true
}

// ClientAPIKeySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ClientAPIKeySetter struct {
	ID         *string           `db:"id,pk" `
	Label      *string           `db:"label" `
	KeyHash    *string           `db:"key_hash" `
	KeyPrefix  *string           `db:"key_prefix" `
	CreatedAt  *string           `db:"created_at" `
	LastUsedAt *sql.Null[string] `db:"last_used_at" `
	RevokedAt  *sql.Null[string] `db:"revoked_at" `
}

func (s ClientAPIKeySetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.Label != nil {
		vals = append(vals, "label")
	}
	if s.KeyHash != nil {
		vals = append(vals, "key_hash")
	}
	if s.KeyPrefix != nil {
		vals = append(vals, "key_prefix")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.LastUsedAt != nil {
		vals = append(vals, "last_used_at")
	}
	if s.RevokedAt != nil {
		vals = append(vals, "revoked_at")
	}
	return vals
}

func (s ClientAPIKeySetter) Overwrite(t *ClientAPIKey) {
	if s.ID != nil {
		t.ID = func() string {
			if s.ID == nil {
				return *new(string)
			}
			return *s.ID
		}()
	}
	if s.Label != nil {
		t.Label = func() string {
			if s.Label == nil {
				return *new(string)
			}
			return *s.Label
		}()
	}
	if s.KeyHash != nil {
		t.KeyHash = func() string {
			if s.KeyHash == nil {
				return *new(string)
			}
			return *s.KeyHash
		}()
	}
	if s.KeyPrefix != nil {
		t.KeyPrefix = func() string {
			if s.KeyPrefix == nil {
				return *new(string)
			}
			return *s.KeyPrefix
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() string {
			if s.CreatedAt == nil {
				return *new(string)
			}
			return *s.CreatedAt
		}()
	}
	if s.LastUsedAt != nil {
		t.LastUsedAt = func() sql.Null[string] {
			if s.LastUsedAt == nil {
				return *new(sql.Null[string])
			}
			v := s.LastUsedAt
			return *v
		}()
	}
	if s.RevokedAt != nil {
		t.RevokedAt = func() sql.Null[string] {
			if s.RevokedAt == nil {
				return *new(sql.Null[string])
			}
			v := s.RevokedAt
			return *v
		}()
	}
}

func (s *ClientAPIKeySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ClientAPIKeys.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.ID == nil {
						return *new(string)
					}
					return *s.ID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "label":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Label == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.Label == nil {
						return *new(string)
					}
					return *s.Label
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "key_hash":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.KeyHash == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.KeyHash == nil {
						return *new(string)
					}
					return *s.KeyHash
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "key_prefix":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.KeyPrefix == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.KeyPrefix == nil {
						return *new(string)
					}
					return *s.KeyPrefix
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "created_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.CreatedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.CreatedAt == nil {
						return *new(string)
					}
					return *s.CreatedAt
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "last_used_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LastUsedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.LastUsedAt == nil {
						return *new(sql.Null[string])
					}
					v := s.LastUsedAt
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "revoked_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.RevokedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.RevokedAt == nil {
						return *new(sql.Null[string])
					}
					v := s.RevokedAt
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s ClientAPIKeySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ClientAPIKeySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.Label != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "label")...),
			sqlite.Arg(s.Label),
		}})
	}

	if s.KeyHash != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "key_hash")...),
			sqlite.Arg(s.KeyHash),
		}})
	}

	if s.KeyPrefix != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "key_prefix")...),
			sqlite.Arg(s.KeyPrefix),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.LastUsedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "last_used_at")...),
			sqlite.Arg(s.LastUsedAt),
		}})
	}

	if s.RevokedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "revoked_at")...),
			sqlite.Arg(s.RevokedAt),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func clientAPIKeyScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*ClientAPIKey, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *ClientAPIKey) any
	}
	targets := make([]target, 0, 7)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *ClientAPIKey) any { return &o.ID }})
		case "label":
			targets = append(targets, target{i, func(o *ClientAPIKey) any { return &o.Label }})
		case "key_hash":
			targets = append(targets, target{i, func(o *ClientAPIKey) any { return &o.KeyHash }})
		case "key_prefix":
			targets = append(targets, target{i, func(o *ClientAPIKey) any { return &o.KeyPrefix }})
		case "created_at":
			targets = append(targets, target{i, func(o *ClientAPIKey) any { return &o.CreatedAt }})
		case "last_used_at":
			targets = append(targets, target{i, func(o *ClientAPIKey) any { return &o.LastUsedAt }})
		case "revoked_at":
			targets = append(targets, target{i, func(o *ClientAPIKey) any { return &o.RevokedAt }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(ClientAPIKey)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*ClientAPIKey, error) {
			return v.(*ClientAPIKey), nil
		}
}

// FindClientAPIKey retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindClientAPIKey(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*ClientAPIKey, error) {
	if len(cols) == 0 {
		return ClientAPIKeys.Query(
			sm.Where(ClientAPIKeys.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ClientAPIKeys.Query(
		sm.Where(ClientAPIKeys.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(ClientAPIKeys.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ClientAPIKeyExists checks the presence of a single record by primary key
func ClientAPIKeyExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return ClientAPIKeys.Query(
		sm.Where(ClientAPIKeys.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ClientAPIKey is retrieved from the database
func (o *ClientAPIKey) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ClientAPIKeys.AfterSelectHooks.RunHooks(ctx, exec, ClientAPIKeySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ClientAPIKeys.AfterInsertHooks.RunHooks(ctx, exec, ClientAPIKeySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ClientAPIKeys.AfterUpdateHooks.RunHooks(ctx, exec, ClientAPIKeySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ClientAPIKeys.AfterDeleteHooks.RunHooks(ctx, exec, ClientAPIKeySlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the ClientAPIKey
func (o *ClientAPIKey) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *ClientAPIKey) pkEQ() dialect.Expression {
	return sqlite.Quote("client_api_keys", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ClientAPIKey
func (o *ClientAPIKey) Update(ctx context.Context, exec bob.Executor, s *ClientAPIKeySetter) error {
	v, err := ClientAPIKeys.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single ClientAPIKey record with an executor
func (o *ClientAPIKey) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ClientAPIKeys.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ClientAPIKey using the executor
func (o *ClientAPIKey) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ClientAPIKeys.Query(
		sm.Where(ClientAPIKeys.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after ClientAPIKeySlice is retrieved from the database
func (o ClientAPIKeySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ClientAPIKeys.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ClientAPIKeys.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ClientAPIKeys.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ClientAPIKeys.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o ClientAPIKeySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("client_api_keys", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ClientAPIKeySlice) copyMatchingRows(from ...*ClientAPIKey) {
	fromByPK := make(map[string]*ClientAPIKey, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}

		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ClientAPIKeySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ClientAPIKeys.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ClientAPIKey:
				o.copyMatchingRows(retrieved)
			case []*ClientAPIKey:
				o.copyMatchingRows(retrieved...)
			case ClientAPIKeySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ClientAPIKey or a slice of ClientAPIKey
				// then run the AfterUpdateHooks on the slice
				_, err = ClientAPIKeys.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ClientAPIKeySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ClientAPIKeys.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ClientAPIKey:
				o.copyMatchingRows(retrieved)
			case []*ClientAPIKey:
				o.copyMatchingRows(retrieved...)
			case ClientAPIKeySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ClientAPIKey or a slice of ClientAPIKey
				// then run the AfterDeleteHooks on the slice
				_, err = ClientAPIKeys.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ClientAPIKeySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ClientAPIKeySetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ClientAPIKeys.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ClientAPIKeySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ClientAPIKeys.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ClientAPIKeySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ClientAPIKeys.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}
