// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"io"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// ModelRoute is an object representing the database table.
type ModelRoute struct {
	ID               string           `db:"id,pk" `
	ModelID          string           `db:"model_id" `
	Provider         string           `db:"provider" `
	UpstreamModel    string           `db:"upstream_model" `
	Protocol         string           `db:"protocol" `
	PriceJSON        string           `db:"price_json" `
	CapabilitiesJSON string           `db:"capabilities_json" `
	Health           string           `db:"health" `
	Trusted          int64            `db:"trusted" `
	ObservedAt       string           `db:"observed_at" `
	StaleAt          sql.Null[string] `db:"stale_at" `

	R modelRouteR `db:"-" `
}

// ModelRouteSlice is an alias for a slice of pointers to ModelRoute.
// This should almost always be used instead of []*ModelRoute.
type ModelRouteSlice []*ModelRoute

// ModelRoutes contains methods to work with the model_routes table
var ModelRoutes = sqlite.NewTablex[*ModelRoute, ModelRouteSlice, *ModelRouteSetter]("", "model_routes", buildModelRouteColumns("model_routes"), modelRouteScanMapper)

// ModelRoutesQuery is a query on the model_routes table
type ModelRoutesQuery = *sqlite.ViewQuery[*ModelRoute, ModelRouteSlice]

// modelRouteR is where relationships are stored.
type modelRouteR struct {
	Model *Model // fk_model_routes_0
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded modelRouteRLoaded `db:"-" `
}

// modelRouteRLoaded tracks which relationships on ModelRoute have been loaded.
type modelRouteRLoaded struct {
	Model bool // fk_model_routes_0
}

func buildModelRouteColumns(tableName string) modelRouteColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "model_id", "provider", "upstream_model", "protocol", "price_json", "capabilities_json", "health", "trusted", "observed_at", "stale_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return modelRouteColumns{
		ColumnsExpr:      columnsExpr,
		tableAlias:       tableName,
		ID:               buildModelRouteColumn(tableName, "id"),
		ModelID:          buildModelRouteColumn(tableName, "model_id"),
		Provider:         buildModelRouteColumn(tableName, "provider"),
		UpstreamModel:    buildModelRouteColumn(tableName, "upstream_model"),
		Protocol:         buildModelRouteColumn(tableName, "protocol"),
		PriceJSON:        buildModelRouteColumn(tableName, "price_json"),
		CapabilitiesJSON: buildModelRouteColumn(tableName, "capabilities_json"),
		Health:           buildModelRouteColumn(tableName, "health"),
		Trusted:          buildModelRouteColumn(tableName, "trusted"),
		ObservedAt:       buildModelRouteColumn(tableName, "observed_at"),
		StaleAt:          buildModelRouteColumn(tableName, "stale_at"),
	}
}

type modelRouteColumns struct {
	expr.ColumnsExpr
	tableAlias       string
	ID               modelRouteColumn
	ModelID          modelRouteColumn
	Provider         modelRouteColumn
	UpstreamModel    modelRouteColumn
	Protocol         modelRouteColumn
	PriceJSON        modelRouteColumn
	CapabilitiesJSON modelRouteColumn
	Health           modelRouteColumn
	Trusted          modelRouteColumn
	ObservedAt       modelRouteColumn
	StaleAt          modelRouteColumn
}

// Alias returns the current table alias for the columns set.
func (c modelRouteColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (modelRouteColumns) AliasedAs(tableName string) modelRouteColumns {
	return buildModelRouteColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c modelRouteColumns) Unqualified() modelRouteColumns {
	return buildModelRouteColumns("")
}

func buildModelRouteColumn(alias, name string) modelRouteColumn {
	return modelRouteColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type modelRouteColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c modelRouteColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c modelRouteColumn) ShouldOmitParens() bool {
	return true
}

// ModelRouteSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ModelRouteSetter struct {
	ID               *string           `db:"id,pk" `
	ModelID          *string           `db:"model_id" `
	Provider         *string           `db:"provider" `
	UpstreamModel    *string           `db:"upstream_model" `
	Protocol         *string           `db:"protocol" `
	PriceJSON        *string           `db:"price_json" `
	CapabilitiesJSON *string           `db:"capabilities_json" `
	Health           *string           `db:"health" `
	Trusted          *int64            `db:"trusted" `
	ObservedAt       *string           `db:"observed_at" `
	StaleAt          *sql.Null[string] `db:"stale_at" `
}

func (s ModelRouteSetter) SetColumns() []string {
	vals := make([]string, 0, 11)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.ModelID != nil {
		vals = append(vals, "model_id")
	}
	if s.Provider != nil {
		vals = append(vals, "provider")
	}
	if s.UpstreamModel != nil {
		vals = append(vals, "upstream_model")
	}
	if s.Protocol != nil {
		vals = append(vals, "protocol")
	}
	if s.PriceJSON != nil {
		vals = append(vals, "price_json")
	}
	if s.CapabilitiesJSON != nil {
		vals = append(vals, "capabilities_json")
	}
	if s.Health != nil {
		vals = append(vals, "health")
	}
	if s.Trusted != nil {
		vals = append(vals, "trusted")
	}
	if s.ObservedAt != nil {
		vals = append(vals, "observed_at")
	}
	if s.StaleAt != nil {
		vals = append(vals, "stale_at")
	}
	return vals
}

func (s ModelRouteSetter) Overwrite(t *ModelRoute) {
	if s.ID != nil {
		t.ID = func() string {
			if s.ID == nil {
				return *new(string)
			}
			return *s.ID
		}()
	}
	if s.ModelID != nil {
		t.ModelID = func() string {
			if s.ModelID == nil {
				return *new(string)
			}
			return *s.ModelID
		}()
	}
	if s.Provider != nil {
		t.Provider = func() string {
			if s.Provider == nil {
				return *new(string)
			}
			return *s.Provider
		}()
	}
	if s.UpstreamModel != nil {
		t.UpstreamModel = func() string {
			if s.UpstreamModel == nil {
				return *new(string)
			}
			return *s.UpstreamModel
		}()
	}
	if s.Protocol != nil {
		t.Protocol = func() string {
			if s.Protocol == nil {
				return *new(string)
			}
			return *s.Protocol
		}()
	}
	if s.PriceJSON != nil {
		t.PriceJSON = func() string {
			if s.PriceJSON == nil {
				return *new(string)
			}
			return *s.PriceJSON
		}()
	}
	if s.CapabilitiesJSON != nil {
		t.CapabilitiesJSON = func() string {
			if s.CapabilitiesJSON == nil {
				return *new(string)
			}
			return *s.CapabilitiesJSON
		}()
	}
	if s.Health != nil {
		t.Health = func() string {
			if s.Health == nil {
				return *new(string)
			}
			return *s.Health
		}()
	}
	if s.Trusted != nil {
		t.Trusted = func() int64 {
			if s.Trusted == nil {
				return *new(int64)
			}
			return *s.Trusted
		}()
	}
	if s.ObservedAt != nil {
		t.ObservedAt = func() string {
			if s.ObservedAt == nil {
				return *new(string)
			}
			return *s.ObservedAt
		}()
	}
	if s.StaleAt != nil {
		t.StaleAt = func() sql.Null[string] {
			if s.StaleAt == nil {
				return *new(sql.Null[string])
			}
			v := s.StaleAt
			return *v
		}()
	}
}

func (s *ModelRouteSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ModelRoutes.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.ID == nil {
						return *new(string)
					}
					return *s.ID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "model_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ModelID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.ModelID == nil {
						return *new(string)
					}
					return *s.ModelID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "provider":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Provider == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.Provider == nil {
						return *new(string)
					}
					return *s.Provider
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "upstream_model":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.UpstreamModel == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.UpstreamModel == nil {
						return *new(string)
					}
					return *s.UpstreamModel
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "protocol":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Protocol == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.Protocol == nil {
						return *new(string)
					}
					return *s.Protocol
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "price_json":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.PriceJSON == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.PriceJSON == nil {
						return *new(string)
					}
					return *s.PriceJSON
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "capabilities_json":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.CapabilitiesJSON == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.CapabilitiesJSON == nil {
						return *new(string)
					}
					return *s.CapabilitiesJSON
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "health":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Health == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.Health == nil {
						return *new(string)
					}
					return *s.Health
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "trusted":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Trusted == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.Trusted == nil {
						return *new(int64)
					}
					return *s.Trusted
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "observed_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ObservedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.ObservedAt == nil {
						return *new(string)
					}
					return *s.ObservedAt
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "stale_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.StaleAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.StaleAt == nil {
						return *new(sql.Null[string])
					}
					v := s.StaleAt
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s ModelRouteSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ModelRouteSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 11)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.ModelID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "model_id")...),
			sqlite.Arg(s.ModelID),
		}})
	}

	if s.Provider != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "provider")...),
			sqlite.Arg(s.Provider),
		}})
	}

	if s.UpstreamModel != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "upstream_model")...),
			sqlite.Arg(s.UpstreamModel),
		}})
	}

	if s.Protocol != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "protocol")...),
			sqlite.Arg(s.Protocol),
		}})
	}

	if s.PriceJSON != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "price_json")...),
			sqlite.Arg(s.PriceJSON),
		}})
	}

	if s.CapabilitiesJSON != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "capabilities_json")...),
			sqlite.Arg(s.CapabilitiesJSON),
		}})
	}

	if s.Health != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "health")...),
			sqlite.Arg(s.Health),
		}})
	}

	if s.Trusted != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "trusted")...),
			sqlite.Arg(s.Trusted),
		}})
	}

	if s.ObservedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "observed_at")...),
			sqlite.Arg(s.ObservedAt),
		}})
	}

	if s.StaleAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "stale_at")...),
			sqlite.Arg(s.StaleAt),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func modelRouteScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*ModelRoute, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *ModelRoute) any
	}
	targets := make([]target, 0, 11)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *ModelRoute) any { return &o.ID }})
		case "model_id":
			targets = append(targets, target{i, func(o *ModelRoute) any { return &o.ModelID }})
		case "provider":
			targets = append(targets, target{i, func(o *ModelRoute) any { return &o.Provider }})
		case "upstream_model":
			targets = append(targets, target{i, func(o *ModelRoute) any { return &o.UpstreamModel }})
		case "protocol":
			targets = append(targets, target{i, func(o *ModelRoute) any { return &o.Protocol }})
		case "price_json":
			targets = append(targets, target{i, func(o *ModelRoute) any { return &o.PriceJSON }})
		case "capabilities_json":
			targets = append(targets, target{i, func(o *ModelRoute) any { return &o.CapabilitiesJSON }})
		case "health":
			targets = append(targets, target{i, func(o *ModelRoute) any { return &o.Health }})
		case "trusted":
			targets = append(targets, target{i, func(o *ModelRoute) any { return &o.Trusted }})
		case "observed_at":
			targets = append(targets, target{i, func(o *ModelRoute) any { return &o.ObservedAt }})
		case "stale_at":
			targets = append(targets, target{i, func(o *ModelRoute) any { return &o.StaleAt }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(ModelRoute)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*ModelRoute, error) {
			return v.(*ModelRoute), nil
		}
}

// FindModelRoute retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindModelRoute(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*ModelRoute, error) {
	if len(cols) == 0 {
		return ModelRoutes.Query(
			sm.Where(ModelRoutes.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ModelRoutes.Query(
		sm.Where(ModelRoutes.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(ModelRoutes.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ModelRouteExists checks the presence of a single record by primary key
func ModelRouteExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return ModelRoutes.Query(
		sm.Where(ModelRoutes.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ModelRoute is retrieved from the database
func (o *ModelRoute) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ModelRoutes.AfterSelectHooks.RunHooks(ctx, exec, ModelRouteSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ModelRoutes.AfterInsertHooks.RunHooks(ctx, exec, ModelRouteSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ModelRoutes.AfterUpdateHooks.RunHooks(ctx, exec, ModelRouteSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ModelRoutes.AfterDeleteHooks.RunHooks(ctx, exec, ModelRouteSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the ModelRoute
func (o *ModelRoute) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *ModelRoute) pkEQ() dialect.Expression {
	return sqlite.Quote("model_routes", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ModelRoute
func (o *ModelRoute) Update(ctx context.Context, exec bob.Executor, s *ModelRouteSetter) error {
	v, err := ModelRoutes.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single ModelRoute record with an executor
func (o *ModelRoute) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ModelRoutes.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ModelRoute using the executor
func (o *ModelRoute) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ModelRoutes.Query(
		sm.Where(ModelRoutes.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ModelRouteSlice is retrieved from the database
func (o ModelRouteSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ModelRoutes.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ModelRoutes.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ModelRoutes.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ModelRoutes.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o ModelRouteSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("model_routes", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ModelRouteSlice) copyMatchingRows(from ...*ModelRoute) {
	fromByPK := make(map[string]*ModelRoute, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}
		new.R = old.R
		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ModelRouteSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ModelRoutes.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ModelRoute:
				o.copyMatchingRows(retrieved)
			case []*ModelRoute:
				o.copyMatchingRows(retrieved...)
			case ModelRouteSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ModelRoute or a slice of ModelRoute
				// then run the AfterUpdateHooks on the slice
				_, err = ModelRoutes.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ModelRouteSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ModelRoutes.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ModelRoute:
				o.copyMatchingRows(retrieved)
			case []*ModelRoute:
				o.copyMatchingRows(retrieved...)
			case ModelRouteSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ModelRoute or a slice of ModelRoute
				// then run the AfterDeleteHooks on the slice
				_, err = ModelRoutes.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ModelRouteSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ModelRouteSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ModelRoutes.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ModelRouteSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ModelRoutes.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ModelRouteSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ModelRoutes.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Model starts a query for related objects on models
func (o *ModelRoute) Model(mods ...bob.Mod[*dialect.SelectQuery]) ModelsQuery {
	return Models.Query(append(mods,
		sm.Where(Models.Columns.ID.EQ(sqlite.Arg(o.ModelID))),
	)...)
}

func (os ModelRouteSlice) Model(mods ...bob.Mod[*dialect.SelectQuery]) ModelsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ModelID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Models.Query(append(mods,
		sm.Where(sqlite.Group(Models.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachModelRouteModel0(ctx context.Context, exec bob.Executor, count int, modelRoute0 *ModelRoute, model1 *Model) (*ModelRoute, error) {
	setter := &ModelRouteSetter{
		ModelID: func() *string { return &model1.ID }(),
	}

	err := modelRoute0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachModelRouteModel0: %w", err)
	}

	return modelRoute0, nil
}

func (modelRoute0 *ModelRoute) InsertModel(ctx context.Context, exec bob.Executor, related *ModelSetter) error {
	var err error

	model1, err := Models.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachModelRouteModel0(ctx, exec, 1, modelRoute0, model1)
	if err != nil {
		return err
	}

	modelRoute0.R.Model = model1
	modelRoute0.R.Loaded.Model = true

	return nil
}

func (modelRoute0 *ModelRoute) AttachModel(ctx context.Context, exec bob.Executor, model1 *Model) error {
	var err error

	_, err = attachModelRouteModel0(ctx, exec, 1, modelRoute0, model1)
	if err != nil {
		return err
	}

	modelRoute0.R.Model = model1
	modelRoute0.R.Loaded.Model = true

	return nil
}
