// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"io"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// Model is an object representing the database table.
type Model struct {
	ID              string           `db:"id,pk" `
	DisplayName     string           `db:"display_name" `
	ContextLength   int64            `db:"context_length" `
	MaxOutputTokens int64            `db:"max_output_tokens" `
	MetadataJSON    string           `db:"metadata_json" `
	ObservedAt      string           `db:"observed_at" `
	StaleAt         sql.Null[string] `db:"stale_at" `

	R modelR `db:"-" `
}

// ModelSlice is an alias for a slice of pointers to Model.
// This should almost always be used instead of []*Model.
type ModelSlice []*Model

// Models contains methods to work with the models table
var Models = sqlite.NewTablex[*Model, ModelSlice, *ModelSetter]("", "models", buildModelColumns("models"), modelScanMapper)

// ModelsQuery is a query on the models table
type ModelsQuery = *sqlite.ViewQuery[*Model, ModelSlice]

// modelR is where relationships are stored.
type modelR struct {
	ModelRoutes ModelRouteSlice // fk_model_routes_0
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded modelRLoaded `db:"-" `
}

// modelRLoaded tracks which relationships on Model have been loaded.
type modelRLoaded struct {
	ModelRoutes bool // fk_model_routes_0
}

func buildModelColumns(tableName string) modelColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "display_name", "context_length", "max_output_tokens", "metadata_json", "observed_at", "stale_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return modelColumns{
		ColumnsExpr:     columnsExpr,
		tableAlias:      tableName,
		ID:              buildModelColumn(tableName, "id"),
		DisplayName:     buildModelColumn(tableName, "display_name"),
		ContextLength:   buildModelColumn(tableName, "context_length"),
		MaxOutputTokens: buildModelColumn(tableName, "max_output_tokens"),
		MetadataJSON:    buildModelColumn(tableName, "metadata_json"),
		ObservedAt:      buildModelColumn(tableName, "observed_at"),
		StaleAt:         buildModelColumn(tableName, "stale_at"),
	}
}

type modelColumns struct {
	expr.ColumnsExpr
	tableAlias      string
	ID              modelColumn
	DisplayName     modelColumn
	ContextLength   modelColumn
	MaxOutputTokens modelColumn
	MetadataJSON    modelColumn
	ObservedAt      modelColumn
	StaleAt         modelColumn
}

// Alias returns the current table alias for the columns set.
func (c modelColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (modelColumns) AliasedAs(tableName string) modelColumns {
	return buildModelColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c modelColumns) Unqualified() modelColumns {
	return buildModelColumns("")
}

func buildModelColumn(alias, name string) modelColumn {
	return modelColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type modelColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c modelColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c modelColumn) ShouldOmitParens() bool {
	return true
}

// ModelSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ModelSetter struct {
	ID              *string           `db:"id,pk" `
	DisplayName     *string           `db:"display_name" `
	ContextLength   *int64            `db:"context_length" `
	MaxOutputTokens *int64            `db:"max_output_tokens" `
	MetadataJSON    *string           `db:"metadata_json" `
	ObservedAt      *string           `db:"observed_at" `
	StaleAt         *sql.Null[string] `db:"stale_at" `
}

func (s ModelSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.DisplayName != nil {
		vals = append(vals, "display_name")
	}
	if s.ContextLength != nil {
		vals = append(vals, "context_length")
	}
	if s.MaxOutputTokens != nil {
		vals = append(vals, "max_output_tokens")
	}
	if s.MetadataJSON != nil {
		vals = append(vals, "metadata_json")
	}
	if s.ObservedAt != nil {
		vals = append(vals, "observed_at")
	}
	if s.StaleAt != nil {
		vals = append(vals, "stale_at")
	}
	return vals
}

func (s ModelSetter) Overwrite(t *Model) {
	if s.ID != nil {
		t.ID = func() string {
			if s.ID == nil {
				return *new(string)
			}
			return *s.ID
		}()
	}
	if s.DisplayName != nil {
		t.DisplayName = func() string {
			if s.DisplayName == nil {
				return *new(string)
			}
			return *s.DisplayName
		}()
	}
	if s.ContextLength != nil {
		t.ContextLength = func() int64 {
			if s.ContextLength == nil {
				return *new(int64)
			}
			return *s.ContextLength
		}()
	}
	if s.MaxOutputTokens != nil {
		t.MaxOutputTokens = func() int64 {
			if s.MaxOutputTokens == nil {
				return *new(int64)
			}
			return *s.MaxOutputTokens
		}()
	}
	if s.MetadataJSON != nil {
		t.MetadataJSON = func() string {
			if s.MetadataJSON == nil {
				return *new(string)
			}
			return *s.MetadataJSON
		}()
	}
	if s.ObservedAt != nil {
		t.ObservedAt = func() string {
			if s.ObservedAt == nil {
				return *new(string)
			}
			return *s.ObservedAt
		}()
	}
	if s.StaleAt != nil {
		t.StaleAt = func() sql.Null[string] {
			if s.StaleAt == nil {
				return *new(sql.Null[string])
			}
			v := s.StaleAt
			return *v
		}()
	}
}

func (s *ModelSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Models.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.ID == nil {
						return *new(string)
					}
					return *s.ID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "display_name":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.DisplayName == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.DisplayName == nil {
						return *new(string)
					}
					return *s.DisplayName
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "context_length":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ContextLength == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.ContextLength == nil {
						return *new(int64)
					}
					return *s.ContextLength
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "max_output_tokens":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.MaxOutputTokens == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.MaxOutputTokens == nil {
						return *new(int64)
					}
					return *s.MaxOutputTokens
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "metadata_json":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.MetadataJSON == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.MetadataJSON == nil {
						return *new(string)
					}
					return *s.MetadataJSON
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "observed_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ObservedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.ObservedAt == nil {
						return *new(string)
					}
					return *s.ObservedAt
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "stale_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.StaleAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.StaleAt == nil {
						return *new(sql.Null[string])
					}
					v := s.StaleAt
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s ModelSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ModelSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.DisplayName != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "display_name")...),
			sqlite.Arg(s.DisplayName),
		}})
	}

	if s.ContextLength != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "context_length")...),
			sqlite.Arg(s.ContextLength),
		}})
	}

	if s.MaxOutputTokens != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "max_output_tokens")...),
			sqlite.Arg(s.MaxOutputTokens),
		}})
	}

	if s.MetadataJSON != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "metadata_json")...),
			sqlite.Arg(s.MetadataJSON),
		}})
	}

	if s.ObservedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "observed_at")...),
			sqlite.Arg(s.ObservedAt),
		}})
	}

	if s.StaleAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "stale_at")...),
			sqlite.Arg(s.StaleAt),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func modelScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Model, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *Model) any
	}
	targets := make([]target, 0, 7)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *Model) any { return &o.ID }})
		case "display_name":
			targets = append(targets, target{i, func(o *Model) any { return &o.DisplayName }})
		case "context_length":
			targets = append(targets, target{i, func(o *Model) any { return &o.ContextLength }})
		case "max_output_tokens":
			targets = append(targets, target{i, func(o *Model) any { return &o.MaxOutputTokens }})
		case "metadata_json":
			targets = append(targets, target{i, func(o *Model) any { return &o.MetadataJSON }})
		case "observed_at":
			targets = append(targets, target{i, func(o *Model) any { return &o.ObservedAt }})
		case "stale_at":
			targets = append(targets, target{i, func(o *Model) any { return &o.StaleAt }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(Model)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*Model, error) {
			return v.(*Model), nil
		}
}

// FindModel retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindModel(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Model, error) {
	if len(cols) == 0 {
		return Models.Query(
			sm.Where(Models.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Models.Query(
		sm.Where(Models.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(Models.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ModelExists checks the presence of a single record by primary key
func ModelExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Models.Query(
		sm.Where(Models.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Model is retrieved from the database
func (o *Model) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Models.AfterSelectHooks.RunHooks(ctx, exec, ModelSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Models.AfterInsertHooks.RunHooks(ctx, exec, ModelSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Models.AfterUpdateHooks.RunHooks(ctx, exec, ModelSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Models.AfterDeleteHooks.RunHooks(ctx, exec, ModelSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the Model
func (o *Model) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *Model) pkEQ() dialect.Expression {
	return sqlite.Quote("models", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Model
func (o *Model) Update(ctx context.Context, exec bob.Executor, s *ModelSetter) error {
	v, err := Models.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Model record with an executor
func (o *Model) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Models.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Model using the executor
func (o *Model) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Models.Query(
		sm.Where(Models.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ModelSlice is retrieved from the database
func (o ModelSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Models.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Models.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Models.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Models.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o ModelSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("models", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ModelSlice) copyMatchingRows(from ...*Model) {
	fromByPK := make(map[string]*Model, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}
		new.R = old.R
		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ModelSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Models.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Model:
				o.copyMatchingRows(retrieved)
			case []*Model:
				o.copyMatchingRows(retrieved...)
			case ModelSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Model or a slice of Model
				// then run the AfterUpdateHooks on the slice
				_, err = Models.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ModelSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Models.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Model:
				o.copyMatchingRows(retrieved)
			case []*Model:
				o.copyMatchingRows(retrieved...)
			case ModelSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Model or a slice of Model
				// then run the AfterDeleteHooks on the slice
				_, err = Models.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ModelSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ModelSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Models.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ModelSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Models.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ModelSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Models.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// ModelRoutes starts a query for related objects on model_routes
func (o *Model) ModelRoutes(mods ...bob.Mod[*dialect.SelectQuery]) ModelRoutesQuery {
	return ModelRoutes.Query(append(mods,
		sm.Where(ModelRoutes.Columns.ModelID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os ModelSlice) ModelRoutes(mods ...bob.Mod[*dialect.SelectQuery]) ModelRoutesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return ModelRoutes.Query(append(mods,
		sm.Where(sqlite.Group(ModelRoutes.Columns.ModelID).OP("IN", PKArgExpr)),
	)...)
}

func insertModelModelRoutes0(ctx context.Context, exec bob.Executor, modelRoutes1 []*ModelRouteSetter, model0 *Model) (ModelRouteSlice, error) {
	for i := range modelRoutes1 {
		modelRoutes1[i].ModelID = func() *string { return &model0.ID }()
	}

	ret, err := ModelRoutes.Insert(bob.ToMods(modelRoutes1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertModelModelRoutes0: %w", err)
	}

	return ret, nil
}

func attachModelModelRoutes0(ctx context.Context, exec bob.Executor, count int, modelRoutes1 ModelRouteSlice, model0 *Model) (ModelRouteSlice, error) {
	setter := &ModelRouteSetter{
		ModelID: func() *string { return &model0.ID }(),
	}

	err := modelRoutes1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachModelModelRoutes0: %w", err)
	}

	return modelRoutes1, nil
}

func (model0 *Model) InsertModelRoutes(ctx context.Context, exec bob.Executor, related ...*ModelRouteSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	modelRoutes1, err := insertModelModelRoutes0(ctx, exec, related, model0)
	if err != nil {
		return err
	}

	model0.R.ModelRoutes = append(model0.R.ModelRoutes, modelRoutes1...)

	return nil
}

func (model0 *Model) AttachModelRoutes(ctx context.Context, exec bob.Executor, related ...*ModelRoute) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	modelRoutes1 := ModelRouteSlice(related)

	_, err = attachModelModelRoutes0(ctx, exec, len(related), modelRoutes1, model0)
	if err != nil {
		return err
	}

	model0.R.ModelRoutes = append(model0.R.ModelRoutes, modelRoutes1...)

	return nil
}
