// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"io"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// ProviderCredential is an object representing the database table.
type ProviderCredential struct {
	ID                     string           `db:"id,pk" `
	Provider               string           `db:"provider" `
	Label                  string           `db:"label" `
	BaseURL                string           `db:"base_url" `
	Ciphertext             []byte           `db:"ciphertext" `
	Nonce                  []byte           `db:"nonce" `
	Enabled                int64            `db:"enabled" `
	CreatedAt              string           `db:"created_at" `
	UpdatedAt              string           `db:"updated_at" `
	LastCheckedAt          sql.Null[string] `db:"last_checked_at" `
	LastError              sql.Null[string] `db:"last_error" `
	ManualModelsJSON       string           `db:"manual_models_json" `
	AccessMode             string           `db:"access_mode" `
	SubscriptionFeePicoUsd sql.Null[int64]  `db:"subscription_fee_pico_usd" `
	SubscriptionCycleStart sql.Null[string] `db:"subscription_cycle_start" `
	SubscriptionCycleEnd   sql.Null[string] `db:"subscription_cycle_end" `
	SubscriptionStatus     string           `db:"subscription_status" `
	NextAvailableAt        sql.Null[string] `db:"next_available_at" `
	StatusReason           sql.Null[string] `db:"status_reason" `
}

// ProviderCredentialSlice is an alias for a slice of pointers to ProviderCredential.
// This should almost always be used instead of []*ProviderCredential.
type ProviderCredentialSlice []*ProviderCredential

// ProviderCredentials contains methods to work with the provider_credentials table
var ProviderCredentials = sqlite.NewTablex[*ProviderCredential, ProviderCredentialSlice, *ProviderCredentialSetter]("", "provider_credentials", buildProviderCredentialColumns("provider_credentials"), providerCredentialScanMapper)

// ProviderCredentialsQuery is a query on the provider_credentials table
type ProviderCredentialsQuery = *sqlite.ViewQuery[*ProviderCredential, ProviderCredentialSlice]

func buildProviderCredentialColumns(tableName string) providerCredentialColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "provider", "label", "base_url", "ciphertext", "nonce", "enabled", "created_at", "updated_at", "last_checked_at", "last_error", "manual_models_json", "access_mode", "subscription_fee_pico_usd", "subscription_cycle_start", "subscription_cycle_end", "subscription_status", "next_available_at", "status_reason",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return providerCredentialColumns{
		ColumnsExpr:            columnsExpr,
		tableAlias:             tableName,
		ID:                     buildProviderCredentialColumn(tableName, "id"),
		Provider:               buildProviderCredentialColumn(tableName, "provider"),
		Label:                  buildProviderCredentialColumn(tableName, "label"),
		BaseURL:                buildProviderCredentialColumn(tableName, "base_url"),
		Ciphertext:             buildProviderCredentialColumn(tableName, "ciphertext"),
		Nonce:                  buildProviderCredentialColumn(tableName, "nonce"),
		Enabled:                buildProviderCredentialColumn(tableName, "enabled"),
		CreatedAt:              buildProviderCredentialColumn(tableName, "created_at"),
		UpdatedAt:              buildProviderCredentialColumn(tableName, "updated_at"),
		LastCheckedAt:          buildProviderCredentialColumn(tableName, "last_checked_at"),
		LastError:              buildProviderCredentialColumn(tableName, "last_error"),
		ManualModelsJSON:       buildProviderCredentialColumn(tableName, "manual_models_json"),
		AccessMode:             buildProviderCredentialColumn(tableName, "access_mode"),
		SubscriptionFeePicoUsd: buildProviderCredentialColumn(tableName, "subscription_fee_pico_usd"),
		SubscriptionCycleStart: buildProviderCredentialColumn(tableName, "subscription_cycle_start"),
		SubscriptionCycleEnd:   buildProviderCredentialColumn(tableName, "subscription_cycle_end"),
		SubscriptionStatus:     buildProviderCredentialColumn(tableName, "subscription_status"),
		NextAvailableAt:        buildProviderCredentialColumn(tableName, "next_available_at"),
		StatusReason:           buildProviderCredentialColumn(tableName, "status_reason"),
	}
}

type providerCredentialColumns struct {
	expr.ColumnsExpr
	tableAlias             string
	ID                     providerCredentialColumn
	Provider               providerCredentialColumn
	Label                  providerCredentialColumn
	BaseURL                providerCredentialColumn
	Ciphertext             providerCredentialColumn
	Nonce                  providerCredentialColumn
	Enabled                providerCredentialColumn
	CreatedAt              providerCredentialColumn
	UpdatedAt              providerCredentialColumn
	LastCheckedAt          providerCredentialColumn
	LastError              providerCredentialColumn
	ManualModelsJSON       providerCredentialColumn
	AccessMode             providerCredentialColumn
	SubscriptionFeePicoUsd providerCredentialColumn
	SubscriptionCycleStart providerCredentialColumn
	SubscriptionCycleEnd   providerCredentialColumn
	SubscriptionStatus     providerCredentialColumn
	NextAvailableAt        providerCredentialColumn
	StatusReason           providerCredentialColumn
}

// Alias returns the current table alias for the columns set.
func (c providerCredentialColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (providerCredentialColumns) AliasedAs(tableName string) providerCredentialColumns {
	return buildProviderCredentialColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c providerCredentialColumns) Unqualified() providerCredentialColumns {
	return buildProviderCredentialColumns("")
}

func buildProviderCredentialColumn(alias, name string) providerCredentialColumn {
	return providerCredentialColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type providerCredentialColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c providerCredentialColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c providerCredentialColumn) ShouldOmitParens() bool {
	return true
}

// ProviderCredentialSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ProviderCredentialSetter struct {
	ID                     *string           `db:"id,pk" `
	Provider               *string           `db:"provider" `
	Label                  *string           `db:"label" `
	BaseURL                *string           `db:"base_url" `
	Ciphertext             *[]byte           `db:"ciphertext" `
	Nonce                  *[]byte           `db:"nonce" `
	Enabled                *int64            `db:"enabled" `
	CreatedAt              *string           `db:"created_at" `
	UpdatedAt              *string           `db:"updated_at" `
	LastCheckedAt          *sql.Null[string] `db:"last_checked_at" `
	LastError              *sql.Null[string] `db:"last_error" `
	ManualModelsJSON       *string           `db:"manual_models_json" `
	AccessMode             *string           `db:"access_mode" `
	SubscriptionFeePicoUsd *sql.Null[int64]  `db:"subscription_fee_pico_usd" `
	SubscriptionCycleStart *sql.Null[string] `db:"subscription_cycle_start" `
	SubscriptionCycleEnd   *sql.Null[string] `db:"subscription_cycle_end" `
	SubscriptionStatus     *string           `db:"subscription_status" `
	NextAvailableAt        *sql.Null[string] `db:"next_available_at" `
	StatusReason           *sql.Null[string] `db:"status_reason" `
}

func (s ProviderCredentialSetter) SetColumns() []string {
	vals := make([]string, 0, 19)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.Provider != nil {
		vals = append(vals, "provider")
	}
	if s.Label != nil {
		vals = append(vals, "label")
	}
	if s.BaseURL != nil {
		vals = append(vals, "base_url")
	}
	if s.Ciphertext != nil {
		vals = append(vals, "ciphertext")
	}
	if s.Nonce != nil {
		vals = append(vals, "nonce")
	}
	if s.Enabled != nil {
		vals = append(vals, "enabled")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	if s.LastCheckedAt != nil {
		vals = append(vals, "last_checked_at")
	}
	if s.LastError != nil {
		vals = append(vals, "last_error")
	}
	if s.ManualModelsJSON != nil {
		vals = append(vals, "manual_models_json")
	}
	if s.AccessMode != nil {
		vals = append(vals, "access_mode")
	}
	if s.SubscriptionFeePicoUsd != nil {
		vals = append(vals, "subscription_fee_pico_usd")
	}
	if s.SubscriptionCycleStart != nil {
		vals = append(vals, "subscription_cycle_start")
	}
	if s.SubscriptionCycleEnd != nil {
		vals = append(vals, "subscription_cycle_end")
	}
	if s.SubscriptionStatus != nil {
		vals = append(vals, "subscription_status")
	}
	if s.NextAvailableAt != nil {
		vals = append(vals, "next_available_at")
	}
	if s.StatusReason != nil {
		vals = append(vals, "status_reason")
	}
	return vals
}

func (s ProviderCredentialSetter) Overwrite(t *ProviderCredential) {
	if s.ID != nil {
		t.ID = func() string {
			if s.ID == nil {
				return *new(string)
			}
			return *s.ID
		}()
	}
	if s.Provider != nil {
		t.Provider = func() string {
			if s.Provider == nil {
				return *new(string)
			}
			return *s.Provider
		}()
	}
	if s.Label != nil {
		t.Label = func() string {
			if s.Label == nil {
				return *new(string)
			}
			return *s.Label
		}()
	}
	if s.BaseURL != nil {
		t.BaseURL = func() string {
			if s.BaseURL == nil {
				return *new(string)
			}
			return *s.BaseURL
		}()
	}
	if s.Ciphertext != nil {
		t.Ciphertext = func() []byte {
			if s.Ciphertext == nil {
				return *new([]byte)
			}
			return *s.Ciphertext
		}()
	}
	if s.Nonce != nil {
		t.Nonce = func() []byte {
			if s.Nonce == nil {
				return *new([]byte)
			}
			return *s.Nonce
		}()
	}
	if s.Enabled != nil {
		t.Enabled = func() int64 {
			if s.Enabled == nil {
				return *new(int64)
			}
			return *s.Enabled
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() string {
			if s.CreatedAt == nil {
				return *new(string)
			}
			return *s.CreatedAt
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() string {
			if s.UpdatedAt == nil {
				return *new(string)
			}
			return *s.UpdatedAt
		}()
	}
	if s.LastCheckedAt != nil {
		t.LastCheckedAt = func() sql.Null[string] {
			if s.LastCheckedAt == nil {
				return *new(sql.Null[string])
			}
			v := s.LastCheckedAt
			return *v
		}()
	}
	if s.LastError != nil {
		t.LastError = func() sql.Null[string] {
			if s.LastError == nil {
				return *new(sql.Null[string])
			}
			v := s.LastError
			return *v
		}()
	}
	if s.ManualModelsJSON != nil {
		t.ManualModelsJSON = func() string {
			if s.ManualModelsJSON == nil {
				return *new(string)
			}
			return *s.ManualModelsJSON
		}()
	}
	if s.AccessMode != nil {
		t.AccessMode = func() string {
			if s.AccessMode == nil {
				return *new(string)
			}
			return *s.AccessMode
		}()
	}
	if s.SubscriptionFeePicoUsd != nil {
		t.SubscriptionFeePicoUsd = func() sql.Null[int64] {
			if s.SubscriptionFeePicoUsd == nil {
				return *new(sql.Null[int64])
			}
			v := s.SubscriptionFeePicoUsd
			return *v
		}()
	}
	if s.SubscriptionCycleStart != nil {
		t.SubscriptionCycleStart = func() sql.Null[string] {
			if s.SubscriptionCycleStart == nil {
				return *new(sql.Null[string])
			}
			v := s.SubscriptionCycleStart
			return *v
		}()
	}
	if s.SubscriptionCycleEnd != nil {
		t.SubscriptionCycleEnd = func() sql.Null[string] {
			if s.SubscriptionCycleEnd == nil {
				return *new(sql.Null[string])
			}
			v := s.SubscriptionCycleEnd
			return *v
		}()
	}
	if s.SubscriptionStatus != nil {
		t.SubscriptionStatus = func() string {
			if s.SubscriptionStatus == nil {
				return *new(string)
			}
			return *s.SubscriptionStatus
		}()
	}
	if s.NextAvailableAt != nil {
		t.NextAvailableAt = func() sql.Null[string] {
			if s.NextAvailableAt == nil {
				return *new(sql.Null[string])
			}
			v := s.NextAvailableAt
			return *v
		}()
	}
	if s.StatusReason != nil {
		t.StatusReason = func() sql.Null[string] {
			if s.StatusReason == nil {
				return *new(sql.Null[string])
			}
			v := s.StatusReason
			return *v
		}()
	}
}

func (s *ProviderCredentialSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ProviderCredentials.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.ID == nil {
						return *new(string)
					}
					return *s.ID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "provider":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Provider == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.Provider == nil {
						return *new(string)
					}
					return *s.Provider
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "label":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Label == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.Label == nil {
						return *new(string)
					}
					return *s.Label
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "base_url":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.BaseURL == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.BaseURL == nil {
						return *new(string)
					}
					return *s.BaseURL
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "ciphertext":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Ciphertext == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() []byte {
					if s.Ciphertext == nil {
						return *new([]byte)
					}
					return *s.Ciphertext
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "nonce":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Nonce == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() []byte {
					if s.Nonce == nil {
						return *new([]byte)
					}
					return *s.Nonce
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "enabled":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Enabled == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.Enabled == nil {
						return *new(int64)
					}
					return *s.Enabled
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "created_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.CreatedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.CreatedAt == nil {
						return *new(string)
					}
					return *s.CreatedAt
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "updated_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.UpdatedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.UpdatedAt == nil {
						return *new(string)
					}
					return *s.UpdatedAt
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "last_checked_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LastCheckedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.LastCheckedAt == nil {
						return *new(sql.Null[string])
					}
					v := s.LastCheckedAt
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "last_error":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LastError == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.LastError == nil {
						return *new(sql.Null[string])
					}
					v := s.LastError
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "manual_models_json":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ManualModelsJSON == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.ManualModelsJSON == nil {
						return *new(string)
					}
					return *s.ManualModelsJSON
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "access_mode":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.AccessMode == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.AccessMode == nil {
						return *new(string)
					}
					return *s.AccessMode
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "subscription_fee_pico_usd":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.SubscriptionFeePicoUsd == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[int64] {
					if s.SubscriptionFeePicoUsd == nil {
						return *new(sql.Null[int64])
					}
					v := s.SubscriptionFeePicoUsd
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "subscription_cycle_start":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.SubscriptionCycleStart == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.SubscriptionCycleStart == nil {
						return *new(sql.Null[string])
					}
					v := s.SubscriptionCycleStart
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "subscription_cycle_end":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.SubscriptionCycleEnd == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.SubscriptionCycleEnd == nil {
						return *new(sql.Null[string])
					}
					v := s.SubscriptionCycleEnd
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "subscription_status":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.SubscriptionStatus == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.SubscriptionStatus == nil {
						return *new(string)
					}
					return *s.SubscriptionStatus
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "next_available_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.NextAvailableAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.NextAvailableAt == nil {
						return *new(sql.Null[string])
					}
					v := s.NextAvailableAt
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "status_reason":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.StatusReason == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.StatusReason == nil {
						return *new(sql.Null[string])
					}
					v := s.StatusReason
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s ProviderCredentialSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ProviderCredentialSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 19)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.Provider != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "provider")...),
			sqlite.Arg(s.Provider),
		}})
	}

	if s.Label != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "label")...),
			sqlite.Arg(s.Label),
		}})
	}

	if s.BaseURL != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "base_url")...),
			sqlite.Arg(s.BaseURL),
		}})
	}

	if s.Ciphertext != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "ciphertext")...),
			sqlite.Arg(s.Ciphertext),
		}})
	}

	if s.Nonce != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "nonce")...),
			sqlite.Arg(s.Nonce),
		}})
	}

	if s.Enabled != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "enabled")...),
			sqlite.Arg(s.Enabled),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	if s.LastCheckedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "last_checked_at")...),
			sqlite.Arg(s.LastCheckedAt),
		}})
	}

	if s.LastError != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "last_error")...),
			sqlite.Arg(s.LastError),
		}})
	}

	if s.ManualModelsJSON != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "manual_models_json")...),
			sqlite.Arg(s.ManualModelsJSON),
		}})
	}

	if s.AccessMode != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "access_mode")...),
			sqlite.Arg(s.AccessMode),
		}})
	}

	if s.SubscriptionFeePicoUsd != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "subscription_fee_pico_usd")...),
			sqlite.Arg(s.SubscriptionFeePicoUsd),
		}})
	}

	if s.SubscriptionCycleStart != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "subscription_cycle_start")...),
			sqlite.Arg(s.SubscriptionCycleStart),
		}})
	}

	if s.SubscriptionCycleEnd != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "subscription_cycle_end")...),
			sqlite.Arg(s.SubscriptionCycleEnd),
		}})
	}

	if s.SubscriptionStatus != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "subscription_status")...),
			sqlite.Arg(s.SubscriptionStatus),
		}})
	}

	if s.NextAvailableAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "next_available_at")...),
			sqlite.Arg(s.NextAvailableAt),
		}})
	}

	if s.StatusReason != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "status_reason")...),
			sqlite.Arg(s.StatusReason),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func providerCredentialScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*ProviderCredential, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *ProviderCredential) any
	}
	targets := make([]target, 0, 19)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.ID }})
		case "provider":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.Provider }})
		case "label":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.Label }})
		case "base_url":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.BaseURL }})
		case "ciphertext":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.Ciphertext }})
		case "nonce":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.Nonce }})
		case "enabled":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.Enabled }})
		case "created_at":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.CreatedAt }})
		case "updated_at":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.UpdatedAt }})
		case "last_checked_at":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.LastCheckedAt }})
		case "last_error":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.LastError }})
		case "manual_models_json":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.ManualModelsJSON }})
		case "access_mode":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.AccessMode }})
		case "subscription_fee_pico_usd":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.SubscriptionFeePicoUsd }})
		case "subscription_cycle_start":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.SubscriptionCycleStart }})
		case "subscription_cycle_end":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.SubscriptionCycleEnd }})
		case "subscription_status":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.SubscriptionStatus }})
		case "next_available_at":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.NextAvailableAt }})
		case "status_reason":
			targets = append(targets, target{i, func(o *ProviderCredential) any { return &o.StatusReason }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(ProviderCredential)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*ProviderCredential, error) {
			return v.(*ProviderCredential), nil
		}
}

// FindProviderCredential retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindProviderCredential(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*ProviderCredential, error) {
	if len(cols) == 0 {
		return ProviderCredentials.Query(
			sm.Where(ProviderCredentials.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ProviderCredentials.Query(
		sm.Where(ProviderCredentials.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(ProviderCredentials.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ProviderCredentialExists checks the presence of a single record by primary key
func ProviderCredentialExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return ProviderCredentials.Query(
		sm.Where(ProviderCredentials.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ProviderCredential is retrieved from the database
func (o *ProviderCredential) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ProviderCredentials.AfterSelectHooks.RunHooks(ctx, exec, ProviderCredentialSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ProviderCredentials.AfterInsertHooks.RunHooks(ctx, exec, ProviderCredentialSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ProviderCredentials.AfterUpdateHooks.RunHooks(ctx, exec, ProviderCredentialSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ProviderCredentials.AfterDeleteHooks.RunHooks(ctx, exec, ProviderCredentialSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the ProviderCredential
func (o *ProviderCredential) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *ProviderCredential) pkEQ() dialect.Expression {
	return sqlite.Quote("provider_credentials", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ProviderCredential
func (o *ProviderCredential) Update(ctx context.Context, exec bob.Executor, s *ProviderCredentialSetter) error {
	v, err := ProviderCredentials.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single ProviderCredential record with an executor
func (o *ProviderCredential) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ProviderCredentials.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ProviderCredential using the executor
func (o *ProviderCredential) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ProviderCredentials.Query(
		sm.Where(ProviderCredentials.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after ProviderCredentialSlice is retrieved from the database
func (o ProviderCredentialSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ProviderCredentials.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ProviderCredentials.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ProviderCredentials.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ProviderCredentials.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o ProviderCredentialSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("provider_credentials", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ProviderCredentialSlice) copyMatchingRows(from ...*ProviderCredential) {
	fromByPK := make(map[string]*ProviderCredential, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}

		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ProviderCredentialSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ProviderCredentials.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ProviderCredential:
				o.copyMatchingRows(retrieved)
			case []*ProviderCredential:
				o.copyMatchingRows(retrieved...)
			case ProviderCredentialSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ProviderCredential or a slice of ProviderCredential
				// then run the AfterUpdateHooks on the slice
				_, err = ProviderCredentials.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ProviderCredentialSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ProviderCredentials.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ProviderCredential:
				o.copyMatchingRows(retrieved)
			case []*ProviderCredential:
				o.copyMatchingRows(retrieved...)
			case ProviderCredentialSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ProviderCredential or a slice of ProviderCredential
				// then run the AfterDeleteHooks on the slice
				_, err = ProviderCredentials.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ProviderCredentialSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ProviderCredentialSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ProviderCredentials.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ProviderCredentialSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ProviderCredentials.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ProviderCredentialSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ProviderCredentials.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}
