// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"io"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// ProviderHealth is an object representing the database table.
type ProviderHealth struct {
	RouteID      string           `db:"route_id,pk" `
	FailureCount int64            `db:"failure_count" `
	State        string           `db:"state" `
	BackoffUntil sql.Null[string] `db:"backoff_until" `
	LastError    sql.Null[string] `db:"last_error" `
	UpdatedAt    string           `db:"updated_at" `
}

// ProviderHealthSlice is an alias for a slice of pointers to ProviderHealth.
// This should almost always be used instead of []*ProviderHealth.
type ProviderHealthSlice []*ProviderHealth

// ProviderHealths contains methods to work with the provider_health table
var ProviderHealths = sqlite.NewTablex[*ProviderHealth, ProviderHealthSlice, *ProviderHealthSetter]("", "provider_health", buildProviderHealthColumns("provider_health"), providerHealthScanMapper)

// ProviderHealthsQuery is a query on the provider_health table
type ProviderHealthsQuery = *sqlite.ViewQuery[*ProviderHealth, ProviderHealthSlice]

func buildProviderHealthColumns(tableName string) providerHealthColumns {
	columnsExpr := expr.NewColumnsExpr(
		"route_id", "failure_count", "state", "backoff_until", "last_error", "updated_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return providerHealthColumns{
		ColumnsExpr:  columnsExpr,
		tableAlias:   tableName,
		RouteID:      buildProviderHealthColumn(tableName, "route_id"),
		FailureCount: buildProviderHealthColumn(tableName, "failure_count"),
		State:        buildProviderHealthColumn(tableName, "state"),
		BackoffUntil: buildProviderHealthColumn(tableName, "backoff_until"),
		LastError:    buildProviderHealthColumn(tableName, "last_error"),
		UpdatedAt:    buildProviderHealthColumn(tableName, "updated_at"),
	}
}

type providerHealthColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	RouteID      providerHealthColumn
	FailureCount providerHealthColumn
	State        providerHealthColumn
	BackoffUntil providerHealthColumn
	LastError    providerHealthColumn
	UpdatedAt    providerHealthColumn
}

// Alias returns the current table alias for the columns set.
func (c providerHealthColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (providerHealthColumns) AliasedAs(tableName string) providerHealthColumns {
	return buildProviderHealthColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c providerHealthColumns) Unqualified() providerHealthColumns {
	return buildProviderHealthColumns("")
}

func buildProviderHealthColumn(alias, name string) providerHealthColumn {
	return providerHealthColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type providerHealthColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c providerHealthColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c providerHealthColumn) ShouldOmitParens() bool {
	return true
}

// ProviderHealthSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ProviderHealthSetter struct {
	RouteID      *string           `db:"route_id,pk" `
	FailureCount *int64            `db:"failure_count" `
	State        *string           `db:"state" `
	BackoffUntil *sql.Null[string] `db:"backoff_until" `
	LastError    *sql.Null[string] `db:"last_error" `
	UpdatedAt    *string           `db:"updated_at" `
}

func (s ProviderHealthSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.RouteID != nil {
		vals = append(vals, "route_id")
	}
	if s.FailureCount != nil {
		vals = append(vals, "failure_count")
	}
	if s.State != nil {
		vals = append(vals, "state")
	}
	if s.BackoffUntil != nil {
		vals = append(vals, "backoff_until")
	}
	if s.LastError != nil {
		vals = append(vals, "last_error")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ProviderHealthSetter) Overwrite(t *ProviderHealth) {
	if s.RouteID != nil {
		t.RouteID = func() string {
			if s.RouteID == nil {
				return *new(string)
			}
			return *s.RouteID
		}()
	}
	if s.FailureCount != nil {
		t.FailureCount = func() int64 {
			if s.FailureCount == nil {
				return *new(int64)
			}
			return *s.FailureCount
		}()
	}
	if s.State != nil {
		t.State = func() string {
			if s.State == nil {
				return *new(string)
			}
			return *s.State
		}()
	}
	if s.BackoffUntil != nil {
		t.BackoffUntil = func() sql.Null[string] {
			if s.BackoffUntil == nil {
				return *new(sql.Null[string])
			}
			v := s.BackoffUntil
			return *v
		}()
	}
	if s.LastError != nil {
		t.LastError = func() sql.Null[string] {
			if s.LastError == nil {
				return *new(sql.Null[string])
			}
			v := s.LastError
			return *v
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() string {
			if s.UpdatedAt == nil {
				return *new(string)
			}
			return *s.UpdatedAt
		}()
	}
}

func (s *ProviderHealthSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ProviderHealths.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"route_id"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "route_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.RouteID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.RouteID == nil {
						return *new(string)
					}
					return *s.RouteID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "failure_count":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.FailureCount == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.FailureCount == nil {
						return *new(int64)
					}
					return *s.FailureCount
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "state":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.State == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.State == nil {
						return *new(string)
					}
					return *s.State
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "backoff_until":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.BackoffUntil == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.BackoffUntil == nil {
						return *new(sql.Null[string])
					}
					v := s.BackoffUntil
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "last_error":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LastError == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.LastError == nil {
						return *new(sql.Null[string])
					}
					v := s.LastError
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "updated_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.UpdatedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.UpdatedAt == nil {
						return *new(string)
					}
					return *s.UpdatedAt
				}()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s ProviderHealthSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ProviderHealthSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.RouteID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "route_id")...),
			sqlite.Arg(s.RouteID),
		}})
	}

	if s.FailureCount != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "failure_count")...),
			sqlite.Arg(s.FailureCount),
		}})
	}

	if s.State != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "state")...),
			sqlite.Arg(s.State),
		}})
	}

	if s.BackoffUntil != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "backoff_until")...),
			sqlite.Arg(s.BackoffUntil),
		}})
	}

	if s.LastError != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "last_error")...),
			sqlite.Arg(s.LastError),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func providerHealthScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*ProviderHealth, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *ProviderHealth) any
	}
	targets := make([]target, 0, 6)
	for i, col := range cols {
		switch col {
		case "route_id":
			targets = append(targets, target{i, func(o *ProviderHealth) any { return &o.RouteID }})
		case "failure_count":
			targets = append(targets, target{i, func(o *ProviderHealth) any { return &o.FailureCount }})
		case "state":
			targets = append(targets, target{i, func(o *ProviderHealth) any { return &o.State }})
		case "backoff_until":
			targets = append(targets, target{i, func(o *ProviderHealth) any { return &o.BackoffUntil }})
		case "last_error":
			targets = append(targets, target{i, func(o *ProviderHealth) any { return &o.LastError }})
		case "updated_at":
			targets = append(targets, target{i, func(o *ProviderHealth) any { return &o.UpdatedAt }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(ProviderHealth)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*ProviderHealth, error) {
			return v.(*ProviderHealth), nil
		}
}

// FindProviderHealth retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindProviderHealth(ctx context.Context, exec bob.Executor, RouteIDPK string, cols ...string) (*ProviderHealth, error) {
	if len(cols) == 0 {
		return ProviderHealths.Query(
			sm.Where(ProviderHealths.Columns.RouteID.EQ(sqlite.Arg(RouteIDPK))),
		).One(ctx, exec)
	}

	return ProviderHealths.Query(
		sm.Where(ProviderHealths.Columns.RouteID.EQ(sqlite.Arg(RouteIDPK))),
		sm.Columns(ProviderHealths.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ProviderHealthExists checks the presence of a single record by primary key
func ProviderHealthExists(ctx context.Context, exec bob.Executor, RouteIDPK string) (bool, error) {
	return ProviderHealths.Query(
		sm.Where(ProviderHealths.Columns.RouteID.EQ(sqlite.Arg(RouteIDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ProviderHealth is retrieved from the database
func (o *ProviderHealth) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ProviderHealths.AfterSelectHooks.RunHooks(ctx, exec, ProviderHealthSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ProviderHealths.AfterInsertHooks.RunHooks(ctx, exec, ProviderHealthSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ProviderHealths.AfterUpdateHooks.RunHooks(ctx, exec, ProviderHealthSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ProviderHealths.AfterDeleteHooks.RunHooks(ctx, exec, ProviderHealthSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the ProviderHealth
func (o *ProviderHealth) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.RouteID)
}

func (o *ProviderHealth) pkEQ() dialect.Expression {
	return sqlite.Quote("provider_health", "route_id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ProviderHealth
func (o *ProviderHealth) Update(ctx context.Context, exec bob.Executor, s *ProviderHealthSetter) error {
	v, err := ProviderHealths.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single ProviderHealth record with an executor
func (o *ProviderHealth) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ProviderHealths.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ProviderHealth using the executor
func (o *ProviderHealth) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ProviderHealths.Query(
		sm.Where(ProviderHealths.Columns.RouteID.EQ(sqlite.Arg(o.RouteID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after ProviderHealthSlice is retrieved from the database
func (o ProviderHealthSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ProviderHealths.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ProviderHealths.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ProviderHealths.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ProviderHealths.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o ProviderHealthSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("provider_health", "route_id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ProviderHealthSlice) copyMatchingRows(from ...*ProviderHealth) {
	fromByPK := make(map[string]*ProviderHealth, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.RouteID]; !ok {
			fromByPK[new.RouteID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.RouteID]
		if !ok {
			continue
		}

		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ProviderHealthSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ProviderHealths.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ProviderHealth:
				o.copyMatchingRows(retrieved)
			case []*ProviderHealth:
				o.copyMatchingRows(retrieved...)
			case ProviderHealthSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ProviderHealth or a slice of ProviderHealth
				// then run the AfterUpdateHooks on the slice
				_, err = ProviderHealths.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ProviderHealthSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ProviderHealths.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ProviderHealth:
				o.copyMatchingRows(retrieved)
			case []*ProviderHealth:
				o.copyMatchingRows(retrieved...)
			case ProviderHealthSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ProviderHealth or a slice of ProviderHealth
				// then run the AfterDeleteHooks on the slice
				_, err = ProviderHealths.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ProviderHealthSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ProviderHealthSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ProviderHealths.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ProviderHealthSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ProviderHealths.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ProviderHealthSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ProviderHealths.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}
