// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"io"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// ProxyRequest is an object representing the database table.
type ProxyRequest struct {
	ID                    string           `db:"id,pk" `
	ClientKeyID           sql.Null[string] `db:"client_key_id" `
	Protocol              string           `db:"protocol" `
	LogicalModel          string           `db:"logical_model" `
	State                 string           `db:"state" `
	ReceivedAt            string           `db:"received_at" `
	CompletedAt           sql.Null[string] `db:"completed_at" `
	SelectedProvider      sql.Null[string] `db:"selected_provider" `
	SelectedUpstreamModel sql.Null[string] `db:"selected_upstream_model" `
	AttemptCount          int64            `db:"attempt_count" `
	DurationMS            sql.Null[int64]  `db:"duration_ms" `
	ErrorCode             sql.Null[string] `db:"error_code" `
	ErrorMessage          sql.Null[string] `db:"error_message" `
	StatsDisposition      string           `db:"stats_disposition" `
	ResolvedGroupID       sql.Null[string] `db:"resolved_group_id" `
	ResolvedGroupRevision sql.Null[int64]  `db:"resolved_group_revision" `
	ResolvedPlanJSON      sql.Null[string] `db:"resolved_plan_json" `
	SelectedLogicalModel  sql.Null[string] `db:"selected_logical_model" `

	R proxyRequestR `db:"-" `
}

// ProxyRequestSlice is an alias for a slice of pointers to ProxyRequest.
// This should almost always be used instead of []*ProxyRequest.
type ProxyRequestSlice []*ProxyRequest

// ProxyRequests contains methods to work with the proxy_requests table
var ProxyRequests = sqlite.NewTablex[*ProxyRequest, ProxyRequestSlice, *ProxyRequestSetter]("", "proxy_requests", buildProxyRequestColumns("proxy_requests"), proxyRequestScanMapper)

// ProxyRequestsQuery is a query on the proxy_requests table
type ProxyRequestsQuery = *sqlite.ViewQuery[*ProxyRequest, ProxyRequestSlice]

// proxyRequestR is where relationships are stored.
type proxyRequestR struct {
	RequestProxyAttempts ProxyAttemptSlice // fk_proxy_attempts_0
	RequestRequestUsage  *RequestUsage     // fk_request_usage_0
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded proxyRequestRLoaded `db:"-" `
}

// proxyRequestRLoaded tracks which relationships on ProxyRequest have been loaded.
type proxyRequestRLoaded struct {
	RequestProxyAttempts bool // fk_proxy_attempts_0
	RequestRequestUsage  bool // fk_request_usage_0
}

func buildProxyRequestColumns(tableName string) proxyRequestColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "client_key_id", "protocol", "logical_model", "state", "received_at", "completed_at", "selected_provider", "selected_upstream_model", "attempt_count", "duration_ms", "error_code", "error_message", "stats_disposition", "resolved_group_id", "resolved_group_revision", "resolved_plan_json", "selected_logical_model",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return proxyRequestColumns{
		ColumnsExpr:           columnsExpr,
		tableAlias:            tableName,
		ID:                    buildProxyRequestColumn(tableName, "id"),
		ClientKeyID:           buildProxyRequestColumn(tableName, "client_key_id"),
		Protocol:              buildProxyRequestColumn(tableName, "protocol"),
		LogicalModel:          buildProxyRequestColumn(tableName, "logical_model"),
		State:                 buildProxyRequestColumn(tableName, "state"),
		ReceivedAt:            buildProxyRequestColumn(tableName, "received_at"),
		CompletedAt:           buildProxyRequestColumn(tableName, "completed_at"),
		SelectedProvider:      buildProxyRequestColumn(tableName, "selected_provider"),
		SelectedUpstreamModel: buildProxyRequestColumn(tableName, "selected_upstream_model"),
		AttemptCount:          buildProxyRequestColumn(tableName, "attempt_count"),
		DurationMS:            buildProxyRequestColumn(tableName, "duration_ms"),
		ErrorCode:             buildProxyRequestColumn(tableName, "error_code"),
		ErrorMessage:          buildProxyRequestColumn(tableName, "error_message"),
		StatsDisposition:      buildProxyRequestColumn(tableName, "stats_disposition"),
		ResolvedGroupID:       buildProxyRequestColumn(tableName, "resolved_group_id"),
		ResolvedGroupRevision: buildProxyRequestColumn(tableName, "resolved_group_revision"),
		ResolvedPlanJSON:      buildProxyRequestColumn(tableName, "resolved_plan_json"),
		SelectedLogicalModel:  buildProxyRequestColumn(tableName, "selected_logical_model"),
	}
}

type proxyRequestColumns struct {
	expr.ColumnsExpr
	tableAlias            string
	ID                    proxyRequestColumn
	ClientKeyID           proxyRequestColumn
	Protocol              proxyRequestColumn
	LogicalModel          proxyRequestColumn
	State                 proxyRequestColumn
	ReceivedAt            proxyRequestColumn
	CompletedAt           proxyRequestColumn
	SelectedProvider      proxyRequestColumn
	SelectedUpstreamModel proxyRequestColumn
	AttemptCount          proxyRequestColumn
	DurationMS            proxyRequestColumn
	ErrorCode             proxyRequestColumn
	ErrorMessage          proxyRequestColumn
	StatsDisposition      proxyRequestColumn
	ResolvedGroupID       proxyRequestColumn
	ResolvedGroupRevision proxyRequestColumn
	ResolvedPlanJSON      proxyRequestColumn
	SelectedLogicalModel  proxyRequestColumn
}

// Alias returns the current table alias for the columns set.
func (c proxyRequestColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (proxyRequestColumns) AliasedAs(tableName string) proxyRequestColumns {
	return buildProxyRequestColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c proxyRequestColumns) Unqualified() proxyRequestColumns {
	return buildProxyRequestColumns("")
}

func buildProxyRequestColumn(alias, name string) proxyRequestColumn {
	return proxyRequestColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type proxyRequestColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c proxyRequestColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c proxyRequestColumn) ShouldOmitParens() bool {
	return true
}

// ProxyRequestSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ProxyRequestSetter struct {
	ID                    *string           `db:"id,pk" `
	ClientKeyID           *sql.Null[string] `db:"client_key_id" `
	Protocol              *string           `db:"protocol" `
	LogicalModel          *string           `db:"logical_model" `
	State                 *string           `db:"state" `
	ReceivedAt            *string           `db:"received_at" `
	CompletedAt           *sql.Null[string] `db:"completed_at" `
	SelectedProvider      *sql.Null[string] `db:"selected_provider" `
	SelectedUpstreamModel *sql.Null[string] `db:"selected_upstream_model" `
	AttemptCount          *int64            `db:"attempt_count" `
	DurationMS            *sql.Null[int64]  `db:"duration_ms" `
	ErrorCode             *sql.Null[string] `db:"error_code" `
	ErrorMessage          *sql.Null[string] `db:"error_message" `
	StatsDisposition      *string           `db:"stats_disposition" `
	ResolvedGroupID       *sql.Null[string] `db:"resolved_group_id" `
	ResolvedGroupRevision *sql.Null[int64]  `db:"resolved_group_revision" `
	ResolvedPlanJSON      *sql.Null[string] `db:"resolved_plan_json" `
	SelectedLogicalModel  *sql.Null[string] `db:"selected_logical_model" `
}

func (s ProxyRequestSetter) SetColumns() []string {
	vals := make([]string, 0, 18)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.ClientKeyID != nil {
		vals = append(vals, "client_key_id")
	}
	if s.Protocol != nil {
		vals = append(vals, "protocol")
	}
	if s.LogicalModel != nil {
		vals = append(vals, "logical_model")
	}
	if s.State != nil {
		vals = append(vals, "state")
	}
	if s.ReceivedAt != nil {
		vals = append(vals, "received_at")
	}
	if s.CompletedAt != nil {
		vals = append(vals, "completed_at")
	}
	if s.SelectedProvider != nil {
		vals = append(vals, "selected_provider")
	}
	if s.SelectedUpstreamModel != nil {
		vals = append(vals, "selected_upstream_model")
	}
	if s.AttemptCount != nil {
		vals = append(vals, "attempt_count")
	}
	if s.DurationMS != nil {
		vals = append(vals, "duration_ms")
	}
	if s.ErrorCode != nil {
		vals = append(vals, "error_code")
	}
	if s.ErrorMessage != nil {
		vals = append(vals, "error_message")
	}
	if s.StatsDisposition != nil {
		vals = append(vals, "stats_disposition")
	}
	if s.ResolvedGroupID != nil {
		vals = append(vals, "resolved_group_id")
	}
	if s.ResolvedGroupRevision != nil {
		vals = append(vals, "resolved_group_revision")
	}
	if s.ResolvedPlanJSON != nil {
		vals = append(vals, "resolved_plan_json")
	}
	if s.SelectedLogicalModel != nil {
		vals = append(vals, "selected_logical_model")
	}
	return vals
}

func (s ProxyRequestSetter) Overwrite(t *ProxyRequest) {
	if s.ID != nil {
		t.ID = func() string {
			if s.ID == nil {
				return *new(string)
			}
			return *s.ID
		}()
	}
	if s.ClientKeyID != nil {
		t.ClientKeyID = func() sql.Null[string] {
			if s.ClientKeyID == nil {
				return *new(sql.Null[string])
			}
			v := s.ClientKeyID
			return *v
		}()
	}
	if s.Protocol != nil {
		t.Protocol = func() string {
			if s.Protocol == nil {
				return *new(string)
			}
			return *s.Protocol
		}()
	}
	if s.LogicalModel != nil {
		t.LogicalModel = func() string {
			if s.LogicalModel == nil {
				return *new(string)
			}
			return *s.LogicalModel
		}()
	}
	if s.State != nil {
		t.State = func() string {
			if s.State == nil {
				return *new(string)
			}
			return *s.State
		}()
	}
	if s.ReceivedAt != nil {
		t.ReceivedAt = func() string {
			if s.ReceivedAt == nil {
				return *new(string)
			}
			return *s.ReceivedAt
		}()
	}
	if s.CompletedAt != nil {
		t.CompletedAt = func() sql.Null[string] {
			if s.CompletedAt == nil {
				return *new(sql.Null[string])
			}
			v := s.CompletedAt
			return *v
		}()
	}
	if s.SelectedProvider != nil {
		t.SelectedProvider = func() sql.Null[string] {
			if s.SelectedProvider == nil {
				return *new(sql.Null[string])
			}
			v := s.SelectedProvider
			return *v
		}()
	}
	if s.SelectedUpstreamModel != nil {
		t.SelectedUpstreamModel = func() sql.Null[string] {
			if s.SelectedUpstreamModel == nil {
				return *new(sql.Null[string])
			}
			v := s.SelectedUpstreamModel
			return *v
		}()
	}
	if s.AttemptCount != nil {
		t.AttemptCount = func() int64 {
			if s.AttemptCount == nil {
				return *new(int64)
			}
			return *s.AttemptCount
		}()
	}
	if s.DurationMS != nil {
		t.DurationMS = func() sql.Null[int64] {
			if s.DurationMS == nil {
				return *new(sql.Null[int64])
			}
			v := s.DurationMS
			return *v
		}()
	}
	if s.ErrorCode != nil {
		t.ErrorCode = func() sql.Null[string] {
			if s.ErrorCode == nil {
				return *new(sql.Null[string])
			}
			v := s.ErrorCode
			return *v
		}()
	}
	if s.ErrorMessage != nil {
		t.ErrorMessage = func() sql.Null[string] {
			if s.ErrorMessage == nil {
				return *new(sql.Null[string])
			}
			v := s.ErrorMessage
			return *v
		}()
	}
	if s.StatsDisposition != nil {
		t.StatsDisposition = func() string {
			if s.StatsDisposition == nil {
				return *new(string)
			}
			return *s.StatsDisposition
		}()
	}
	if s.ResolvedGroupID != nil {
		t.ResolvedGroupID = func() sql.Null[string] {
			if s.ResolvedGroupID == nil {
				return *new(sql.Null[string])
			}
			v := s.ResolvedGroupID
			return *v
		}()
	}
	if s.ResolvedGroupRevision != nil {
		t.ResolvedGroupRevision = func() sql.Null[int64] {
			if s.ResolvedGroupRevision == nil {
				return *new(sql.Null[int64])
			}
			v := s.ResolvedGroupRevision
			return *v
		}()
	}
	if s.ResolvedPlanJSON != nil {
		t.ResolvedPlanJSON = func() sql.Null[string] {
			if s.ResolvedPlanJSON == nil {
				return *new(sql.Null[string])
			}
			v := s.ResolvedPlanJSON
			return *v
		}()
	}
	if s.SelectedLogicalModel != nil {
		t.SelectedLogicalModel = func() sql.Null[string] {
			if s.SelectedLogicalModel == nil {
				return *new(sql.Null[string])
			}
			v := s.SelectedLogicalModel
			return *v
		}()
	}
}

func (s *ProxyRequestSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ProxyRequests.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.ID == nil {
						return *new(string)
					}
					return *s.ID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "client_key_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ClientKeyID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.ClientKeyID == nil {
						return *new(sql.Null[string])
					}
					v := s.ClientKeyID
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "protocol":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Protocol == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.Protocol == nil {
						return *new(string)
					}
					return *s.Protocol
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "logical_model":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LogicalModel == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.LogicalModel == nil {
						return *new(string)
					}
					return *s.LogicalModel
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "state":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.State == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.State == nil {
						return *new(string)
					}
					return *s.State
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "received_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ReceivedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.ReceivedAt == nil {
						return *new(string)
					}
					return *s.ReceivedAt
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "completed_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.CompletedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.CompletedAt == nil {
						return *new(sql.Null[string])
					}
					v := s.CompletedAt
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "selected_provider":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.SelectedProvider == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.SelectedProvider == nil {
						return *new(sql.Null[string])
					}
					v := s.SelectedProvider
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "selected_upstream_model":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.SelectedUpstreamModel == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.SelectedUpstreamModel == nil {
						return *new(sql.Null[string])
					}
					v := s.SelectedUpstreamModel
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "attempt_count":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.AttemptCount == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.AttemptCount == nil {
						return *new(int64)
					}
					return *s.AttemptCount
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "duration_ms":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.DurationMS == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[int64] {
					if s.DurationMS == nil {
						return *new(sql.Null[int64])
					}
					v := s.DurationMS
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "error_code":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ErrorCode == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.ErrorCode == nil {
						return *new(sql.Null[string])
					}
					v := s.ErrorCode
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "error_message":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ErrorMessage == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.ErrorMessage == nil {
						return *new(sql.Null[string])
					}
					v := s.ErrorMessage
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "stats_disposition":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.StatsDisposition == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.StatsDisposition == nil {
						return *new(string)
					}
					return *s.StatsDisposition
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "resolved_group_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ResolvedGroupID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.ResolvedGroupID == nil {
						return *new(sql.Null[string])
					}
					v := s.ResolvedGroupID
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "resolved_group_revision":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ResolvedGroupRevision == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[int64] {
					if s.ResolvedGroupRevision == nil {
						return *new(sql.Null[int64])
					}
					v := s.ResolvedGroupRevision
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "resolved_plan_json":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ResolvedPlanJSON == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.ResolvedPlanJSON == nil {
						return *new(sql.Null[string])
					}
					v := s.ResolvedPlanJSON
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "selected_logical_model":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.SelectedLogicalModel == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.SelectedLogicalModel == nil {
						return *new(sql.Null[string])
					}
					v := s.SelectedLogicalModel
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s ProxyRequestSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ProxyRequestSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 18)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.ClientKeyID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "client_key_id")...),
			sqlite.Arg(s.ClientKeyID),
		}})
	}

	if s.Protocol != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "protocol")...),
			sqlite.Arg(s.Protocol),
		}})
	}

	if s.LogicalModel != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "logical_model")...),
			sqlite.Arg(s.LogicalModel),
		}})
	}

	if s.State != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "state")...),
			sqlite.Arg(s.State),
		}})
	}

	if s.ReceivedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "received_at")...),
			sqlite.Arg(s.ReceivedAt),
		}})
	}

	if s.CompletedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "completed_at")...),
			sqlite.Arg(s.CompletedAt),
		}})
	}

	if s.SelectedProvider != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "selected_provider")...),
			sqlite.Arg(s.SelectedProvider),
		}})
	}

	if s.SelectedUpstreamModel != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "selected_upstream_model")...),
			sqlite.Arg(s.SelectedUpstreamModel),
		}})
	}

	if s.AttemptCount != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "attempt_count")...),
			sqlite.Arg(s.AttemptCount),
		}})
	}

	if s.DurationMS != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "duration_ms")...),
			sqlite.Arg(s.DurationMS),
		}})
	}

	if s.ErrorCode != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "error_code")...),
			sqlite.Arg(s.ErrorCode),
		}})
	}

	if s.ErrorMessage != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "error_message")...),
			sqlite.Arg(s.ErrorMessage),
		}})
	}

	if s.StatsDisposition != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "stats_disposition")...),
			sqlite.Arg(s.StatsDisposition),
		}})
	}

	if s.ResolvedGroupID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "resolved_group_id")...),
			sqlite.Arg(s.ResolvedGroupID),
		}})
	}

	if s.ResolvedGroupRevision != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "resolved_group_revision")...),
			sqlite.Arg(s.ResolvedGroupRevision),
		}})
	}

	if s.ResolvedPlanJSON != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "resolved_plan_json")...),
			sqlite.Arg(s.ResolvedPlanJSON),
		}})
	}

	if s.SelectedLogicalModel != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "selected_logical_model")...),
			sqlite.Arg(s.SelectedLogicalModel),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func proxyRequestScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*ProxyRequest, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *ProxyRequest) any
	}
	targets := make([]target, 0, 18)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.ID }})
		case "client_key_id":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.ClientKeyID }})
		case "protocol":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.Protocol }})
		case "logical_model":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.LogicalModel }})
		case "state":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.State }})
		case "received_at":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.ReceivedAt }})
		case "completed_at":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.CompletedAt }})
		case "selected_provider":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.SelectedProvider }})
		case "selected_upstream_model":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.SelectedUpstreamModel }})
		case "attempt_count":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.AttemptCount }})
		case "duration_ms":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.DurationMS }})
		case "error_code":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.ErrorCode }})
		case "error_message":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.ErrorMessage }})
		case "stats_disposition":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.StatsDisposition }})
		case "resolved_group_id":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.ResolvedGroupID }})
		case "resolved_group_revision":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.ResolvedGroupRevision }})
		case "resolved_plan_json":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.ResolvedPlanJSON }})
		case "selected_logical_model":
			targets = append(targets, target{i, func(o *ProxyRequest) any { return &o.SelectedLogicalModel }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(ProxyRequest)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*ProxyRequest, error) {
			return v.(*ProxyRequest), nil
		}
}

// FindProxyRequest retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindProxyRequest(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*ProxyRequest, error) {
	if len(cols) == 0 {
		return ProxyRequests.Query(
			sm.Where(ProxyRequests.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ProxyRequests.Query(
		sm.Where(ProxyRequests.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(ProxyRequests.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ProxyRequestExists checks the presence of a single record by primary key
func ProxyRequestExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return ProxyRequests.Query(
		sm.Where(ProxyRequests.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ProxyRequest is retrieved from the database
func (o *ProxyRequest) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ProxyRequests.AfterSelectHooks.RunHooks(ctx, exec, ProxyRequestSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ProxyRequests.AfterInsertHooks.RunHooks(ctx, exec, ProxyRequestSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ProxyRequests.AfterUpdateHooks.RunHooks(ctx, exec, ProxyRequestSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ProxyRequests.AfterDeleteHooks.RunHooks(ctx, exec, ProxyRequestSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the ProxyRequest
func (o *ProxyRequest) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *ProxyRequest) pkEQ() dialect.Expression {
	return sqlite.Quote("proxy_requests", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ProxyRequest
func (o *ProxyRequest) Update(ctx context.Context, exec bob.Executor, s *ProxyRequestSetter) error {
	v, err := ProxyRequests.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single ProxyRequest record with an executor
func (o *ProxyRequest) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ProxyRequests.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ProxyRequest using the executor
func (o *ProxyRequest) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ProxyRequests.Query(
		sm.Where(ProxyRequests.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ProxyRequestSlice is retrieved from the database
func (o ProxyRequestSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ProxyRequests.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ProxyRequests.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ProxyRequests.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ProxyRequests.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o ProxyRequestSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("proxy_requests", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ProxyRequestSlice) copyMatchingRows(from ...*ProxyRequest) {
	fromByPK := make(map[string]*ProxyRequest, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}
		new.R = old.R
		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ProxyRequestSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ProxyRequests.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ProxyRequest:
				o.copyMatchingRows(retrieved)
			case []*ProxyRequest:
				o.copyMatchingRows(retrieved...)
			case ProxyRequestSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ProxyRequest or a slice of ProxyRequest
				// then run the AfterUpdateHooks on the slice
				_, err = ProxyRequests.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ProxyRequestSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ProxyRequests.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ProxyRequest:
				o.copyMatchingRows(retrieved)
			case []*ProxyRequest:
				o.copyMatchingRows(retrieved...)
			case ProxyRequestSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ProxyRequest or a slice of ProxyRequest
				// then run the AfterDeleteHooks on the slice
				_, err = ProxyRequests.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ProxyRequestSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ProxyRequestSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ProxyRequests.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ProxyRequestSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ProxyRequests.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ProxyRequestSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ProxyRequests.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// RequestProxyAttempts starts a query for related objects on proxy_attempts
func (o *ProxyRequest) RequestProxyAttempts(mods ...bob.Mod[*dialect.SelectQuery]) ProxyAttemptsQuery {
	return ProxyAttempts.Query(append(mods,
		sm.Where(ProxyAttempts.Columns.RequestID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os ProxyRequestSlice) RequestProxyAttempts(mods ...bob.Mod[*dialect.SelectQuery]) ProxyAttemptsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return ProxyAttempts.Query(append(mods,
		sm.Where(sqlite.Group(ProxyAttempts.Columns.RequestID).OP("IN", PKArgExpr)),
	)...)
}

// RequestRequestUsage starts a query for related objects on request_usage
func (o *ProxyRequest) RequestRequestUsage(mods ...bob.Mod[*dialect.SelectQuery]) RequestUsagesQuery {
	return RequestUsages.Query(append(mods,
		sm.Where(RequestUsages.Columns.RequestID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os ProxyRequestSlice) RequestRequestUsage(mods ...bob.Mod[*dialect.SelectQuery]) RequestUsagesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return RequestUsages.Query(append(mods,
		sm.Where(sqlite.Group(RequestUsages.Columns.RequestID).OP("IN", PKArgExpr)),
	)...)
}

func insertProxyRequestRequestProxyAttempts0(ctx context.Context, exec bob.Executor, proxyAttempts1 []*ProxyAttemptSetter, proxyRequest0 *ProxyRequest) (ProxyAttemptSlice, error) {
	for i := range proxyAttempts1 {
		proxyAttempts1[i].RequestID = func() *string { return &proxyRequest0.ID }()
	}

	ret, err := ProxyAttempts.Insert(bob.ToMods(proxyAttempts1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertProxyRequestRequestProxyAttempts0: %w", err)
	}

	return ret, nil
}

func attachProxyRequestRequestProxyAttempts0(ctx context.Context, exec bob.Executor, count int, proxyAttempts1 ProxyAttemptSlice, proxyRequest0 *ProxyRequest) (ProxyAttemptSlice, error) {
	setter := &ProxyAttemptSetter{
		RequestID: func() *string { return &proxyRequest0.ID }(),
	}

	err := proxyAttempts1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachProxyRequestRequestProxyAttempts0: %w", err)
	}

	return proxyAttempts1, nil
}

func (proxyRequest0 *ProxyRequest) InsertRequestProxyAttempts(ctx context.Context, exec bob.Executor, related ...*ProxyAttemptSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	proxyAttempts1, err := insertProxyRequestRequestProxyAttempts0(ctx, exec, related, proxyRequest0)
	if err != nil {
		return err
	}

	proxyRequest0.R.RequestProxyAttempts = append(proxyRequest0.R.RequestProxyAttempts, proxyAttempts1...)

	return nil
}

func (proxyRequest0 *ProxyRequest) AttachRequestProxyAttempts(ctx context.Context, exec bob.Executor, related ...*ProxyAttempt) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	proxyAttempts1 := ProxyAttemptSlice(related)

	_, err = attachProxyRequestRequestProxyAttempts0(ctx, exec, len(related), proxyAttempts1, proxyRequest0)
	if err != nil {
		return err
	}

	proxyRequest0.R.RequestProxyAttempts = append(proxyRequest0.R.RequestProxyAttempts, proxyAttempts1...)

	return nil
}

func insertProxyRequestRequestRequestUsage0(ctx context.Context, exec bob.Executor, requestUsage1 *RequestUsageSetter, proxyRequest0 *ProxyRequest) (*RequestUsage, error) {
	requestUsage1.RequestID = func() *string { return &proxyRequest0.ID }()

	ret, err := RequestUsages.Insert(requestUsage1).One(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertProxyRequestRequestRequestUsage0: %w", err)
	}

	return ret, nil
}

func attachProxyRequestRequestRequestUsage0(ctx context.Context, exec bob.Executor, count int, requestUsage1 *RequestUsage, proxyRequest0 *ProxyRequest) (*RequestUsage, error) {
	setter := &RequestUsageSetter{
		RequestID: func() *string { return &proxyRequest0.ID }(),
	}

	err := requestUsage1.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachProxyRequestRequestRequestUsage0: %w", err)
	}

	return requestUsage1, nil
}

func (proxyRequest0 *ProxyRequest) InsertRequestRequestUsage(ctx context.Context, exec bob.Executor, related *RequestUsageSetter) error {
	var err error

	requestUsage1, err := insertProxyRequestRequestRequestUsage0(ctx, exec, related, proxyRequest0)
	if err != nil {
		return err
	}

	proxyRequest0.R.RequestRequestUsage = requestUsage1
	proxyRequest0.R.Loaded.RequestRequestUsage = true

	return nil
}

func (proxyRequest0 *ProxyRequest) AttachRequestRequestUsage(ctx context.Context, exec bob.Executor, requestUsage1 *RequestUsage) error {
	var err error

	_, err = attachProxyRequestRequestRequestUsage0(ctx, exec, 1, requestUsage1, proxyRequest0)
	if err != nil {
		return err
	}

	proxyRequest0.R.RequestRequestUsage = requestUsage1
	proxyRequest0.R.Loaded.RequestRequestUsage = true

	return nil
}
