// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"io"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// ProxyAttempt is an object representing the database table.
type ProxyAttempt struct {
	ID               string           `db:"id,pk" `
	RequestID        string           `db:"request_id" `
	AttemptNumber    int64            `db:"attempt_number" `
	RouteID          sql.Null[string] `db:"route_id" `
	Provider         sql.Null[string] `db:"provider" `
	UpstreamModel    sql.Null[string] `db:"upstream_model" `
	State            string           `db:"state" `
	StartedAt        string           `db:"started_at" `
	CompletedAt      sql.Null[string] `db:"completed_at" `
	HTTPStatus       sql.Null[int64]  `db:"http_status" `
	ErrorClass       sql.Null[string] `db:"error_class" `
	ErrorMessage     sql.Null[string] `db:"error_message" `
	ErrorRaw         sql.Null[string] `db:"error_raw" `
	DurationMS       sql.Null[int64]  `db:"duration_ms" `
	DeliveryState    string           `db:"delivery_state" `
	StatsDisposition string           `db:"stats_disposition" `

	R proxyAttemptR `db:"-" `
}

// ProxyAttemptSlice is an alias for a slice of pointers to ProxyAttempt.
// This should almost always be used instead of []*ProxyAttempt.
type ProxyAttemptSlice []*ProxyAttempt

// ProxyAttempts contains methods to work with the proxy_attempts table
var ProxyAttempts = sqlite.NewTablex[*ProxyAttempt, ProxyAttemptSlice, *ProxyAttemptSetter]("", "proxy_attempts", buildProxyAttemptColumns("proxy_attempts"), proxyAttemptScanMapper)

// ProxyAttemptsQuery is a query on the proxy_attempts table
type ProxyAttemptsQuery = *sqlite.ViewQuery[*ProxyAttempt, ProxyAttemptSlice]

// proxyAttemptR is where relationships are stored.
type proxyAttemptR struct {
	RequestProxyRequest *ProxyRequest // fk_proxy_attempts_0
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded proxyAttemptRLoaded `db:"-" `
}

// proxyAttemptRLoaded tracks which relationships on ProxyAttempt have been loaded.
type proxyAttemptRLoaded struct {
	RequestProxyRequest bool // fk_proxy_attempts_0
}

func buildProxyAttemptColumns(tableName string) proxyAttemptColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "request_id", "attempt_number", "route_id", "provider", "upstream_model", "state", "started_at", "completed_at", "http_status", "error_class", "error_message", "error_raw", "duration_ms", "delivery_state", "stats_disposition",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return proxyAttemptColumns{
		ColumnsExpr:      columnsExpr,
		tableAlias:       tableName,
		ID:               buildProxyAttemptColumn(tableName, "id"),
		RequestID:        buildProxyAttemptColumn(tableName, "request_id"),
		AttemptNumber:    buildProxyAttemptColumn(tableName, "attempt_number"),
		RouteID:          buildProxyAttemptColumn(tableName, "route_id"),
		Provider:         buildProxyAttemptColumn(tableName, "provider"),
		UpstreamModel:    buildProxyAttemptColumn(tableName, "upstream_model"),
		State:            buildProxyAttemptColumn(tableName, "state"),
		StartedAt:        buildProxyAttemptColumn(tableName, "started_at"),
		CompletedAt:      buildProxyAttemptColumn(tableName, "completed_at"),
		HTTPStatus:       buildProxyAttemptColumn(tableName, "http_status"),
		ErrorClass:       buildProxyAttemptColumn(tableName, "error_class"),
		ErrorMessage:     buildProxyAttemptColumn(tableName, "error_message"),
		ErrorRaw:         buildProxyAttemptColumn(tableName, "error_raw"),
		DurationMS:       buildProxyAttemptColumn(tableName, "duration_ms"),
		DeliveryState:    buildProxyAttemptColumn(tableName, "delivery_state"),
		StatsDisposition: buildProxyAttemptColumn(tableName, "stats_disposition"),
	}
}

type proxyAttemptColumns struct {
	expr.ColumnsExpr
	tableAlias       string
	ID               proxyAttemptColumn
	RequestID        proxyAttemptColumn
	AttemptNumber    proxyAttemptColumn
	RouteID          proxyAttemptColumn
	Provider         proxyAttemptColumn
	UpstreamModel    proxyAttemptColumn
	State            proxyAttemptColumn
	StartedAt        proxyAttemptColumn
	CompletedAt      proxyAttemptColumn
	HTTPStatus       proxyAttemptColumn
	ErrorClass       proxyAttemptColumn
	ErrorMessage     proxyAttemptColumn
	ErrorRaw         proxyAttemptColumn
	DurationMS       proxyAttemptColumn
	DeliveryState    proxyAttemptColumn
	StatsDisposition proxyAttemptColumn
}

// Alias returns the current table alias for the columns set.
func (c proxyAttemptColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (proxyAttemptColumns) AliasedAs(tableName string) proxyAttemptColumns {
	return buildProxyAttemptColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c proxyAttemptColumns) Unqualified() proxyAttemptColumns {
	return buildProxyAttemptColumns("")
}

func buildProxyAttemptColumn(alias, name string) proxyAttemptColumn {
	return proxyAttemptColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type proxyAttemptColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c proxyAttemptColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c proxyAttemptColumn) ShouldOmitParens() bool {
	return true
}

// ProxyAttemptSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ProxyAttemptSetter struct {
	ID               *string           `db:"id,pk" `
	RequestID        *string           `db:"request_id" `
	AttemptNumber    *int64            `db:"attempt_number" `
	RouteID          *sql.Null[string] `db:"route_id" `
	Provider         *sql.Null[string] `db:"provider" `
	UpstreamModel    *sql.Null[string] `db:"upstream_model" `
	State            *string           `db:"state" `
	StartedAt        *string           `db:"started_at" `
	CompletedAt      *sql.Null[string] `db:"completed_at" `
	HTTPStatus       *sql.Null[int64]  `db:"http_status" `
	ErrorClass       *sql.Null[string] `db:"error_class" `
	ErrorMessage     *sql.Null[string] `db:"error_message" `
	ErrorRaw         *sql.Null[string] `db:"error_raw" `
	DurationMS       *sql.Null[int64]  `db:"duration_ms" `
	DeliveryState    *string           `db:"delivery_state" `
	StatsDisposition *string           `db:"stats_disposition" `
}

func (s ProxyAttemptSetter) SetColumns() []string {
	vals := make([]string, 0, 16)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.RequestID != nil {
		vals = append(vals, "request_id")
	}
	if s.AttemptNumber != nil {
		vals = append(vals, "attempt_number")
	}
	if s.RouteID != nil {
		vals = append(vals, "route_id")
	}
	if s.Provider != nil {
		vals = append(vals, "provider")
	}
	if s.UpstreamModel != nil {
		vals = append(vals, "upstream_model")
	}
	if s.State != nil {
		vals = append(vals, "state")
	}
	if s.StartedAt != nil {
		vals = append(vals, "started_at")
	}
	if s.CompletedAt != nil {
		vals = append(vals, "completed_at")
	}
	if s.HTTPStatus != nil {
		vals = append(vals, "http_status")
	}
	if s.ErrorClass != nil {
		vals = append(vals, "error_class")
	}
	if s.ErrorMessage != nil {
		vals = append(vals, "error_message")
	}
	if s.ErrorRaw != nil {
		vals = append(vals, "error_raw")
	}
	if s.DurationMS != nil {
		vals = append(vals, "duration_ms")
	}
	if s.DeliveryState != nil {
		vals = append(vals, "delivery_state")
	}
	if s.StatsDisposition != nil {
		vals = append(vals, "stats_disposition")
	}
	return vals
}

func (s ProxyAttemptSetter) Overwrite(t *ProxyAttempt) {
	if s.ID != nil {
		t.ID = func() string {
			if s.ID == nil {
				return *new(string)
			}
			return *s.ID
		}()
	}
	if s.RequestID != nil {
		t.RequestID = func() string {
			if s.RequestID == nil {
				return *new(string)
			}
			return *s.RequestID
		}()
	}
	if s.AttemptNumber != nil {
		t.AttemptNumber = func() int64 {
			if s.AttemptNumber == nil {
				return *new(int64)
			}
			return *s.AttemptNumber
		}()
	}
	if s.RouteID != nil {
		t.RouteID = func() sql.Null[string] {
			if s.RouteID == nil {
				return *new(sql.Null[string])
			}
			v := s.RouteID
			return *v
		}()
	}
	if s.Provider != nil {
		t.Provider = func() sql.Null[string] {
			if s.Provider == nil {
				return *new(sql.Null[string])
			}
			v := s.Provider
			return *v
		}()
	}
	if s.UpstreamModel != nil {
		t.UpstreamModel = func() sql.Null[string] {
			if s.UpstreamModel == nil {
				return *new(sql.Null[string])
			}
			v := s.UpstreamModel
			return *v
		}()
	}
	if s.State != nil {
		t.State = func() string {
			if s.State == nil {
				return *new(string)
			}
			return *s.State
		}()
	}
	if s.StartedAt != nil {
		t.StartedAt = func() string {
			if s.StartedAt == nil {
				return *new(string)
			}
			return *s.StartedAt
		}()
	}
	if s.CompletedAt != nil {
		t.CompletedAt = func() sql.Null[string] {
			if s.CompletedAt == nil {
				return *new(sql.Null[string])
			}
			v := s.CompletedAt
			return *v
		}()
	}
	if s.HTTPStatus != nil {
		t.HTTPStatus = func() sql.Null[int64] {
			if s.HTTPStatus == nil {
				return *new(sql.Null[int64])
			}
			v := s.HTTPStatus
			return *v
		}()
	}
	if s.ErrorClass != nil {
		t.ErrorClass = func() sql.Null[string] {
			if s.ErrorClass == nil {
				return *new(sql.Null[string])
			}
			v := s.ErrorClass
			return *v
		}()
	}
	if s.ErrorMessage != nil {
		t.ErrorMessage = func() sql.Null[string] {
			if s.ErrorMessage == nil {
				return *new(sql.Null[string])
			}
			v := s.ErrorMessage
			return *v
		}()
	}
	if s.ErrorRaw != nil {
		t.ErrorRaw = func() sql.Null[string] {
			if s.ErrorRaw == nil {
				return *new(sql.Null[string])
			}
			v := s.ErrorRaw
			return *v
		}()
	}
	if s.DurationMS != nil {
		t.DurationMS = func() sql.Null[int64] {
			if s.DurationMS == nil {
				return *new(sql.Null[int64])
			}
			v := s.DurationMS
			return *v
		}()
	}
	if s.DeliveryState != nil {
		t.DeliveryState = func() string {
			if s.DeliveryState == nil {
				return *new(string)
			}
			return *s.DeliveryState
		}()
	}
	if s.StatsDisposition != nil {
		t.StatsDisposition = func() string {
			if s.StatsDisposition == nil {
				return *new(string)
			}
			return *s.StatsDisposition
		}()
	}
}

func (s *ProxyAttemptSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ProxyAttempts.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.ID == nil {
						return *new(string)
					}
					return *s.ID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "request_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.RequestID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.RequestID == nil {
						return *new(string)
					}
					return *s.RequestID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "attempt_number":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.AttemptNumber == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.AttemptNumber == nil {
						return *new(int64)
					}
					return *s.AttemptNumber
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "route_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.RouteID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.RouteID == nil {
						return *new(sql.Null[string])
					}
					v := s.RouteID
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "provider":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Provider == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.Provider == nil {
						return *new(sql.Null[string])
					}
					v := s.Provider
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "upstream_model":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.UpstreamModel == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.UpstreamModel == nil {
						return *new(sql.Null[string])
					}
					v := s.UpstreamModel
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "state":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.State == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.State == nil {
						return *new(string)
					}
					return *s.State
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "started_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.StartedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.StartedAt == nil {
						return *new(string)
					}
					return *s.StartedAt
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "completed_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.CompletedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.CompletedAt == nil {
						return *new(sql.Null[string])
					}
					v := s.CompletedAt
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "http_status":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.HTTPStatus == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[int64] {
					if s.HTTPStatus == nil {
						return *new(sql.Null[int64])
					}
					v := s.HTTPStatus
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "error_class":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ErrorClass == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.ErrorClass == nil {
						return *new(sql.Null[string])
					}
					v := s.ErrorClass
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "error_message":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ErrorMessage == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.ErrorMessage == nil {
						return *new(sql.Null[string])
					}
					v := s.ErrorMessage
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "error_raw":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ErrorRaw == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[string] {
					if s.ErrorRaw == nil {
						return *new(sql.Null[string])
					}
					v := s.ErrorRaw
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "duration_ms":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.DurationMS == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[int64] {
					if s.DurationMS == nil {
						return *new(sql.Null[int64])
					}
					v := s.DurationMS
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "delivery_state":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.DeliveryState == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.DeliveryState == nil {
						return *new(string)
					}
					return *s.DeliveryState
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "stats_disposition":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.StatsDisposition == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.StatsDisposition == nil {
						return *new(string)
					}
					return *s.StatsDisposition
				}()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s ProxyAttemptSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ProxyAttemptSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 16)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.RequestID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "request_id")...),
			sqlite.Arg(s.RequestID),
		}})
	}

	if s.AttemptNumber != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "attempt_number")...),
			sqlite.Arg(s.AttemptNumber),
		}})
	}

	if s.RouteID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "route_id")...),
			sqlite.Arg(s.RouteID),
		}})
	}

	if s.Provider != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "provider")...),
			sqlite.Arg(s.Provider),
		}})
	}

	if s.UpstreamModel != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "upstream_model")...),
			sqlite.Arg(s.UpstreamModel),
		}})
	}

	if s.State != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "state")...),
			sqlite.Arg(s.State),
		}})
	}

	if s.StartedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "started_at")...),
			sqlite.Arg(s.StartedAt),
		}})
	}

	if s.CompletedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "completed_at")...),
			sqlite.Arg(s.CompletedAt),
		}})
	}

	if s.HTTPStatus != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "http_status")...),
			sqlite.Arg(s.HTTPStatus),
		}})
	}

	if s.ErrorClass != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "error_class")...),
			sqlite.Arg(s.ErrorClass),
		}})
	}

	if s.ErrorMessage != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "error_message")...),
			sqlite.Arg(s.ErrorMessage),
		}})
	}

	if s.ErrorRaw != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "error_raw")...),
			sqlite.Arg(s.ErrorRaw),
		}})
	}

	if s.DurationMS != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "duration_ms")...),
			sqlite.Arg(s.DurationMS),
		}})
	}

	if s.DeliveryState != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "delivery_state")...),
			sqlite.Arg(s.DeliveryState),
		}})
	}

	if s.StatsDisposition != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "stats_disposition")...),
			sqlite.Arg(s.StatsDisposition),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func proxyAttemptScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*ProxyAttempt, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *ProxyAttempt) any
	}
	targets := make([]target, 0, 16)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *ProxyAttempt) any { return &o.ID }})
		case "request_id":
			targets = append(targets, target{i, func(o *ProxyAttempt) any { return &o.RequestID }})
		case "attempt_number":
			targets = append(targets, target{i, func(o *ProxyAttempt) any { return &o.AttemptNumber }})
		case "route_id":
			targets = append(targets, target{i, func(o *ProxyAttempt) any { return &o.RouteID }})
		case "provider":
			targets = append(targets, target{i, func(o *ProxyAttempt) any { return &o.Provider }})
		case "upstream_model":
			targets = append(targets, target{i, func(o *ProxyAttempt) any { return &o.UpstreamModel }})
		case "state":
			targets = append(targets, target{i, func(o *ProxyAttempt) any { return &o.State }})
		case "started_at":
			targets = append(targets, target{i, func(o *ProxyAttempt) any { return &o.StartedAt }})
		case "completed_at":
			targets = append(targets, target{i, func(o *ProxyAttempt) any { return &o.CompletedAt }})
		case "http_status":
			targets = append(targets, target{i, func(o *ProxyAttempt) any { return &o.HTTPStatus }})
		case "error_class":
			targets = append(targets, target{i, func(o *ProxyAttempt) any { return &o.ErrorClass }})
		case "error_message":
			targets = append(targets, target{i, func(o *ProxyAttempt) any { return &o.ErrorMessage }})
		case "error_raw":
			targets = append(targets, target{i, func(o *ProxyAttempt) any { return &o.ErrorRaw }})
		case "duration_ms":
			targets = append(targets, target{i, func(o *ProxyAttempt) any { return &o.DurationMS }})
		case "delivery_state":
			targets = append(targets, target{i, func(o *ProxyAttempt) any { return &o.DeliveryState }})
		case "stats_disposition":
			targets = append(targets, target{i, func(o *ProxyAttempt) any { return &o.StatsDisposition }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(ProxyAttempt)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*ProxyAttempt, error) {
			return v.(*ProxyAttempt), nil
		}
}

// FindProxyAttempt retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindProxyAttempt(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*ProxyAttempt, error) {
	if len(cols) == 0 {
		return ProxyAttempts.Query(
			sm.Where(ProxyAttempts.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ProxyAttempts.Query(
		sm.Where(ProxyAttempts.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(ProxyAttempts.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ProxyAttemptExists checks the presence of a single record by primary key
func ProxyAttemptExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return ProxyAttempts.Query(
		sm.Where(ProxyAttempts.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ProxyAttempt is retrieved from the database
func (o *ProxyAttempt) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ProxyAttempts.AfterSelectHooks.RunHooks(ctx, exec, ProxyAttemptSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ProxyAttempts.AfterInsertHooks.RunHooks(ctx, exec, ProxyAttemptSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ProxyAttempts.AfterUpdateHooks.RunHooks(ctx, exec, ProxyAttemptSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ProxyAttempts.AfterDeleteHooks.RunHooks(ctx, exec, ProxyAttemptSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the ProxyAttempt
func (o *ProxyAttempt) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *ProxyAttempt) pkEQ() dialect.Expression {
	return sqlite.Quote("proxy_attempts", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ProxyAttempt
func (o *ProxyAttempt) Update(ctx context.Context, exec bob.Executor, s *ProxyAttemptSetter) error {
	v, err := ProxyAttempts.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single ProxyAttempt record with an executor
func (o *ProxyAttempt) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ProxyAttempts.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ProxyAttempt using the executor
func (o *ProxyAttempt) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ProxyAttempts.Query(
		sm.Where(ProxyAttempts.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ProxyAttemptSlice is retrieved from the database
func (o ProxyAttemptSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ProxyAttempts.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ProxyAttempts.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ProxyAttempts.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ProxyAttempts.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o ProxyAttemptSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("proxy_attempts", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ProxyAttemptSlice) copyMatchingRows(from ...*ProxyAttempt) {
	fromByPK := make(map[string]*ProxyAttempt, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}
		new.R = old.R
		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ProxyAttemptSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ProxyAttempts.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ProxyAttempt:
				o.copyMatchingRows(retrieved)
			case []*ProxyAttempt:
				o.copyMatchingRows(retrieved...)
			case ProxyAttemptSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ProxyAttempt or a slice of ProxyAttempt
				// then run the AfterUpdateHooks on the slice
				_, err = ProxyAttempts.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ProxyAttemptSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ProxyAttempts.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ProxyAttempt:
				o.copyMatchingRows(retrieved)
			case []*ProxyAttempt:
				o.copyMatchingRows(retrieved...)
			case ProxyAttemptSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ProxyAttempt or a slice of ProxyAttempt
				// then run the AfterDeleteHooks on the slice
				_, err = ProxyAttempts.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ProxyAttemptSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ProxyAttemptSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ProxyAttempts.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ProxyAttemptSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ProxyAttempts.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ProxyAttemptSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ProxyAttempts.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// RequestProxyRequest starts a query for related objects on proxy_requests
func (o *ProxyAttempt) RequestProxyRequest(mods ...bob.Mod[*dialect.SelectQuery]) ProxyRequestsQuery {
	return ProxyRequests.Query(append(mods,
		sm.Where(ProxyRequests.Columns.ID.EQ(sqlite.Arg(o.RequestID))),
	)...)
}

func (os ProxyAttemptSlice) RequestProxyRequest(mods ...bob.Mod[*dialect.SelectQuery]) ProxyRequestsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.RequestID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return ProxyRequests.Query(append(mods,
		sm.Where(sqlite.Group(ProxyRequests.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachProxyAttemptRequestProxyRequest0(ctx context.Context, exec bob.Executor, count int, proxyAttempt0 *ProxyAttempt, proxyRequest1 *ProxyRequest) (*ProxyAttempt, error) {
	setter := &ProxyAttemptSetter{
		RequestID: func() *string { return &proxyRequest1.ID }(),
	}

	err := proxyAttempt0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachProxyAttemptRequestProxyRequest0: %w", err)
	}

	return proxyAttempt0, nil
}

func (proxyAttempt0 *ProxyAttempt) InsertRequestProxyRequest(ctx context.Context, exec bob.Executor, related *ProxyRequestSetter) error {
	var err error

	proxyRequest1, err := ProxyRequests.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachProxyAttemptRequestProxyRequest0(ctx, exec, 1, proxyAttempt0, proxyRequest1)
	if err != nil {
		return err
	}

	proxyAttempt0.R.RequestProxyRequest = proxyRequest1
	proxyAttempt0.R.Loaded.RequestProxyRequest = true

	return nil
}

func (proxyAttempt0 *ProxyAttempt) AttachRequestProxyRequest(ctx context.Context, exec bob.Executor, proxyRequest1 *ProxyRequest) error {
	var err error

	_, err = attachProxyAttemptRequestProxyRequest0(ctx, exec, 1, proxyAttempt0, proxyRequest1)
	if err != nil {
		return err
	}

	proxyAttempt0.R.RequestProxyRequest = proxyRequest1
	proxyAttempt0.R.Loaded.RequestProxyRequest = true

	return nil
}
