// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"io"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// RequestUsage is an object representing the database table.
type RequestUsage struct {
	RequestID            string          `db:"request_id,pk" `
	InputTokens          int64           `db:"input_tokens" `
	OutputTokens         int64           `db:"output_tokens" `
	TotalTokens          int64           `db:"total_tokens" `
	CachedReadTokens     int64           `db:"cached_read_tokens" `
	CacheWriteTokens     int64           `db:"cache_write_tokens" `
	ReasoningTokens      int64           `db:"reasoning_tokens" `
	EstimatedCostPicoUsd int64           `db:"estimated_cost_pico_usd" `
	OfficialCostPicoUsd  int64           `db:"official_cost_pico_usd" `
	DiscountPicoUsd      sql.Null[int64] `db:"discount_pico_usd" `
	DiscountPercentBPS   sql.Null[int64] `db:"discount_percent_bps" `
	ActualCostPicoUsd    sql.Null[int64] `db:"actual_cost_pico_usd" `
	RawUsageJSON         string          `db:"raw_usage_json" `

	R requestUsageR `db:"-" `
}

// RequestUsageSlice is an alias for a slice of pointers to RequestUsage.
// This should almost always be used instead of []*RequestUsage.
type RequestUsageSlice []*RequestUsage

// RequestUsages contains methods to work with the request_usage table
var RequestUsages = sqlite.NewTablex[*RequestUsage, RequestUsageSlice, *RequestUsageSetter]("", "request_usage", buildRequestUsageColumns("request_usage"), requestUsageScanMapper)

// RequestUsagesQuery is a query on the request_usage table
type RequestUsagesQuery = *sqlite.ViewQuery[*RequestUsage, RequestUsageSlice]

// requestUsageR is where relationships are stored.
type requestUsageR struct {
	RequestProxyRequest *ProxyRequest // fk_request_usage_0
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded requestUsageRLoaded `db:"-" `
}

// requestUsageRLoaded tracks which relationships on RequestUsage have been loaded.
type requestUsageRLoaded struct {
	RequestProxyRequest bool // fk_request_usage_0
}

func buildRequestUsageColumns(tableName string) requestUsageColumns {
	columnsExpr := expr.NewColumnsExpr(
		"request_id", "input_tokens", "output_tokens", "total_tokens", "cached_read_tokens", "cache_write_tokens", "reasoning_tokens", "estimated_cost_pico_usd", "official_cost_pico_usd", "discount_pico_usd", "discount_percent_bps", "actual_cost_pico_usd", "raw_usage_json",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return requestUsageColumns{
		ColumnsExpr:          columnsExpr,
		tableAlias:           tableName,
		RequestID:            buildRequestUsageColumn(tableName, "request_id"),
		InputTokens:          buildRequestUsageColumn(tableName, "input_tokens"),
		OutputTokens:         buildRequestUsageColumn(tableName, "output_tokens"),
		TotalTokens:          buildRequestUsageColumn(tableName, "total_tokens"),
		CachedReadTokens:     buildRequestUsageColumn(tableName, "cached_read_tokens"),
		CacheWriteTokens:     buildRequestUsageColumn(tableName, "cache_write_tokens"),
		ReasoningTokens:      buildRequestUsageColumn(tableName, "reasoning_tokens"),
		EstimatedCostPicoUsd: buildRequestUsageColumn(tableName, "estimated_cost_pico_usd"),
		OfficialCostPicoUsd:  buildRequestUsageColumn(tableName, "official_cost_pico_usd"),
		DiscountPicoUsd:      buildRequestUsageColumn(tableName, "discount_pico_usd"),
		DiscountPercentBPS:   buildRequestUsageColumn(tableName, "discount_percent_bps"),
		ActualCostPicoUsd:    buildRequestUsageColumn(tableName, "actual_cost_pico_usd"),
		RawUsageJSON:         buildRequestUsageColumn(tableName, "raw_usage_json"),
	}
}

type requestUsageColumns struct {
	expr.ColumnsExpr
	tableAlias           string
	RequestID            requestUsageColumn
	InputTokens          requestUsageColumn
	OutputTokens         requestUsageColumn
	TotalTokens          requestUsageColumn
	CachedReadTokens     requestUsageColumn
	CacheWriteTokens     requestUsageColumn
	ReasoningTokens      requestUsageColumn
	EstimatedCostPicoUsd requestUsageColumn
	OfficialCostPicoUsd  requestUsageColumn
	DiscountPicoUsd      requestUsageColumn
	DiscountPercentBPS   requestUsageColumn
	ActualCostPicoUsd    requestUsageColumn
	RawUsageJSON         requestUsageColumn
}

// Alias returns the current table alias for the columns set.
func (c requestUsageColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (requestUsageColumns) AliasedAs(tableName string) requestUsageColumns {
	return buildRequestUsageColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c requestUsageColumns) Unqualified() requestUsageColumns {
	return buildRequestUsageColumns("")
}

func buildRequestUsageColumn(alias, name string) requestUsageColumn {
	return requestUsageColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type requestUsageColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c requestUsageColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c requestUsageColumn) ShouldOmitParens() bool {
	return true
}

// RequestUsageSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type RequestUsageSetter struct {
	RequestID            *string          `db:"request_id,pk" `
	InputTokens          *int64           `db:"input_tokens" `
	OutputTokens         *int64           `db:"output_tokens" `
	TotalTokens          *int64           `db:"total_tokens" `
	CachedReadTokens     *int64           `db:"cached_read_tokens" `
	CacheWriteTokens     *int64           `db:"cache_write_tokens" `
	ReasoningTokens      *int64           `db:"reasoning_tokens" `
	EstimatedCostPicoUsd *int64           `db:"estimated_cost_pico_usd" `
	OfficialCostPicoUsd  *int64           `db:"official_cost_pico_usd" `
	DiscountPicoUsd      *sql.Null[int64] `db:"discount_pico_usd" `
	DiscountPercentBPS   *sql.Null[int64] `db:"discount_percent_bps" `
	ActualCostPicoUsd    *sql.Null[int64] `db:"actual_cost_pico_usd" `
	RawUsageJSON         *string          `db:"raw_usage_json" `
}

func (s RequestUsageSetter) SetColumns() []string {
	vals := make([]string, 0, 13)
	if s.RequestID != nil {
		vals = append(vals, "request_id")
	}
	if s.InputTokens != nil {
		vals = append(vals, "input_tokens")
	}
	if s.OutputTokens != nil {
		vals = append(vals, "output_tokens")
	}
	if s.TotalTokens != nil {
		vals = append(vals, "total_tokens")
	}
	if s.CachedReadTokens != nil {
		vals = append(vals, "cached_read_tokens")
	}
	if s.CacheWriteTokens != nil {
		vals = append(vals, "cache_write_tokens")
	}
	if s.ReasoningTokens != nil {
		vals = append(vals, "reasoning_tokens")
	}
	if s.EstimatedCostPicoUsd != nil {
		vals = append(vals, "estimated_cost_pico_usd")
	}
	if s.OfficialCostPicoUsd != nil {
		vals = append(vals, "official_cost_pico_usd")
	}
	if s.DiscountPicoUsd != nil {
		vals = append(vals, "discount_pico_usd")
	}
	if s.DiscountPercentBPS != nil {
		vals = append(vals, "discount_percent_bps")
	}
	if s.ActualCostPicoUsd != nil {
		vals = append(vals, "actual_cost_pico_usd")
	}
	if s.RawUsageJSON != nil {
		vals = append(vals, "raw_usage_json")
	}
	return vals
}

func (s RequestUsageSetter) Overwrite(t *RequestUsage) {
	if s.RequestID != nil {
		t.RequestID = func() string {
			if s.RequestID == nil {
				return *new(string)
			}
			return *s.RequestID
		}()
	}
	if s.InputTokens != nil {
		t.InputTokens = func() int64 {
			if s.InputTokens == nil {
				return *new(int64)
			}
			return *s.InputTokens
		}()
	}
	if s.OutputTokens != nil {
		t.OutputTokens = func() int64 {
			if s.OutputTokens == nil {
				return *new(int64)
			}
			return *s.OutputTokens
		}()
	}
	if s.TotalTokens != nil {
		t.TotalTokens = func() int64 {
			if s.TotalTokens == nil {
				return *new(int64)
			}
			return *s.TotalTokens
		}()
	}
	if s.CachedReadTokens != nil {
		t.CachedReadTokens = func() int64 {
			if s.CachedReadTokens == nil {
				return *new(int64)
			}
			return *s.CachedReadTokens
		}()
	}
	if s.CacheWriteTokens != nil {
		t.CacheWriteTokens = func() int64 {
			if s.CacheWriteTokens == nil {
				return *new(int64)
			}
			return *s.CacheWriteTokens
		}()
	}
	if s.ReasoningTokens != nil {
		t.ReasoningTokens = func() int64 {
			if s.ReasoningTokens == nil {
				return *new(int64)
			}
			return *s.ReasoningTokens
		}()
	}
	if s.EstimatedCostPicoUsd != nil {
		t.EstimatedCostPicoUsd = func() int64 {
			if s.EstimatedCostPicoUsd == nil {
				return *new(int64)
			}
			return *s.EstimatedCostPicoUsd
		}()
	}
	if s.OfficialCostPicoUsd != nil {
		t.OfficialCostPicoUsd = func() int64 {
			if s.OfficialCostPicoUsd == nil {
				return *new(int64)
			}
			return *s.OfficialCostPicoUsd
		}()
	}
	if s.DiscountPicoUsd != nil {
		t.DiscountPicoUsd = func() sql.Null[int64] {
			if s.DiscountPicoUsd == nil {
				return *new(sql.Null[int64])
			}
			v := s.DiscountPicoUsd
			return *v
		}()
	}
	if s.DiscountPercentBPS != nil {
		t.DiscountPercentBPS = func() sql.Null[int64] {
			if s.DiscountPercentBPS == nil {
				return *new(sql.Null[int64])
			}
			v := s.DiscountPercentBPS
			return *v
		}()
	}
	if s.ActualCostPicoUsd != nil {
		t.ActualCostPicoUsd = func() sql.Null[int64] {
			if s.ActualCostPicoUsd == nil {
				return *new(sql.Null[int64])
			}
			v := s.ActualCostPicoUsd
			return *v
		}()
	}
	if s.RawUsageJSON != nil {
		t.RawUsageJSON = func() string {
			if s.RawUsageJSON == nil {
				return *new(string)
			}
			return *s.RawUsageJSON
		}()
	}
}

func (s *RequestUsageSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return RequestUsages.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"request_id"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "request_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.RequestID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.RequestID == nil {
						return *new(string)
					}
					return *s.RequestID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "input_tokens":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.InputTokens == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.InputTokens == nil {
						return *new(int64)
					}
					return *s.InputTokens
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "output_tokens":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.OutputTokens == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.OutputTokens == nil {
						return *new(int64)
					}
					return *s.OutputTokens
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "total_tokens":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.TotalTokens == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.TotalTokens == nil {
						return *new(int64)
					}
					return *s.TotalTokens
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "cached_read_tokens":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.CachedReadTokens == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.CachedReadTokens == nil {
						return *new(int64)
					}
					return *s.CachedReadTokens
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "cache_write_tokens":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.CacheWriteTokens == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.CacheWriteTokens == nil {
						return *new(int64)
					}
					return *s.CacheWriteTokens
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "reasoning_tokens":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ReasoningTokens == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.ReasoningTokens == nil {
						return *new(int64)
					}
					return *s.ReasoningTokens
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "estimated_cost_pico_usd":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.EstimatedCostPicoUsd == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.EstimatedCostPicoUsd == nil {
						return *new(int64)
					}
					return *s.EstimatedCostPicoUsd
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "official_cost_pico_usd":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.OfficialCostPicoUsd == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.OfficialCostPicoUsd == nil {
						return *new(int64)
					}
					return *s.OfficialCostPicoUsd
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "discount_pico_usd":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.DiscountPicoUsd == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[int64] {
					if s.DiscountPicoUsd == nil {
						return *new(sql.Null[int64])
					}
					v := s.DiscountPicoUsd
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "discount_percent_bps":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.DiscountPercentBPS == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[int64] {
					if s.DiscountPercentBPS == nil {
						return *new(sql.Null[int64])
					}
					v := s.DiscountPercentBPS
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "actual_cost_pico_usd":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ActualCostPicoUsd == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() sql.Null[int64] {
					if s.ActualCostPicoUsd == nil {
						return *new(sql.Null[int64])
					}
					v := s.ActualCostPicoUsd
					return *v
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "raw_usage_json":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.RawUsageJSON == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.RawUsageJSON == nil {
						return *new(string)
					}
					return *s.RawUsageJSON
				}()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s RequestUsageSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s RequestUsageSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 13)

	if s.RequestID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "request_id")...),
			sqlite.Arg(s.RequestID),
		}})
	}

	if s.InputTokens != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "input_tokens")...),
			sqlite.Arg(s.InputTokens),
		}})
	}

	if s.OutputTokens != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "output_tokens")...),
			sqlite.Arg(s.OutputTokens),
		}})
	}

	if s.TotalTokens != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "total_tokens")...),
			sqlite.Arg(s.TotalTokens),
		}})
	}

	if s.CachedReadTokens != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "cached_read_tokens")...),
			sqlite.Arg(s.CachedReadTokens),
		}})
	}

	if s.CacheWriteTokens != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "cache_write_tokens")...),
			sqlite.Arg(s.CacheWriteTokens),
		}})
	}

	if s.ReasoningTokens != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "reasoning_tokens")...),
			sqlite.Arg(s.ReasoningTokens),
		}})
	}

	if s.EstimatedCostPicoUsd != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "estimated_cost_pico_usd")...),
			sqlite.Arg(s.EstimatedCostPicoUsd),
		}})
	}

	if s.OfficialCostPicoUsd != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "official_cost_pico_usd")...),
			sqlite.Arg(s.OfficialCostPicoUsd),
		}})
	}

	if s.DiscountPicoUsd != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "discount_pico_usd")...),
			sqlite.Arg(s.DiscountPicoUsd),
		}})
	}

	if s.DiscountPercentBPS != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "discount_percent_bps")...),
			sqlite.Arg(s.DiscountPercentBPS),
		}})
	}

	if s.ActualCostPicoUsd != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "actual_cost_pico_usd")...),
			sqlite.Arg(s.ActualCostPicoUsd),
		}})
	}

	if s.RawUsageJSON != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "raw_usage_json")...),
			sqlite.Arg(s.RawUsageJSON),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func requestUsageScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*RequestUsage, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *RequestUsage) any
	}
	targets := make([]target, 0, 13)
	for i, col := range cols {
		switch col {
		case "request_id":
			targets = append(targets, target{i, func(o *RequestUsage) any { return &o.RequestID }})
		case "input_tokens":
			targets = append(targets, target{i, func(o *RequestUsage) any { return &o.InputTokens }})
		case "output_tokens":
			targets = append(targets, target{i, func(o *RequestUsage) any { return &o.OutputTokens }})
		case "total_tokens":
			targets = append(targets, target{i, func(o *RequestUsage) any { return &o.TotalTokens }})
		case "cached_read_tokens":
			targets = append(targets, target{i, func(o *RequestUsage) any { return &o.CachedReadTokens }})
		case "cache_write_tokens":
			targets = append(targets, target{i, func(o *RequestUsage) any { return &o.CacheWriteTokens }})
		case "reasoning_tokens":
			targets = append(targets, target{i, func(o *RequestUsage) any { return &o.ReasoningTokens }})
		case "estimated_cost_pico_usd":
			targets = append(targets, target{i, func(o *RequestUsage) any { return &o.EstimatedCostPicoUsd }})
		case "official_cost_pico_usd":
			targets = append(targets, target{i, func(o *RequestUsage) any { return &o.OfficialCostPicoUsd }})
		case "discount_pico_usd":
			targets = append(targets, target{i, func(o *RequestUsage) any { return &o.DiscountPicoUsd }})
		case "discount_percent_bps":
			targets = append(targets, target{i, func(o *RequestUsage) any { return &o.DiscountPercentBPS }})
		case "actual_cost_pico_usd":
			targets = append(targets, target{i, func(o *RequestUsage) any { return &o.ActualCostPicoUsd }})
		case "raw_usage_json":
			targets = append(targets, target{i, func(o *RequestUsage) any { return &o.RawUsageJSON }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(RequestUsage)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*RequestUsage, error) {
			return v.(*RequestUsage), nil
		}
}

// FindRequestUsage retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindRequestUsage(ctx context.Context, exec bob.Executor, RequestIDPK string, cols ...string) (*RequestUsage, error) {
	if len(cols) == 0 {
		return RequestUsages.Query(
			sm.Where(RequestUsages.Columns.RequestID.EQ(sqlite.Arg(RequestIDPK))),
		).One(ctx, exec)
	}

	return RequestUsages.Query(
		sm.Where(RequestUsages.Columns.RequestID.EQ(sqlite.Arg(RequestIDPK))),
		sm.Columns(RequestUsages.Columns.Only(cols...)),
	).One(ctx, exec)
}

// RequestUsageExists checks the presence of a single record by primary key
func RequestUsageExists(ctx context.Context, exec bob.Executor, RequestIDPK string) (bool, error) {
	return RequestUsages.Query(
		sm.Where(RequestUsages.Columns.RequestID.EQ(sqlite.Arg(RequestIDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after RequestUsage is retrieved from the database
func (o *RequestUsage) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RequestUsages.AfterSelectHooks.RunHooks(ctx, exec, RequestUsageSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = RequestUsages.AfterInsertHooks.RunHooks(ctx, exec, RequestUsageSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = RequestUsages.AfterUpdateHooks.RunHooks(ctx, exec, RequestUsageSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = RequestUsages.AfterDeleteHooks.RunHooks(ctx, exec, RequestUsageSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the RequestUsage
func (o *RequestUsage) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.RequestID)
}

func (o *RequestUsage) pkEQ() dialect.Expression {
	return sqlite.Quote("request_usage", "request_id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the RequestUsage
func (o *RequestUsage) Update(ctx context.Context, exec bob.Executor, s *RequestUsageSetter) error {
	v, err := RequestUsages.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single RequestUsage record with an executor
func (o *RequestUsage) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := RequestUsages.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the RequestUsage using the executor
func (o *RequestUsage) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := RequestUsages.Query(
		sm.Where(RequestUsages.Columns.RequestID.EQ(sqlite.Arg(o.RequestID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after RequestUsageSlice is retrieved from the database
func (o RequestUsageSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RequestUsages.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = RequestUsages.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = RequestUsages.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = RequestUsages.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o RequestUsageSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("request_usage", "request_id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o RequestUsageSlice) copyMatchingRows(from ...*RequestUsage) {
	fromByPK := make(map[string]*RequestUsage, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.RequestID]; !ok {
			fromByPK[new.RequestID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.RequestID]
		if !ok {
			continue
		}
		new.R = old.R
		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o RequestUsageSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RequestUsages.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RequestUsage:
				o.copyMatchingRows(retrieved)
			case []*RequestUsage:
				o.copyMatchingRows(retrieved...)
			case RequestUsageSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RequestUsage or a slice of RequestUsage
				// then run the AfterUpdateHooks on the slice
				_, err = RequestUsages.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o RequestUsageSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RequestUsages.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RequestUsage:
				o.copyMatchingRows(retrieved)
			case []*RequestUsage:
				o.copyMatchingRows(retrieved...)
			case RequestUsageSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RequestUsage or a slice of RequestUsage
				// then run the AfterDeleteHooks on the slice
				_, err = RequestUsages.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o RequestUsageSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals RequestUsageSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RequestUsages.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o RequestUsageSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RequestUsages.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o RequestUsageSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := RequestUsages.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// RequestProxyRequest starts a query for related objects on proxy_requests
func (o *RequestUsage) RequestProxyRequest(mods ...bob.Mod[*dialect.SelectQuery]) ProxyRequestsQuery {
	return ProxyRequests.Query(append(mods,
		sm.Where(ProxyRequests.Columns.ID.EQ(sqlite.Arg(o.RequestID))),
	)...)
}

func (os RequestUsageSlice) RequestProxyRequest(mods ...bob.Mod[*dialect.SelectQuery]) ProxyRequestsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.RequestID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return ProxyRequests.Query(append(mods,
		sm.Where(sqlite.Group(ProxyRequests.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachRequestUsageRequestProxyRequest0(ctx context.Context, exec bob.Executor, count int, requestUsage0 *RequestUsage, proxyRequest1 *ProxyRequest) (*RequestUsage, error) {
	setter := &RequestUsageSetter{
		RequestID: func() *string { return &proxyRequest1.ID }(),
	}

	err := requestUsage0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachRequestUsageRequestProxyRequest0: %w", err)
	}

	return requestUsage0, nil
}

func (requestUsage0 *RequestUsage) InsertRequestProxyRequest(ctx context.Context, exec bob.Executor, related *ProxyRequestSetter) error {
	var err error

	proxyRequest1, err := ProxyRequests.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachRequestUsageRequestProxyRequest0(ctx, exec, 1, requestUsage0, proxyRequest1)
	if err != nil {
		return err
	}

	requestUsage0.R.RequestProxyRequest = proxyRequest1
	requestUsage0.R.Loaded.RequestProxyRequest = true

	return nil
}

func (requestUsage0 *RequestUsage) AttachRequestProxyRequest(ctx context.Context, exec bob.Executor, proxyRequest1 *ProxyRequest) error {
	var err error

	_, err = attachRequestUsageRequestProxyRequest0(ctx, exec, 1, requestUsage0, proxyRequest1)
	if err != nil {
		return err
	}

	requestUsage0.R.RequestProxyRequest = proxyRequest1
	requestUsage0.R.Loaded.RequestProxyRequest = true

	return nil
}
