// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"io"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// RoutingGroup is an object representing the database table.
type RoutingGroup struct {
	ID          string `db:"id,pk" `
	Name        string `db:"name" `
	Slug        string `db:"slug" `
	Description string `db:"description" `
	Enabled     int64  `db:"enabled" `
	Revision    int64  `db:"revision" `
	CreatedAt   string `db:"created_at" `
	UpdatedAt   string `db:"updated_at" `

	R routingGroupR `db:"-" `
}

// RoutingGroupSlice is an alias for a slice of pointers to RoutingGroup.
// This should almost always be used instead of []*RoutingGroup.
type RoutingGroupSlice []*RoutingGroup

// RoutingGroups contains methods to work with the routing_groups table
var RoutingGroups = sqlite.NewTablex[*RoutingGroup, RoutingGroupSlice, *RoutingGroupSetter]("", "routing_groups", buildRoutingGroupColumns("routing_groups"), routingGroupScanMapper)

// RoutingGroupsQuery is a query on the routing_groups table
type RoutingGroupsQuery = *sqlite.ViewQuery[*RoutingGroup, RoutingGroupSlice]

// routingGroupR is where relationships are stored.
type routingGroupR struct {
	NestedGroupRoutingGroupSources RoutingGroupSourceSlice // fk_routing_group_sources_0
	GroupRoutingGroupStages        RoutingGroupStageSlice  // fk_routing_group_stages_0
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded routingGroupRLoaded `db:"-" `
}

// routingGroupRLoaded tracks which relationships on RoutingGroup have been loaded.
type routingGroupRLoaded struct {
	NestedGroupRoutingGroupSources bool // fk_routing_group_sources_0
	GroupRoutingGroupStages        bool // fk_routing_group_stages_0
}

func buildRoutingGroupColumns(tableName string) routingGroupColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "name", "slug", "description", "enabled", "revision", "created_at", "updated_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return routingGroupColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildRoutingGroupColumn(tableName, "id"),
		Name:        buildRoutingGroupColumn(tableName, "name"),
		Slug:        buildRoutingGroupColumn(tableName, "slug"),
		Description: buildRoutingGroupColumn(tableName, "description"),
		Enabled:     buildRoutingGroupColumn(tableName, "enabled"),
		Revision:    buildRoutingGroupColumn(tableName, "revision"),
		CreatedAt:   buildRoutingGroupColumn(tableName, "created_at"),
		UpdatedAt:   buildRoutingGroupColumn(tableName, "updated_at"),
	}
}

type routingGroupColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          routingGroupColumn
	Name        routingGroupColumn
	Slug        routingGroupColumn
	Description routingGroupColumn
	Enabled     routingGroupColumn
	Revision    routingGroupColumn
	CreatedAt   routingGroupColumn
	UpdatedAt   routingGroupColumn
}

// Alias returns the current table alias for the columns set.
func (c routingGroupColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (routingGroupColumns) AliasedAs(tableName string) routingGroupColumns {
	return buildRoutingGroupColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c routingGroupColumns) Unqualified() routingGroupColumns {
	return buildRoutingGroupColumns("")
}

func buildRoutingGroupColumn(alias, name string) routingGroupColumn {
	return routingGroupColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type routingGroupColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c routingGroupColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c routingGroupColumn) ShouldOmitParens() bool {
	return true
}

// RoutingGroupSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type RoutingGroupSetter struct {
	ID          *string `db:"id,pk" `
	Name        *string `db:"name" `
	Slug        *string `db:"slug" `
	Description *string `db:"description" `
	Enabled     *int64  `db:"enabled" `
	Revision    *int64  `db:"revision" `
	CreatedAt   *string `db:"created_at" `
	UpdatedAt   *string `db:"updated_at" `
}

func (s RoutingGroupSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.Name != nil {
		vals = append(vals, "name")
	}
	if s.Slug != nil {
		vals = append(vals, "slug")
	}
	if s.Description != nil {
		vals = append(vals, "description")
	}
	if s.Enabled != nil {
		vals = append(vals, "enabled")
	}
	if s.Revision != nil {
		vals = append(vals, "revision")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s RoutingGroupSetter) Overwrite(t *RoutingGroup) {
	if s.ID != nil {
		t.ID = func() string {
			if s.ID == nil {
				return *new(string)
			}
			return *s.ID
		}()
	}
	if s.Name != nil {
		t.Name = func() string {
			if s.Name == nil {
				return *new(string)
			}
			return *s.Name
		}()
	}
	if s.Slug != nil {
		t.Slug = func() string {
			if s.Slug == nil {
				return *new(string)
			}
			return *s.Slug
		}()
	}
	if s.Description != nil {
		t.Description = func() string {
			if s.Description == nil {
				return *new(string)
			}
			return *s.Description
		}()
	}
	if s.Enabled != nil {
		t.Enabled = func() int64 {
			if s.Enabled == nil {
				return *new(int64)
			}
			return *s.Enabled
		}()
	}
	if s.Revision != nil {
		t.Revision = func() int64 {
			if s.Revision == nil {
				return *new(int64)
			}
			return *s.Revision
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() string {
			if s.CreatedAt == nil {
				return *new(string)
			}
			return *s.CreatedAt
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() string {
			if s.UpdatedAt == nil {
				return *new(string)
			}
			return *s.UpdatedAt
		}()
	}
}

func (s *RoutingGroupSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return RoutingGroups.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.ID == nil {
						return *new(string)
					}
					return *s.ID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "name":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Name == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.Name == nil {
						return *new(string)
					}
					return *s.Name
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "slug":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Slug == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.Slug == nil {
						return *new(string)
					}
					return *s.Slug
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "description":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Description == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.Description == nil {
						return *new(string)
					}
					return *s.Description
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "enabled":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Enabled == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.Enabled == nil {
						return *new(int64)
					}
					return *s.Enabled
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "revision":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Revision == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.Revision == nil {
						return *new(int64)
					}
					return *s.Revision
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "created_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.CreatedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.CreatedAt == nil {
						return *new(string)
					}
					return *s.CreatedAt
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "updated_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.UpdatedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.UpdatedAt == nil {
						return *new(string)
					}
					return *s.UpdatedAt
				}()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s RoutingGroupSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s RoutingGroupSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.Name != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "name")...),
			sqlite.Arg(s.Name),
		}})
	}

	if s.Slug != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "slug")...),
			sqlite.Arg(s.Slug),
		}})
	}

	if s.Description != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "description")...),
			sqlite.Arg(s.Description),
		}})
	}

	if s.Enabled != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "enabled")...),
			sqlite.Arg(s.Enabled),
		}})
	}

	if s.Revision != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "revision")...),
			sqlite.Arg(s.Revision),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func routingGroupScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*RoutingGroup, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *RoutingGroup) any
	}
	targets := make([]target, 0, 8)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *RoutingGroup) any { return &o.ID }})
		case "name":
			targets = append(targets, target{i, func(o *RoutingGroup) any { return &o.Name }})
		case "slug":
			targets = append(targets, target{i, func(o *RoutingGroup) any { return &o.Slug }})
		case "description":
			targets = append(targets, target{i, func(o *RoutingGroup) any { return &o.Description }})
		case "enabled":
			targets = append(targets, target{i, func(o *RoutingGroup) any { return &o.Enabled }})
		case "revision":
			targets = append(targets, target{i, func(o *RoutingGroup) any { return &o.Revision }})
		case "created_at":
			targets = append(targets, target{i, func(o *RoutingGroup) any { return &o.CreatedAt }})
		case "updated_at":
			targets = append(targets, target{i, func(o *RoutingGroup) any { return &o.UpdatedAt }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(RoutingGroup)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*RoutingGroup, error) {
			return v.(*RoutingGroup), nil
		}
}

// FindRoutingGroup retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindRoutingGroup(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*RoutingGroup, error) {
	if len(cols) == 0 {
		return RoutingGroups.Query(
			sm.Where(RoutingGroups.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return RoutingGroups.Query(
		sm.Where(RoutingGroups.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(RoutingGroups.Columns.Only(cols...)),
	).One(ctx, exec)
}

// RoutingGroupExists checks the presence of a single record by primary key
func RoutingGroupExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return RoutingGroups.Query(
		sm.Where(RoutingGroups.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after RoutingGroup is retrieved from the database
func (o *RoutingGroup) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RoutingGroups.AfterSelectHooks.RunHooks(ctx, exec, RoutingGroupSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = RoutingGroups.AfterInsertHooks.RunHooks(ctx, exec, RoutingGroupSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = RoutingGroups.AfterUpdateHooks.RunHooks(ctx, exec, RoutingGroupSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = RoutingGroups.AfterDeleteHooks.RunHooks(ctx, exec, RoutingGroupSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the RoutingGroup
func (o *RoutingGroup) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *RoutingGroup) pkEQ() dialect.Expression {
	return sqlite.Quote("routing_groups", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the RoutingGroup
func (o *RoutingGroup) Update(ctx context.Context, exec bob.Executor, s *RoutingGroupSetter) error {
	v, err := RoutingGroups.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single RoutingGroup record with an executor
func (o *RoutingGroup) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := RoutingGroups.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the RoutingGroup using the executor
func (o *RoutingGroup) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := RoutingGroups.Query(
		sm.Where(RoutingGroups.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after RoutingGroupSlice is retrieved from the database
func (o RoutingGroupSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RoutingGroups.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = RoutingGroups.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = RoutingGroups.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = RoutingGroups.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o RoutingGroupSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("routing_groups", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o RoutingGroupSlice) copyMatchingRows(from ...*RoutingGroup) {
	fromByPK := make(map[string]*RoutingGroup, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}
		new.R = old.R
		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o RoutingGroupSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RoutingGroups.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RoutingGroup:
				o.copyMatchingRows(retrieved)
			case []*RoutingGroup:
				o.copyMatchingRows(retrieved...)
			case RoutingGroupSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RoutingGroup or a slice of RoutingGroup
				// then run the AfterUpdateHooks on the slice
				_, err = RoutingGroups.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o RoutingGroupSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RoutingGroups.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RoutingGroup:
				o.copyMatchingRows(retrieved)
			case []*RoutingGroup:
				o.copyMatchingRows(retrieved...)
			case RoutingGroupSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RoutingGroup or a slice of RoutingGroup
				// then run the AfterDeleteHooks on the slice
				_, err = RoutingGroups.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o RoutingGroupSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals RoutingGroupSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RoutingGroups.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o RoutingGroupSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RoutingGroups.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o RoutingGroupSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := RoutingGroups.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// NestedGroupRoutingGroupSources starts a query for related objects on routing_group_sources
func (o *RoutingGroup) NestedGroupRoutingGroupSources(mods ...bob.Mod[*dialect.SelectQuery]) RoutingGroupSourcesQuery {
	return RoutingGroupSources.Query(append(mods,
		sm.Where(RoutingGroupSources.Columns.NestedGroupID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os RoutingGroupSlice) NestedGroupRoutingGroupSources(mods ...bob.Mod[*dialect.SelectQuery]) RoutingGroupSourcesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return RoutingGroupSources.Query(append(mods,
		sm.Where(sqlite.Group(RoutingGroupSources.Columns.NestedGroupID).OP("IN", PKArgExpr)),
	)...)
}

// GroupRoutingGroupStages starts a query for related objects on routing_group_stages
func (o *RoutingGroup) GroupRoutingGroupStages(mods ...bob.Mod[*dialect.SelectQuery]) RoutingGroupStagesQuery {
	return RoutingGroupStages.Query(append(mods,
		sm.Where(RoutingGroupStages.Columns.GroupID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os RoutingGroupSlice) GroupRoutingGroupStages(mods ...bob.Mod[*dialect.SelectQuery]) RoutingGroupStagesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return RoutingGroupStages.Query(append(mods,
		sm.Where(sqlite.Group(RoutingGroupStages.Columns.GroupID).OP("IN", PKArgExpr)),
	)...)
}

func insertRoutingGroupNestedGroupRoutingGroupSources0(ctx context.Context, exec bob.Executor, routingGroupSources1 []*RoutingGroupSourceSetter, routingGroup0 *RoutingGroup) (RoutingGroupSourceSlice, error) {
	for i := range routingGroupSources1 {
		routingGroupSources1[i].NestedGroupID = func() *sql.Null[string] { v := sql.Null[string]{V: routingGroup0.ID, Valid: true}; return &v }()
	}

	ret, err := RoutingGroupSources.Insert(bob.ToMods(routingGroupSources1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertRoutingGroupNestedGroupRoutingGroupSources0: %w", err)
	}

	return ret, nil
}

func attachRoutingGroupNestedGroupRoutingGroupSources0(ctx context.Context, exec bob.Executor, count int, routingGroupSources1 RoutingGroupSourceSlice, routingGroup0 *RoutingGroup) (RoutingGroupSourceSlice, error) {
	setter := &RoutingGroupSourceSetter{
		NestedGroupID: func() *sql.Null[string] { v := sql.Null[string]{V: routingGroup0.ID, Valid: true}; return &v }(),
	}

	err := routingGroupSources1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachRoutingGroupNestedGroupRoutingGroupSources0: %w", err)
	}

	return routingGroupSources1, nil
}

func (routingGroup0 *RoutingGroup) InsertNestedGroupRoutingGroupSources(ctx context.Context, exec bob.Executor, related ...*RoutingGroupSourceSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	routingGroupSources1, err := insertRoutingGroupNestedGroupRoutingGroupSources0(ctx, exec, related, routingGroup0)
	if err != nil {
		return err
	}

	routingGroup0.R.NestedGroupRoutingGroupSources = append(routingGroup0.R.NestedGroupRoutingGroupSources, routingGroupSources1...)

	return nil
}

func (routingGroup0 *RoutingGroup) AttachNestedGroupRoutingGroupSources(ctx context.Context, exec bob.Executor, related ...*RoutingGroupSource) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	routingGroupSources1 := RoutingGroupSourceSlice(related)

	_, err = attachRoutingGroupNestedGroupRoutingGroupSources0(ctx, exec, len(related), routingGroupSources1, routingGroup0)
	if err != nil {
		return err
	}

	routingGroup0.R.NestedGroupRoutingGroupSources = append(routingGroup0.R.NestedGroupRoutingGroupSources, routingGroupSources1...)

	return nil
}

func insertRoutingGroupGroupRoutingGroupStages0(ctx context.Context, exec bob.Executor, routingGroupStages1 []*RoutingGroupStageSetter, routingGroup0 *RoutingGroup) (RoutingGroupStageSlice, error) {
	for i := range routingGroupStages1 {
		routingGroupStages1[i].GroupID = func() *string { return &routingGroup0.ID }()
	}

	ret, err := RoutingGroupStages.Insert(bob.ToMods(routingGroupStages1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertRoutingGroupGroupRoutingGroupStages0: %w", err)
	}

	return ret, nil
}

func attachRoutingGroupGroupRoutingGroupStages0(ctx context.Context, exec bob.Executor, count int, routingGroupStages1 RoutingGroupStageSlice, routingGroup0 *RoutingGroup) (RoutingGroupStageSlice, error) {
	setter := &RoutingGroupStageSetter{
		GroupID: func() *string { return &routingGroup0.ID }(),
	}

	err := routingGroupStages1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachRoutingGroupGroupRoutingGroupStages0: %w", err)
	}

	return routingGroupStages1, nil
}

func (routingGroup0 *RoutingGroup) InsertGroupRoutingGroupStages(ctx context.Context, exec bob.Executor, related ...*RoutingGroupStageSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	routingGroupStages1, err := insertRoutingGroupGroupRoutingGroupStages0(ctx, exec, related, routingGroup0)
	if err != nil {
		return err
	}

	routingGroup0.R.GroupRoutingGroupStages = append(routingGroup0.R.GroupRoutingGroupStages, routingGroupStages1...)

	return nil
}

func (routingGroup0 *RoutingGroup) AttachGroupRoutingGroupStages(ctx context.Context, exec bob.Executor, related ...*RoutingGroupStage) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	routingGroupStages1 := RoutingGroupStageSlice(related)

	_, err = attachRoutingGroupGroupRoutingGroupStages0(ctx, exec, len(related), routingGroupStages1, routingGroup0)
	if err != nil {
		return err
	}

	routingGroup0.R.GroupRoutingGroupStages = append(routingGroup0.R.GroupRoutingGroupStages, routingGroupStages1...)

	return nil
}
