// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// RoutingGroupStageProvider is an object representing the database table.
type RoutingGroupStageProvider struct {
	StageID      string `db:"stage_id,pk" `
	ProviderName string `db:"provider_name,pk" `

	R routingGroupStageProviderR `db:"-" `
}

// RoutingGroupStageProviderSlice is an alias for a slice of pointers to RoutingGroupStageProvider.
// This should almost always be used instead of []*RoutingGroupStageProvider.
type RoutingGroupStageProviderSlice []*RoutingGroupStageProvider

// RoutingGroupStageProviders contains methods to work with the routing_group_stage_providers table
var RoutingGroupStageProviders = sqlite.NewTablex[*RoutingGroupStageProvider, RoutingGroupStageProviderSlice, *RoutingGroupStageProviderSetter]("", "routing_group_stage_providers", buildRoutingGroupStageProviderColumns("routing_group_stage_providers"), routingGroupStageProviderScanMapper)

// RoutingGroupStageProvidersQuery is a query on the routing_group_stage_providers table
type RoutingGroupStageProvidersQuery = *sqlite.ViewQuery[*RoutingGroupStageProvider, RoutingGroupStageProviderSlice]

// routingGroupStageProviderR is where relationships are stored.
type routingGroupStageProviderR struct {
	StageRoutingGroupStage *RoutingGroupStage // fk_routing_group_stage_providers_0
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded routingGroupStageProviderRLoaded `db:"-" `
}

// routingGroupStageProviderRLoaded tracks which relationships on RoutingGroupStageProvider have been loaded.
type routingGroupStageProviderRLoaded struct {
	StageRoutingGroupStage bool // fk_routing_group_stage_providers_0
}

func buildRoutingGroupStageProviderColumns(tableName string) routingGroupStageProviderColumns {
	columnsExpr := expr.NewColumnsExpr(
		"stage_id", "provider_name",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return routingGroupStageProviderColumns{
		ColumnsExpr:  columnsExpr,
		tableAlias:   tableName,
		StageID:      buildRoutingGroupStageProviderColumn(tableName, "stage_id"),
		ProviderName: buildRoutingGroupStageProviderColumn(tableName, "provider_name"),
	}
}

type routingGroupStageProviderColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	StageID      routingGroupStageProviderColumn
	ProviderName routingGroupStageProviderColumn
}

// Alias returns the current table alias for the columns set.
func (c routingGroupStageProviderColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (routingGroupStageProviderColumns) AliasedAs(tableName string) routingGroupStageProviderColumns {
	return buildRoutingGroupStageProviderColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c routingGroupStageProviderColumns) Unqualified() routingGroupStageProviderColumns {
	return buildRoutingGroupStageProviderColumns("")
}

func buildRoutingGroupStageProviderColumn(alias, name string) routingGroupStageProviderColumn {
	return routingGroupStageProviderColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type routingGroupStageProviderColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c routingGroupStageProviderColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c routingGroupStageProviderColumn) ShouldOmitParens() bool {
	return true
}

// RoutingGroupStageProviderSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type RoutingGroupStageProviderSetter struct {
	StageID      *string `db:"stage_id,pk" `
	ProviderName *string `db:"provider_name,pk" `
}

func (s RoutingGroupStageProviderSetter) SetColumns() []string {
	vals := make([]string, 0, 2)
	if s.StageID != nil {
		vals = append(vals, "stage_id")
	}
	if s.ProviderName != nil {
		vals = append(vals, "provider_name")
	}
	return vals
}

func (s RoutingGroupStageProviderSetter) Overwrite(t *RoutingGroupStageProvider) {
	if s.StageID != nil {
		t.StageID = func() string {
			if s.StageID == nil {
				return *new(string)
			}
			return *s.StageID
		}()
	}
	if s.ProviderName != nil {
		t.ProviderName = func() string {
			if s.ProviderName == nil {
				return *new(string)
			}
			return *s.ProviderName
		}()
	}
}

func (s *RoutingGroupStageProviderSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return RoutingGroupStageProviders.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"stage_id", "provider_name"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "stage_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.StageID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.StageID == nil {
						return *new(string)
					}
					return *s.StageID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "provider_name":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ProviderName == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.ProviderName == nil {
						return *new(string)
					}
					return *s.ProviderName
				}()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s RoutingGroupStageProviderSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s RoutingGroupStageProviderSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 2)

	if s.StageID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "stage_id")...),
			sqlite.Arg(s.StageID),
		}})
	}

	if s.ProviderName != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "provider_name")...),
			sqlite.Arg(s.ProviderName),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func routingGroupStageProviderScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*RoutingGroupStageProvider, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *RoutingGroupStageProvider) any
	}
	targets := make([]target, 0, 2)
	for i, col := range cols {
		switch col {
		case "stage_id":
			targets = append(targets, target{i, func(o *RoutingGroupStageProvider) any { return &o.StageID }})
		case "provider_name":
			targets = append(targets, target{i, func(o *RoutingGroupStageProvider) any { return &o.ProviderName }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(RoutingGroupStageProvider)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*RoutingGroupStageProvider, error) {
			return v.(*RoutingGroupStageProvider), nil
		}
}

// FindRoutingGroupStageProvider retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindRoutingGroupStageProvider(ctx context.Context, exec bob.Executor, StageIDPK string, ProviderNamePK string, cols ...string) (*RoutingGroupStageProvider, error) {
	if len(cols) == 0 {
		return RoutingGroupStageProviders.Query(
			sm.Where(RoutingGroupStageProviders.Columns.StageID.EQ(sqlite.Arg(StageIDPK))),
			sm.Where(RoutingGroupStageProviders.Columns.ProviderName.EQ(sqlite.Arg(ProviderNamePK))),
		).One(ctx, exec)
	}

	return RoutingGroupStageProviders.Query(
		sm.Where(RoutingGroupStageProviders.Columns.StageID.EQ(sqlite.Arg(StageIDPK))),
		sm.Where(RoutingGroupStageProviders.Columns.ProviderName.EQ(sqlite.Arg(ProviderNamePK))),
		sm.Columns(RoutingGroupStageProviders.Columns.Only(cols...)),
	).One(ctx, exec)
}

// RoutingGroupStageProviderExists checks the presence of a single record by primary key
func RoutingGroupStageProviderExists(ctx context.Context, exec bob.Executor, StageIDPK string, ProviderNamePK string) (bool, error) {
	return RoutingGroupStageProviders.Query(
		sm.Where(RoutingGroupStageProviders.Columns.StageID.EQ(sqlite.Arg(StageIDPK))),
		sm.Where(RoutingGroupStageProviders.Columns.ProviderName.EQ(sqlite.Arg(ProviderNamePK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after RoutingGroupStageProvider is retrieved from the database
func (o *RoutingGroupStageProvider) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RoutingGroupStageProviders.AfterSelectHooks.RunHooks(ctx, exec, RoutingGroupStageProviderSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = RoutingGroupStageProviders.AfterInsertHooks.RunHooks(ctx, exec, RoutingGroupStageProviderSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = RoutingGroupStageProviders.AfterUpdateHooks.RunHooks(ctx, exec, RoutingGroupStageProviderSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = RoutingGroupStageProviders.AfterDeleteHooks.RunHooks(ctx, exec, RoutingGroupStageProviderSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the RoutingGroupStageProvider
func (o *RoutingGroupStageProvider) primaryKeyVals() bob.Expression {
	return sqlite.ArgGroup(
		o.StageID,
		o.ProviderName,
	)
}

func (o *RoutingGroupStageProvider) pkEQ() dialect.Expression {
	return sqlite.Group(sqlite.Quote("routing_group_stage_providers", "stage_id"), sqlite.Quote("routing_group_stage_providers", "provider_name")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the RoutingGroupStageProvider
func (o *RoutingGroupStageProvider) Update(ctx context.Context, exec bob.Executor, s *RoutingGroupStageProviderSetter) error {
	v, err := RoutingGroupStageProviders.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single RoutingGroupStageProvider record with an executor
func (o *RoutingGroupStageProvider) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := RoutingGroupStageProviders.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the RoutingGroupStageProvider using the executor
func (o *RoutingGroupStageProvider) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := RoutingGroupStageProviders.Query(
		sm.Where(RoutingGroupStageProviders.Columns.StageID.EQ(sqlite.Arg(o.StageID))),
		sm.Where(RoutingGroupStageProviders.Columns.ProviderName.EQ(sqlite.Arg(o.ProviderName))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after RoutingGroupStageProviderSlice is retrieved from the database
func (o RoutingGroupStageProviderSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RoutingGroupStageProviders.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = RoutingGroupStageProviders.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = RoutingGroupStageProviders.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = RoutingGroupStageProviders.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o RoutingGroupStageProviderSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Group(sqlite.Quote("routing_group_stage_providers", "stage_id"), sqlite.Quote("routing_group_stage_providers", "provider_name")).In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o RoutingGroupStageProviderSlice) copyMatchingRows(from ...*RoutingGroupStageProvider) {
	for i, old := range o {
		for _, new := range from {
			if new.StageID != old.StageID {
				continue
			}
			if new.ProviderName != old.ProviderName {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o RoutingGroupStageProviderSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RoutingGroupStageProviders.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RoutingGroupStageProvider:
				o.copyMatchingRows(retrieved)
			case []*RoutingGroupStageProvider:
				o.copyMatchingRows(retrieved...)
			case RoutingGroupStageProviderSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RoutingGroupStageProvider or a slice of RoutingGroupStageProvider
				// then run the AfterUpdateHooks on the slice
				_, err = RoutingGroupStageProviders.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o RoutingGroupStageProviderSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RoutingGroupStageProviders.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RoutingGroupStageProvider:
				o.copyMatchingRows(retrieved)
			case []*RoutingGroupStageProvider:
				o.copyMatchingRows(retrieved...)
			case RoutingGroupStageProviderSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RoutingGroupStageProvider or a slice of RoutingGroupStageProvider
				// then run the AfterDeleteHooks on the slice
				_, err = RoutingGroupStageProviders.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o RoutingGroupStageProviderSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals RoutingGroupStageProviderSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RoutingGroupStageProviders.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o RoutingGroupStageProviderSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RoutingGroupStageProviders.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o RoutingGroupStageProviderSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := RoutingGroupStageProviders.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// StageRoutingGroupStage starts a query for related objects on routing_group_stages
func (o *RoutingGroupStageProvider) StageRoutingGroupStage(mods ...bob.Mod[*dialect.SelectQuery]) RoutingGroupStagesQuery {
	return RoutingGroupStages.Query(append(mods,
		sm.Where(RoutingGroupStages.Columns.ID.EQ(sqlite.Arg(o.StageID))),
	)...)
}

func (os RoutingGroupStageProviderSlice) StageRoutingGroupStage(mods ...bob.Mod[*dialect.SelectQuery]) RoutingGroupStagesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.StageID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return RoutingGroupStages.Query(append(mods,
		sm.Where(sqlite.Group(RoutingGroupStages.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachRoutingGroupStageProviderStageRoutingGroupStage0(ctx context.Context, exec bob.Executor, count int, routingGroupStageProvider0 *RoutingGroupStageProvider, routingGroupStage1 *RoutingGroupStage) (*RoutingGroupStageProvider, error) {
	setter := &RoutingGroupStageProviderSetter{
		StageID: func() *string { return &routingGroupStage1.ID }(),
	}

	err := routingGroupStageProvider0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachRoutingGroupStageProviderStageRoutingGroupStage0: %w", err)
	}

	return routingGroupStageProvider0, nil
}

func (routingGroupStageProvider0 *RoutingGroupStageProvider) InsertStageRoutingGroupStage(ctx context.Context, exec bob.Executor, related *RoutingGroupStageSetter) error {
	var err error

	routingGroupStage1, err := RoutingGroupStages.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachRoutingGroupStageProviderStageRoutingGroupStage0(ctx, exec, 1, routingGroupStageProvider0, routingGroupStage1)
	if err != nil {
		return err
	}

	routingGroupStageProvider0.R.StageRoutingGroupStage = routingGroupStage1
	routingGroupStageProvider0.R.Loaded.StageRoutingGroupStage = true

	return nil
}

func (routingGroupStageProvider0 *RoutingGroupStageProvider) AttachStageRoutingGroupStage(ctx context.Context, exec bob.Executor, routingGroupStage1 *RoutingGroupStage) error {
	var err error

	_, err = attachRoutingGroupStageProviderStageRoutingGroupStage0(ctx, exec, 1, routingGroupStageProvider0, routingGroupStage1)
	if err != nil {
		return err
	}

	routingGroupStageProvider0.R.StageRoutingGroupStage = routingGroupStage1
	routingGroupStageProvider0.R.Loaded.StageRoutingGroupStage = true

	return nil
}
