// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// RoutingGroupStageBillingClass is an object representing the database table.
type RoutingGroupStageBillingClass struct {
	StageID      string `db:"stage_id,pk" `
	BillingClass string `db:"billing_class,pk" `

	R routingGroupStageBillingClassR `db:"-" `
}

// RoutingGroupStageBillingClassSlice is an alias for a slice of pointers to RoutingGroupStageBillingClass.
// This should almost always be used instead of []*RoutingGroupStageBillingClass.
type RoutingGroupStageBillingClassSlice []*RoutingGroupStageBillingClass

// RoutingGroupStageBillingClasses contains methods to work with the routing_group_stage_billing_classes table
var RoutingGroupStageBillingClasses = sqlite.NewTablex[*RoutingGroupStageBillingClass, RoutingGroupStageBillingClassSlice, *RoutingGroupStageBillingClassSetter]("", "routing_group_stage_billing_classes", buildRoutingGroupStageBillingClassColumns("routing_group_stage_billing_classes"), routingGroupStageBillingClassScanMapper)

// RoutingGroupStageBillingClassesQuery is a query on the routing_group_stage_billing_classes table
type RoutingGroupStageBillingClassesQuery = *sqlite.ViewQuery[*RoutingGroupStageBillingClass, RoutingGroupStageBillingClassSlice]

// routingGroupStageBillingClassR is where relationships are stored.
type routingGroupStageBillingClassR struct {
	StageRoutingGroupStage *RoutingGroupStage // fk_routing_group_stage_billing_classes_0
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded routingGroupStageBillingClassRLoaded `db:"-" `
}

// routingGroupStageBillingClassRLoaded tracks which relationships on RoutingGroupStageBillingClass have been loaded.
type routingGroupStageBillingClassRLoaded struct {
	StageRoutingGroupStage bool // fk_routing_group_stage_billing_classes_0
}

func buildRoutingGroupStageBillingClassColumns(tableName string) routingGroupStageBillingClassColumns {
	columnsExpr := expr.NewColumnsExpr(
		"stage_id", "billing_class",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return routingGroupStageBillingClassColumns{
		ColumnsExpr:  columnsExpr,
		tableAlias:   tableName,
		StageID:      buildRoutingGroupStageBillingClassColumn(tableName, "stage_id"),
		BillingClass: buildRoutingGroupStageBillingClassColumn(tableName, "billing_class"),
	}
}

type routingGroupStageBillingClassColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	StageID      routingGroupStageBillingClassColumn
	BillingClass routingGroupStageBillingClassColumn
}

// Alias returns the current table alias for the columns set.
func (c routingGroupStageBillingClassColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (routingGroupStageBillingClassColumns) AliasedAs(tableName string) routingGroupStageBillingClassColumns {
	return buildRoutingGroupStageBillingClassColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c routingGroupStageBillingClassColumns) Unqualified() routingGroupStageBillingClassColumns {
	return buildRoutingGroupStageBillingClassColumns("")
}

func buildRoutingGroupStageBillingClassColumn(alias, name string) routingGroupStageBillingClassColumn {
	return routingGroupStageBillingClassColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type routingGroupStageBillingClassColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c routingGroupStageBillingClassColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c routingGroupStageBillingClassColumn) ShouldOmitParens() bool {
	return true
}

// RoutingGroupStageBillingClassSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type RoutingGroupStageBillingClassSetter struct {
	StageID      *string `db:"stage_id,pk" `
	BillingClass *string `db:"billing_class,pk" `
}

func (s RoutingGroupStageBillingClassSetter) SetColumns() []string {
	vals := make([]string, 0, 2)
	if s.StageID != nil {
		vals = append(vals, "stage_id")
	}
	if s.BillingClass != nil {
		vals = append(vals, "billing_class")
	}
	return vals
}

func (s RoutingGroupStageBillingClassSetter) Overwrite(t *RoutingGroupStageBillingClass) {
	if s.StageID != nil {
		t.StageID = func() string {
			if s.StageID == nil {
				return *new(string)
			}
			return *s.StageID
		}()
	}
	if s.BillingClass != nil {
		t.BillingClass = func() string {
			if s.BillingClass == nil {
				return *new(string)
			}
			return *s.BillingClass
		}()
	}
}

func (s *RoutingGroupStageBillingClassSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return RoutingGroupStageBillingClasses.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"stage_id", "billing_class"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "stage_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.StageID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.StageID == nil {
						return *new(string)
					}
					return *s.StageID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "billing_class":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.BillingClass == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.BillingClass == nil {
						return *new(string)
					}
					return *s.BillingClass
				}()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s RoutingGroupStageBillingClassSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s RoutingGroupStageBillingClassSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 2)

	if s.StageID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "stage_id")...),
			sqlite.Arg(s.StageID),
		}})
	}

	if s.BillingClass != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "billing_class")...),
			sqlite.Arg(s.BillingClass),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func routingGroupStageBillingClassScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*RoutingGroupStageBillingClass, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *RoutingGroupStageBillingClass) any
	}
	targets := make([]target, 0, 2)
	for i, col := range cols {
		switch col {
		case "stage_id":
			targets = append(targets, target{i, func(o *RoutingGroupStageBillingClass) any { return &o.StageID }})
		case "billing_class":
			targets = append(targets, target{i, func(o *RoutingGroupStageBillingClass) any { return &o.BillingClass }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(RoutingGroupStageBillingClass)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*RoutingGroupStageBillingClass, error) {
			return v.(*RoutingGroupStageBillingClass), nil
		}
}

// FindRoutingGroupStageBillingClass retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindRoutingGroupStageBillingClass(ctx context.Context, exec bob.Executor, StageIDPK string, BillingClassPK string, cols ...string) (*RoutingGroupStageBillingClass, error) {
	if len(cols) == 0 {
		return RoutingGroupStageBillingClasses.Query(
			sm.Where(RoutingGroupStageBillingClasses.Columns.StageID.EQ(sqlite.Arg(StageIDPK))),
			sm.Where(RoutingGroupStageBillingClasses.Columns.BillingClass.EQ(sqlite.Arg(BillingClassPK))),
		).One(ctx, exec)
	}

	return RoutingGroupStageBillingClasses.Query(
		sm.Where(RoutingGroupStageBillingClasses.Columns.StageID.EQ(sqlite.Arg(StageIDPK))),
		sm.Where(RoutingGroupStageBillingClasses.Columns.BillingClass.EQ(sqlite.Arg(BillingClassPK))),
		sm.Columns(RoutingGroupStageBillingClasses.Columns.Only(cols...)),
	).One(ctx, exec)
}

// RoutingGroupStageBillingClassExists checks the presence of a single record by primary key
func RoutingGroupStageBillingClassExists(ctx context.Context, exec bob.Executor, StageIDPK string, BillingClassPK string) (bool, error) {
	return RoutingGroupStageBillingClasses.Query(
		sm.Where(RoutingGroupStageBillingClasses.Columns.StageID.EQ(sqlite.Arg(StageIDPK))),
		sm.Where(RoutingGroupStageBillingClasses.Columns.BillingClass.EQ(sqlite.Arg(BillingClassPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after RoutingGroupStageBillingClass is retrieved from the database
func (o *RoutingGroupStageBillingClass) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RoutingGroupStageBillingClasses.AfterSelectHooks.RunHooks(ctx, exec, RoutingGroupStageBillingClassSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = RoutingGroupStageBillingClasses.AfterInsertHooks.RunHooks(ctx, exec, RoutingGroupStageBillingClassSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = RoutingGroupStageBillingClasses.AfterUpdateHooks.RunHooks(ctx, exec, RoutingGroupStageBillingClassSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = RoutingGroupStageBillingClasses.AfterDeleteHooks.RunHooks(ctx, exec, RoutingGroupStageBillingClassSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the RoutingGroupStageBillingClass
func (o *RoutingGroupStageBillingClass) primaryKeyVals() bob.Expression {
	return sqlite.ArgGroup(
		o.StageID,
		o.BillingClass,
	)
}

func (o *RoutingGroupStageBillingClass) pkEQ() dialect.Expression {
	return sqlite.Group(sqlite.Quote("routing_group_stage_billing_classes", "stage_id"), sqlite.Quote("routing_group_stage_billing_classes", "billing_class")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the RoutingGroupStageBillingClass
func (o *RoutingGroupStageBillingClass) Update(ctx context.Context, exec bob.Executor, s *RoutingGroupStageBillingClassSetter) error {
	v, err := RoutingGroupStageBillingClasses.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single RoutingGroupStageBillingClass record with an executor
func (o *RoutingGroupStageBillingClass) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := RoutingGroupStageBillingClasses.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the RoutingGroupStageBillingClass using the executor
func (o *RoutingGroupStageBillingClass) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := RoutingGroupStageBillingClasses.Query(
		sm.Where(RoutingGroupStageBillingClasses.Columns.StageID.EQ(sqlite.Arg(o.StageID))),
		sm.Where(RoutingGroupStageBillingClasses.Columns.BillingClass.EQ(sqlite.Arg(o.BillingClass))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after RoutingGroupStageBillingClassSlice is retrieved from the database
func (o RoutingGroupStageBillingClassSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RoutingGroupStageBillingClasses.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = RoutingGroupStageBillingClasses.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = RoutingGroupStageBillingClasses.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = RoutingGroupStageBillingClasses.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o RoutingGroupStageBillingClassSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Group(sqlite.Quote("routing_group_stage_billing_classes", "stage_id"), sqlite.Quote("routing_group_stage_billing_classes", "billing_class")).In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o RoutingGroupStageBillingClassSlice) copyMatchingRows(from ...*RoutingGroupStageBillingClass) {
	for i, old := range o {
		for _, new := range from {
			if new.StageID != old.StageID {
				continue
			}
			if new.BillingClass != old.BillingClass {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o RoutingGroupStageBillingClassSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RoutingGroupStageBillingClasses.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RoutingGroupStageBillingClass:
				o.copyMatchingRows(retrieved)
			case []*RoutingGroupStageBillingClass:
				o.copyMatchingRows(retrieved...)
			case RoutingGroupStageBillingClassSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RoutingGroupStageBillingClass or a slice of RoutingGroupStageBillingClass
				// then run the AfterUpdateHooks on the slice
				_, err = RoutingGroupStageBillingClasses.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o RoutingGroupStageBillingClassSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RoutingGroupStageBillingClasses.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RoutingGroupStageBillingClass:
				o.copyMatchingRows(retrieved)
			case []*RoutingGroupStageBillingClass:
				o.copyMatchingRows(retrieved...)
			case RoutingGroupStageBillingClassSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RoutingGroupStageBillingClass or a slice of RoutingGroupStageBillingClass
				// then run the AfterDeleteHooks on the slice
				_, err = RoutingGroupStageBillingClasses.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o RoutingGroupStageBillingClassSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals RoutingGroupStageBillingClassSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RoutingGroupStageBillingClasses.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o RoutingGroupStageBillingClassSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RoutingGroupStageBillingClasses.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o RoutingGroupStageBillingClassSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := RoutingGroupStageBillingClasses.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// StageRoutingGroupStage starts a query for related objects on routing_group_stages
func (o *RoutingGroupStageBillingClass) StageRoutingGroupStage(mods ...bob.Mod[*dialect.SelectQuery]) RoutingGroupStagesQuery {
	return RoutingGroupStages.Query(append(mods,
		sm.Where(RoutingGroupStages.Columns.ID.EQ(sqlite.Arg(o.StageID))),
	)...)
}

func (os RoutingGroupStageBillingClassSlice) StageRoutingGroupStage(mods ...bob.Mod[*dialect.SelectQuery]) RoutingGroupStagesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.StageID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return RoutingGroupStages.Query(append(mods,
		sm.Where(sqlite.Group(RoutingGroupStages.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachRoutingGroupStageBillingClassStageRoutingGroupStage0(ctx context.Context, exec bob.Executor, count int, routingGroupStageBillingClass0 *RoutingGroupStageBillingClass, routingGroupStage1 *RoutingGroupStage) (*RoutingGroupStageBillingClass, error) {
	setter := &RoutingGroupStageBillingClassSetter{
		StageID: func() *string { return &routingGroupStage1.ID }(),
	}

	err := routingGroupStageBillingClass0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachRoutingGroupStageBillingClassStageRoutingGroupStage0: %w", err)
	}

	return routingGroupStageBillingClass0, nil
}

func (routingGroupStageBillingClass0 *RoutingGroupStageBillingClass) InsertStageRoutingGroupStage(ctx context.Context, exec bob.Executor, related *RoutingGroupStageSetter) error {
	var err error

	routingGroupStage1, err := RoutingGroupStages.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachRoutingGroupStageBillingClassStageRoutingGroupStage0(ctx, exec, 1, routingGroupStageBillingClass0, routingGroupStage1)
	if err != nil {
		return err
	}

	routingGroupStageBillingClass0.R.StageRoutingGroupStage = routingGroupStage1
	routingGroupStageBillingClass0.R.Loaded.StageRoutingGroupStage = true

	return nil
}

func (routingGroupStageBillingClass0 *RoutingGroupStageBillingClass) AttachStageRoutingGroupStage(ctx context.Context, exec bob.Executor, routingGroupStage1 *RoutingGroupStage) error {
	var err error

	_, err = attachRoutingGroupStageBillingClassStageRoutingGroupStage0(ctx, exec, 1, routingGroupStageBillingClass0, routingGroupStage1)
	if err != nil {
		return err
	}

	routingGroupStageBillingClass0.R.StageRoutingGroupStage = routingGroupStage1
	routingGroupStageBillingClass0.R.Loaded.StageRoutingGroupStage = true

	return nil
}
