// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// Session is an object representing the database table.
type Session struct {
	ClientKeyID string `db:"client_key_id,pk" `
	SessionID   string `db:"session_id,pk" `
	CreatedAt   string `db:"created_at" `
	LastSeenAt  string `db:"last_seen_at" `

	R sessionR `db:"-" `
}

// SessionSlice is an alias for a slice of pointers to Session.
// This should almost always be used instead of []*Session.
type SessionSlice []*Session

// Sessions contains methods to work with the sessions table
var Sessions = sqlite.NewTablex[*Session, SessionSlice, *SessionSetter]("", "sessions", buildSessionColumns("sessions"), sessionScanMapper)

// SessionsQuery is a query on the sessions table
type SessionsQuery = *sqlite.ViewQuery[*Session, SessionSlice]

// sessionR is where relationships are stored.
type sessionR struct {
	SessionKeys SessionKeySlice // fk_session_keys_0
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded sessionRLoaded `db:"-" `
}

// sessionRLoaded tracks which relationships on Session have been loaded.
type sessionRLoaded struct {
	SessionKeys bool // fk_session_keys_0
}

func buildSessionColumns(tableName string) sessionColumns {
	columnsExpr := expr.NewColumnsExpr(
		"client_key_id", "session_id", "created_at", "last_seen_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return sessionColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ClientKeyID: buildSessionColumn(tableName, "client_key_id"),
		SessionID:   buildSessionColumn(tableName, "session_id"),
		CreatedAt:   buildSessionColumn(tableName, "created_at"),
		LastSeenAt:  buildSessionColumn(tableName, "last_seen_at"),
	}
}

type sessionColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ClientKeyID sessionColumn
	SessionID   sessionColumn
	CreatedAt   sessionColumn
	LastSeenAt  sessionColumn
}

// Alias returns the current table alias for the columns set.
func (c sessionColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (sessionColumns) AliasedAs(tableName string) sessionColumns {
	return buildSessionColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c sessionColumns) Unqualified() sessionColumns {
	return buildSessionColumns("")
}

func buildSessionColumn(alias, name string) sessionColumn {
	return sessionColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type sessionColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c sessionColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c sessionColumn) ShouldOmitParens() bool {
	return true
}

// SessionSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type SessionSetter struct {
	ClientKeyID *string `db:"client_key_id,pk" `
	SessionID   *string `db:"session_id,pk" `
	CreatedAt   *string `db:"created_at" `
	LastSeenAt  *string `db:"last_seen_at" `
}

func (s SessionSetter) SetColumns() []string {
	vals := make([]string, 0, 4)
	if s.ClientKeyID != nil {
		vals = append(vals, "client_key_id")
	}
	if s.SessionID != nil {
		vals = append(vals, "session_id")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.LastSeenAt != nil {
		vals = append(vals, "last_seen_at")
	}
	return vals
}

func (s SessionSetter) Overwrite(t *Session) {
	if s.ClientKeyID != nil {
		t.ClientKeyID = func() string {
			if s.ClientKeyID == nil {
				return *new(string)
			}
			return *s.ClientKeyID
		}()
	}
	if s.SessionID != nil {
		t.SessionID = func() string {
			if s.SessionID == nil {
				return *new(string)
			}
			return *s.SessionID
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() string {
			if s.CreatedAt == nil {
				return *new(string)
			}
			return *s.CreatedAt
		}()
	}
	if s.LastSeenAt != nil {
		t.LastSeenAt = func() string {
			if s.LastSeenAt == nil {
				return *new(string)
			}
			return *s.LastSeenAt
		}()
	}
}

func (s *SessionSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Sessions.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"client_key_id", "session_id"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "client_key_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ClientKeyID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.ClientKeyID == nil {
						return *new(string)
					}
					return *s.ClientKeyID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "session_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.SessionID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.SessionID == nil {
						return *new(string)
					}
					return *s.SessionID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "created_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.CreatedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.CreatedAt == nil {
						return *new(string)
					}
					return *s.CreatedAt
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "last_seen_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LastSeenAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.LastSeenAt == nil {
						return *new(string)
					}
					return *s.LastSeenAt
				}()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s SessionSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s SessionSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 4)

	if s.ClientKeyID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "client_key_id")...),
			sqlite.Arg(s.ClientKeyID),
		}})
	}

	if s.SessionID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "session_id")...),
			sqlite.Arg(s.SessionID),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.LastSeenAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "last_seen_at")...),
			sqlite.Arg(s.LastSeenAt),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func sessionScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Session, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *Session) any
	}
	targets := make([]target, 0, 4)
	for i, col := range cols {
		switch col {
		case "client_key_id":
			targets = append(targets, target{i, func(o *Session) any { return &o.ClientKeyID }})
		case "session_id":
			targets = append(targets, target{i, func(o *Session) any { return &o.SessionID }})
		case "created_at":
			targets = append(targets, target{i, func(o *Session) any { return &o.CreatedAt }})
		case "last_seen_at":
			targets = append(targets, target{i, func(o *Session) any { return &o.LastSeenAt }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(Session)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*Session, error) {
			return v.(*Session), nil
		}
}

// FindSession retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindSession(ctx context.Context, exec bob.Executor, ClientKeyIDPK string, SessionIDPK string, cols ...string) (*Session, error) {
	if len(cols) == 0 {
		return Sessions.Query(
			sm.Where(Sessions.Columns.ClientKeyID.EQ(sqlite.Arg(ClientKeyIDPK))),
			sm.Where(Sessions.Columns.SessionID.EQ(sqlite.Arg(SessionIDPK))),
		).One(ctx, exec)
	}

	return Sessions.Query(
		sm.Where(Sessions.Columns.ClientKeyID.EQ(sqlite.Arg(ClientKeyIDPK))),
		sm.Where(Sessions.Columns.SessionID.EQ(sqlite.Arg(SessionIDPK))),
		sm.Columns(Sessions.Columns.Only(cols...)),
	).One(ctx, exec)
}

// SessionExists checks the presence of a single record by primary key
func SessionExists(ctx context.Context, exec bob.Executor, ClientKeyIDPK string, SessionIDPK string) (bool, error) {
	return Sessions.Query(
		sm.Where(Sessions.Columns.ClientKeyID.EQ(sqlite.Arg(ClientKeyIDPK))),
		sm.Where(Sessions.Columns.SessionID.EQ(sqlite.Arg(SessionIDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Session is retrieved from the database
func (o *Session) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Sessions.AfterSelectHooks.RunHooks(ctx, exec, SessionSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Sessions.AfterInsertHooks.RunHooks(ctx, exec, SessionSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Sessions.AfterUpdateHooks.RunHooks(ctx, exec, SessionSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Sessions.AfterDeleteHooks.RunHooks(ctx, exec, SessionSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the Session
func (o *Session) primaryKeyVals() bob.Expression {
	return sqlite.ArgGroup(
		o.ClientKeyID,
		o.SessionID,
	)
}

func (o *Session) pkEQ() dialect.Expression {
	return sqlite.Group(sqlite.Quote("sessions", "client_key_id"), sqlite.Quote("sessions", "session_id")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Session
func (o *Session) Update(ctx context.Context, exec bob.Executor, s *SessionSetter) error {
	v, err := Sessions.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Session record with an executor
func (o *Session) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Sessions.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Session using the executor
func (o *Session) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Sessions.Query(
		sm.Where(Sessions.Columns.ClientKeyID.EQ(sqlite.Arg(o.ClientKeyID))),
		sm.Where(Sessions.Columns.SessionID.EQ(sqlite.Arg(o.SessionID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after SessionSlice is retrieved from the database
func (o SessionSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Sessions.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Sessions.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Sessions.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Sessions.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o SessionSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Group(sqlite.Quote("sessions", "client_key_id"), sqlite.Quote("sessions", "session_id")).In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o SessionSlice) copyMatchingRows(from ...*Session) {
	for i, old := range o {
		for _, new := range from {
			if new.ClientKeyID != old.ClientKeyID {
				continue
			}
			if new.SessionID != old.SessionID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o SessionSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Sessions.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Session:
				o.copyMatchingRows(retrieved)
			case []*Session:
				o.copyMatchingRows(retrieved...)
			case SessionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Session or a slice of Session
				// then run the AfterUpdateHooks on the slice
				_, err = Sessions.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o SessionSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Sessions.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Session:
				o.copyMatchingRows(retrieved)
			case []*Session:
				o.copyMatchingRows(retrieved...)
			case SessionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Session or a slice of Session
				// then run the AfterDeleteHooks on the slice
				_, err = Sessions.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o SessionSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals SessionSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Sessions.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o SessionSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Sessions.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o SessionSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Sessions.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// SessionKeys starts a query for related objects on session_keys
func (o *Session) SessionKeys(mods ...bob.Mod[*dialect.SelectQuery]) SessionKeysQuery {
	return SessionKeys.Query(append(mods,
		sm.Where(SessionKeys.Columns.ClientKeyID.EQ(sqlite.Arg(o.ClientKeyID))), sm.Where(SessionKeys.Columns.SessionID.EQ(sqlite.Arg(o.SessionID))),
	)...)
}

func (os SessionSlice) SessionKeys(mods ...bob.Mod[*dialect.SelectQuery]) SessionKeysQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ClientKeyID, o.SessionID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return SessionKeys.Query(append(mods,
		sm.Where(sqlite.Group(SessionKeys.Columns.ClientKeyID, SessionKeys.Columns.SessionID).OP("IN", PKArgExpr)),
	)...)
}

func insertSessionSessionKeys0(ctx context.Context, exec bob.Executor, sessionKeys1 []*SessionKeySetter, session0 *Session) (SessionKeySlice, error) {
	for i := range sessionKeys1 {
		sessionKeys1[i].ClientKeyID = func() *string { return &session0.ClientKeyID }()
		sessionKeys1[i].SessionID = func() *string { return &session0.SessionID }()
	}

	ret, err := SessionKeys.Insert(bob.ToMods(sessionKeys1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertSessionSessionKeys0: %w", err)
	}

	return ret, nil
}

func attachSessionSessionKeys0(ctx context.Context, exec bob.Executor, count int, sessionKeys1 SessionKeySlice, session0 *Session) (SessionKeySlice, error) {
	setter := &SessionKeySetter{
		ClientKeyID: func() *string { return &session0.ClientKeyID }(),
		SessionID:   func() *string { return &session0.SessionID }(),
	}

	err := sessionKeys1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachSessionSessionKeys0: %w", err)
	}

	return sessionKeys1, nil
}

func (session0 *Session) InsertSessionKeys(ctx context.Context, exec bob.Executor, related ...*SessionKeySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	sessionKeys1, err := insertSessionSessionKeys0(ctx, exec, related, session0)
	if err != nil {
		return err
	}

	session0.R.SessionKeys = append(session0.R.SessionKeys, sessionKeys1...)

	return nil
}

func (session0 *Session) AttachSessionKeys(ctx context.Context, exec bob.Executor, related ...*SessionKey) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	sessionKeys1 := SessionKeySlice(related)

	_, err = attachSessionSessionKeys0(ctx, exec, len(related), sessionKeys1, session0)
	if err != nil {
		return err
	}

	session0.R.SessionKeys = append(session0.R.SessionKeys, sessionKeys1...)

	return nil
}
