// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// SessionKey is an object representing the database table.
type SessionKey struct {
	ClientKeyID string `db:"client_key_id,pk" `
	SessionID   string `db:"session_id,pk" `
	KeyHash     string `db:"key_hash,pk" `
	IsAnchor    int64  `db:"is_anchor" `
	LastSeenAt  string `db:"last_seen_at" `

	R sessionKeyR `db:"-" `
}

// SessionKeySlice is an alias for a slice of pointers to SessionKey.
// This should almost always be used instead of []*SessionKey.
type SessionKeySlice []*SessionKey

// SessionKeys contains methods to work with the session_keys table
var SessionKeys = sqlite.NewTablex[*SessionKey, SessionKeySlice, *SessionKeySetter]("", "session_keys", buildSessionKeyColumns("session_keys"), sessionKeyScanMapper)

// SessionKeysQuery is a query on the session_keys table
type SessionKeysQuery = *sqlite.ViewQuery[*SessionKey, SessionKeySlice]

// sessionKeyR is where relationships are stored.
type sessionKeyR struct {
	Session *Session // fk_session_keys_0
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded sessionKeyRLoaded `db:"-" `
}

// sessionKeyRLoaded tracks which relationships on SessionKey have been loaded.
type sessionKeyRLoaded struct {
	Session bool // fk_session_keys_0
}

func buildSessionKeyColumns(tableName string) sessionKeyColumns {
	columnsExpr := expr.NewColumnsExpr(
		"client_key_id", "session_id", "key_hash", "is_anchor", "last_seen_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return sessionKeyColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ClientKeyID: buildSessionKeyColumn(tableName, "client_key_id"),
		SessionID:   buildSessionKeyColumn(tableName, "session_id"),
		KeyHash:     buildSessionKeyColumn(tableName, "key_hash"),
		IsAnchor:    buildSessionKeyColumn(tableName, "is_anchor"),
		LastSeenAt:  buildSessionKeyColumn(tableName, "last_seen_at"),
	}
}

type sessionKeyColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ClientKeyID sessionKeyColumn
	SessionID   sessionKeyColumn
	KeyHash     sessionKeyColumn
	IsAnchor    sessionKeyColumn
	LastSeenAt  sessionKeyColumn
}

// Alias returns the current table alias for the columns set.
func (c sessionKeyColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (sessionKeyColumns) AliasedAs(tableName string) sessionKeyColumns {
	return buildSessionKeyColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c sessionKeyColumns) Unqualified() sessionKeyColumns {
	return buildSessionKeyColumns("")
}

func buildSessionKeyColumn(alias, name string) sessionKeyColumn {
	return sessionKeyColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type sessionKeyColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c sessionKeyColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c sessionKeyColumn) ShouldOmitParens() bool {
	return true
}

// SessionKeySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type SessionKeySetter struct {
	ClientKeyID *string `db:"client_key_id,pk" `
	SessionID   *string `db:"session_id,pk" `
	KeyHash     *string `db:"key_hash,pk" `
	IsAnchor    *int64  `db:"is_anchor" `
	LastSeenAt  *string `db:"last_seen_at" `
}

func (s SessionKeySetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ClientKeyID != nil {
		vals = append(vals, "client_key_id")
	}
	if s.SessionID != nil {
		vals = append(vals, "session_id")
	}
	if s.KeyHash != nil {
		vals = append(vals, "key_hash")
	}
	if s.IsAnchor != nil {
		vals = append(vals, "is_anchor")
	}
	if s.LastSeenAt != nil {
		vals = append(vals, "last_seen_at")
	}
	return vals
}

func (s SessionKeySetter) Overwrite(t *SessionKey) {
	if s.ClientKeyID != nil {
		t.ClientKeyID = func() string {
			if s.ClientKeyID == nil {
				return *new(string)
			}
			return *s.ClientKeyID
		}()
	}
	if s.SessionID != nil {
		t.SessionID = func() string {
			if s.SessionID == nil {
				return *new(string)
			}
			return *s.SessionID
		}()
	}
	if s.KeyHash != nil {
		t.KeyHash = func() string {
			if s.KeyHash == nil {
				return *new(string)
			}
			return *s.KeyHash
		}()
	}
	if s.IsAnchor != nil {
		t.IsAnchor = func() int64 {
			if s.IsAnchor == nil {
				return *new(int64)
			}
			return *s.IsAnchor
		}()
	}
	if s.LastSeenAt != nil {
		t.LastSeenAt = func() string {
			if s.LastSeenAt == nil {
				return *new(string)
			}
			return *s.LastSeenAt
		}()
	}
}

func (s *SessionKeySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return SessionKeys.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"client_key_id", "session_id", "key_hash"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "client_key_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ClientKeyID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.ClientKeyID == nil {
						return *new(string)
					}
					return *s.ClientKeyID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "session_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.SessionID == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.SessionID == nil {
						return *new(string)
					}
					return *s.SessionID
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "key_hash":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.KeyHash == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.KeyHash == nil {
						return *new(string)
					}
					return *s.KeyHash
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "is_anchor":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.IsAnchor == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() int64 {
					if s.IsAnchor == nil {
						return *new(int64)
					}
					return *s.IsAnchor
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "last_seen_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LastSeenAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.LastSeenAt == nil {
						return *new(string)
					}
					return *s.LastSeenAt
				}()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s SessionKeySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s SessionKeySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ClientKeyID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "client_key_id")...),
			sqlite.Arg(s.ClientKeyID),
		}})
	}

	if s.SessionID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "session_id")...),
			sqlite.Arg(s.SessionID),
		}})
	}

	if s.KeyHash != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "key_hash")...),
			sqlite.Arg(s.KeyHash),
		}})
	}

	if s.IsAnchor != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "is_anchor")...),
			sqlite.Arg(s.IsAnchor),
		}})
	}

	if s.LastSeenAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "last_seen_at")...),
			sqlite.Arg(s.LastSeenAt),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func sessionKeyScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*SessionKey, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *SessionKey) any
	}
	targets := make([]target, 0, 5)
	for i, col := range cols {
		switch col {
		case "client_key_id":
			targets = append(targets, target{i, func(o *SessionKey) any { return &o.ClientKeyID }})
		case "session_id":
			targets = append(targets, target{i, func(o *SessionKey) any { return &o.SessionID }})
		case "key_hash":
			targets = append(targets, target{i, func(o *SessionKey) any { return &o.KeyHash }})
		case "is_anchor":
			targets = append(targets, target{i, func(o *SessionKey) any { return &o.IsAnchor }})
		case "last_seen_at":
			targets = append(targets, target{i, func(o *SessionKey) any { return &o.LastSeenAt }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(SessionKey)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*SessionKey, error) {
			return v.(*SessionKey), nil
		}
}

// FindSessionKey retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindSessionKey(ctx context.Context, exec bob.Executor, ClientKeyIDPK string, SessionIDPK string, KeyHashPK string, cols ...string) (*SessionKey, error) {
	if len(cols) == 0 {
		return SessionKeys.Query(
			sm.Where(SessionKeys.Columns.ClientKeyID.EQ(sqlite.Arg(ClientKeyIDPK))),
			sm.Where(SessionKeys.Columns.SessionID.EQ(sqlite.Arg(SessionIDPK))),
			sm.Where(SessionKeys.Columns.KeyHash.EQ(sqlite.Arg(KeyHashPK))),
		).One(ctx, exec)
	}

	return SessionKeys.Query(
		sm.Where(SessionKeys.Columns.ClientKeyID.EQ(sqlite.Arg(ClientKeyIDPK))),
		sm.Where(SessionKeys.Columns.SessionID.EQ(sqlite.Arg(SessionIDPK))),
		sm.Where(SessionKeys.Columns.KeyHash.EQ(sqlite.Arg(KeyHashPK))),
		sm.Columns(SessionKeys.Columns.Only(cols...)),
	).One(ctx, exec)
}

// SessionKeyExists checks the presence of a single record by primary key
func SessionKeyExists(ctx context.Context, exec bob.Executor, ClientKeyIDPK string, SessionIDPK string, KeyHashPK string) (bool, error) {
	return SessionKeys.Query(
		sm.Where(SessionKeys.Columns.ClientKeyID.EQ(sqlite.Arg(ClientKeyIDPK))),
		sm.Where(SessionKeys.Columns.SessionID.EQ(sqlite.Arg(SessionIDPK))),
		sm.Where(SessionKeys.Columns.KeyHash.EQ(sqlite.Arg(KeyHashPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after SessionKey is retrieved from the database
func (o *SessionKey) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = SessionKeys.AfterSelectHooks.RunHooks(ctx, exec, SessionKeySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = SessionKeys.AfterInsertHooks.RunHooks(ctx, exec, SessionKeySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = SessionKeys.AfterUpdateHooks.RunHooks(ctx, exec, SessionKeySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = SessionKeys.AfterDeleteHooks.RunHooks(ctx, exec, SessionKeySlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the SessionKey
func (o *SessionKey) primaryKeyVals() bob.Expression {
	return sqlite.ArgGroup(
		o.ClientKeyID,
		o.SessionID,
		o.KeyHash,
	)
}

func (o *SessionKey) pkEQ() dialect.Expression {
	return sqlite.Group(sqlite.Quote("session_keys", "client_key_id"), sqlite.Quote("session_keys", "session_id"), sqlite.Quote("session_keys", "key_hash")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the SessionKey
func (o *SessionKey) Update(ctx context.Context, exec bob.Executor, s *SessionKeySetter) error {
	v, err := SessionKeys.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single SessionKey record with an executor
func (o *SessionKey) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := SessionKeys.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the SessionKey using the executor
func (o *SessionKey) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := SessionKeys.Query(
		sm.Where(SessionKeys.Columns.ClientKeyID.EQ(sqlite.Arg(o.ClientKeyID))),
		sm.Where(SessionKeys.Columns.SessionID.EQ(sqlite.Arg(o.SessionID))),
		sm.Where(SessionKeys.Columns.KeyHash.EQ(sqlite.Arg(o.KeyHash))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after SessionKeySlice is retrieved from the database
func (o SessionKeySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = SessionKeys.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = SessionKeys.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = SessionKeys.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = SessionKeys.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o SessionKeySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Group(sqlite.Quote("session_keys", "client_key_id"), sqlite.Quote("session_keys", "session_id"), sqlite.Quote("session_keys", "key_hash")).In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o SessionKeySlice) copyMatchingRows(from ...*SessionKey) {
	for i, old := range o {
		for _, new := range from {
			if new.ClientKeyID != old.ClientKeyID {
				continue
			}
			if new.SessionID != old.SessionID {
				continue
			}
			if new.KeyHash != old.KeyHash {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o SessionKeySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return SessionKeys.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *SessionKey:
				o.copyMatchingRows(retrieved)
			case []*SessionKey:
				o.copyMatchingRows(retrieved...)
			case SessionKeySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a SessionKey or a slice of SessionKey
				// then run the AfterUpdateHooks on the slice
				_, err = SessionKeys.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o SessionKeySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return SessionKeys.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *SessionKey:
				o.copyMatchingRows(retrieved)
			case []*SessionKey:
				o.copyMatchingRows(retrieved...)
			case SessionKeySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a SessionKey or a slice of SessionKey
				// then run the AfterDeleteHooks on the slice
				_, err = SessionKeys.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o SessionKeySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals SessionKeySetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := SessionKeys.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o SessionKeySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := SessionKeys.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o SessionKeySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := SessionKeys.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Session starts a query for related objects on sessions
func (o *SessionKey) Session(mods ...bob.Mod[*dialect.SelectQuery]) SessionsQuery {
	return Sessions.Query(append(mods,
		sm.Where(Sessions.Columns.ClientKeyID.EQ(sqlite.Arg(o.ClientKeyID))), sm.Where(Sessions.Columns.SessionID.EQ(sqlite.Arg(o.SessionID))),
	)...)
}

func (os SessionKeySlice) Session(mods ...bob.Mod[*dialect.SelectQuery]) SessionsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ClientKeyID, o.SessionID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Sessions.Query(append(mods,
		sm.Where(sqlite.Group(Sessions.Columns.ClientKeyID, Sessions.Columns.SessionID).OP("IN", PKArgExpr)),
	)...)
}

func attachSessionKeySession0(ctx context.Context, exec bob.Executor, count int, sessionKey0 *SessionKey, session1 *Session) (*SessionKey, error) {
	setter := &SessionKeySetter{
		ClientKeyID: func() *string { return &session1.ClientKeyID }(),
		SessionID:   func() *string { return &session1.SessionID }(),
	}

	err := sessionKey0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachSessionKeySession0: %w", err)
	}

	return sessionKey0, nil
}

func (sessionKey0 *SessionKey) InsertSession(ctx context.Context, exec bob.Executor, related *SessionSetter) error {
	var err error

	session1, err := Sessions.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachSessionKeySession0(ctx, exec, 1, sessionKey0, session1)
	if err != nil {
		return err
	}

	sessionKey0.R.Session = session1
	sessionKey0.R.Loaded.Session = true

	return nil
}

func (sessionKey0 *SessionKey) AttachSession(ctx context.Context, exec bob.Executor, session1 *Session) error {
	var err error

	_, err = attachSessionKeySession0(ctx, exec, 1, sessionKey0, session1)
	if err != nil {
		return err
	}

	sessionKey0.R.Session = session1
	sessionKey0.R.Loaded.Session = true

	return nil
}
