// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/scan"
)

// Setting is an object representing the database table.
type Setting struct {
	Key       string `db:"key,pk" `
	Value     string `db:"value" `
	UpdatedAt string `db:"updated_at" `
}

// SettingSlice is an alias for a slice of pointers to Setting.
// This should almost always be used instead of []*Setting.
type SettingSlice []*Setting

// Settings contains methods to work with the settings table
var Settings = sqlite.NewTablex[*Setting, SettingSlice, *SettingSetter]("", "settings", buildSettingColumns("settings"), settingScanMapper)

// SettingsQuery is a query on the settings table
type SettingsQuery = *sqlite.ViewQuery[*Setting, SettingSlice]

func buildSettingColumns(tableName string) settingColumns {
	columnsExpr := expr.NewColumnsExpr(
		"key", "value", "updated_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return settingColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		Key:         buildSettingColumn(tableName, "key"),
		Value:       buildSettingColumn(tableName, "value"),
		UpdatedAt:   buildSettingColumn(tableName, "updated_at"),
	}
}

type settingColumns struct {
	expr.ColumnsExpr
	tableAlias string
	Key        settingColumn
	Value      settingColumn
	UpdatedAt  settingColumn
}

// Alias returns the current table alias for the columns set.
func (c settingColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (settingColumns) AliasedAs(tableName string) settingColumns {
	return buildSettingColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c settingColumns) Unqualified() settingColumns {
	return buildSettingColumns("")
}

func buildSettingColumn(alias, name string) settingColumn {
	return settingColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type settingColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c settingColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c settingColumn) ShouldOmitParens() bool {
	return true
}

// SettingSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type SettingSetter struct {
	Key       *string `db:"key,pk" `
	Value     *string `db:"value" `
	UpdatedAt *string `db:"updated_at" `
}

func (s SettingSetter) SetColumns() []string {
	vals := make([]string, 0, 3)
	if s.Key != nil {
		vals = append(vals, "key")
	}
	if s.Value != nil {
		vals = append(vals, "value")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s SettingSetter) Overwrite(t *Setting) {
	if s.Key != nil {
		t.Key = func() string {
			if s.Key == nil {
				return *new(string)
			}
			return *s.Key
		}()
	}
	if s.Value != nil {
		t.Value = func() string {
			if s.Value == nil {
				return *new(string)
			}
			return *s.Value
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() string {
			if s.UpdatedAt == nil {
				return *new(string)
			}
			return *s.UpdatedAt
		}()
	}
}

func (s *SettingSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Settings.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"key"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "key":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Key == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.Key == nil {
						return *new(string)
					}
					return *s.Key
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "value":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Value == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.Value == nil {
						return *new(string)
					}
					return *s.Value
				}()).WriteSQL(ctx, w, d, start)
			}))
		case "updated_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.UpdatedAt == nil {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(func() string {
					if s.UpdatedAt == nil {
						return *new(string)
					}
					return *s.UpdatedAt
				}()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s SettingSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s SettingSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 3)

	if s.Key != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "key")...),
			sqlite.Arg(s.Key),
		}})
	}

	if s.Value != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "value")...),
			sqlite.Arg(s.Value),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func settingScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Setting, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *Setting) any
	}
	targets := make([]target, 0, 3)
	for i, col := range cols {
		switch col {
		case "key":
			targets = append(targets, target{i, func(o *Setting) any { return &o.Key }})
		case "value":
			targets = append(targets, target{i, func(o *Setting) any { return &o.Value }})
		case "updated_at":
			targets = append(targets, target{i, func(o *Setting) any { return &o.UpdatedAt }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(Setting)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*Setting, error) {
			return v.(*Setting), nil
		}
}

// FindSetting retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindSetting(ctx context.Context, exec bob.Executor, KeyPK string, cols ...string) (*Setting, error) {
	if len(cols) == 0 {
		return Settings.Query(
			sm.Where(Settings.Columns.Key.EQ(sqlite.Arg(KeyPK))),
		).One(ctx, exec)
	}

	return Settings.Query(
		sm.Where(Settings.Columns.Key.EQ(sqlite.Arg(KeyPK))),
		sm.Columns(Settings.Columns.Only(cols...)),
	).One(ctx, exec)
}

// SettingExists checks the presence of a single record by primary key
func SettingExists(ctx context.Context, exec bob.Executor, KeyPK string) (bool, error) {
	return Settings.Query(
		sm.Where(Settings.Columns.Key.EQ(sqlite.Arg(KeyPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Setting is retrieved from the database
func (o *Setting) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Settings.AfterSelectHooks.RunHooks(ctx, exec, SettingSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Settings.AfterInsertHooks.RunHooks(ctx, exec, SettingSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Settings.AfterUpdateHooks.RunHooks(ctx, exec, SettingSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Settings.AfterDeleteHooks.RunHooks(ctx, exec, SettingSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the Setting
func (o *Setting) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.Key)
}

func (o *Setting) pkEQ() dialect.Expression {
	return sqlite.Quote("settings", "key").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Setting
func (o *Setting) Update(ctx context.Context, exec bob.Executor, s *SettingSetter) error {
	v, err := Settings.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Setting record with an executor
func (o *Setting) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Settings.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Setting using the executor
func (o *Setting) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Settings.Query(
		sm.Where(Settings.Columns.Key.EQ(sqlite.Arg(o.Key))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after SettingSlice is retrieved from the database
func (o SettingSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Settings.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Settings.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Settings.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Settings.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o SettingSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("settings", "key").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o SettingSlice) copyMatchingRows(from ...*Setting) {
	fromByPK := make(map[string]*Setting, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.Key]; !ok {
			fromByPK[new.Key] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.Key]
		if !ok {
			continue
		}

		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o SettingSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Settings.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Setting:
				o.copyMatchingRows(retrieved)
			case []*Setting:
				o.copyMatchingRows(retrieved...)
			case SettingSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Setting or a slice of Setting
				// then run the AfterUpdateHooks on the slice
				_, err = Settings.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o SettingSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Settings.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Setting:
				o.copyMatchingRows(retrieved)
			case []*Setting:
				o.copyMatchingRows(retrieved...)
			case SettingSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Setting or a slice of Setting
				// then run the AfterDeleteHooks on the slice
				_, err = Settings.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o SettingSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals SettingSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Settings.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o SettingSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Settings.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o SettingSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Settings.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}
