// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var CatalogRefreshes = Table[
	catalogRefreshColumns,
	catalogRefreshIndexes,
	catalogRefreshForeignKeys,
	catalogRefreshUniques,
	catalogRefreshChecks,
]{
	Schema: "",
	Name:   "catalog_refreshes",
	Columns: catalogRefreshColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Provider: column{
			Name:      "provider",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Status: column{
			Name:      "status",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StartedAt: column{
			Name:      "started_at",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CompletedAt: column{
			Name:      "completed_at",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Error: column{
			Name:      "error",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: catalogRefreshIndexes{
		SqliteAutoindexCatalogRefreshes1: index{
			Type: "pk",
			Name: "sqlite_autoindex_catalog_refreshes_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_catalog_refreshes",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type catalogRefreshColumns struct {
	ID          column
	Provider    column
	Status      column
	StartedAt   column
	CompletedAt column
	Error       column
}

func (c catalogRefreshColumns) AsSlice() []column {
	return []column{
		c.ID, c.Provider, c.Status, c.StartedAt, c.CompletedAt, c.Error,
	}
}

type catalogRefreshIndexes struct {
	SqliteAutoindexCatalogRefreshes1 index
}

func (i catalogRefreshIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexCatalogRefreshes1,
	}
}

type catalogRefreshForeignKeys struct{}

func (f catalogRefreshForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type catalogRefreshUniques struct{}

func (u catalogRefreshUniques) AsSlice() []constraint {
	return []constraint{}
}

type catalogRefreshChecks struct{}

func (c catalogRefreshChecks) AsSlice() []check {
	return []check{}
}
