// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Models = Table[
	modelColumns,
	modelIndexes,
	modelForeignKeys,
	modelUniques,
	modelChecks,
]{
	Schema: "",
	Name:   "models",
	Columns: modelColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DisplayName: column{
			Name:      "display_name",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ContextLength: column{
			Name:      "context_length",
			DBType:    "INTEGER",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		MaxOutputTokens: column{
			Name:      "max_output_tokens",
			DBType:    "INTEGER",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		MetadataJSON: column{
			Name:      "metadata_json",
			DBType:    "TEXT",
			Default:   "'{}'",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ObservedAt: column{
			Name:      "observed_at",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StaleAt: column{
			Name:      "stale_at",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: modelIndexes{
		SqliteAutoindexModels1: index{
			Type: "pk",
			Name: "sqlite_autoindex_models_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_models",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type modelColumns struct {
	ID              column
	DisplayName     column
	ContextLength   column
	MaxOutputTokens column
	MetadataJSON    column
	ObservedAt      column
	StaleAt         column
}

func (c modelColumns) AsSlice() []column {
	return []column{
		c.ID, c.DisplayName, c.ContextLength, c.MaxOutputTokens, c.MetadataJSON, c.ObservedAt, c.StaleAt,
	}
}

type modelIndexes struct {
	SqliteAutoindexModels1 index
}

func (i modelIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexModels1,
	}
}

type modelForeignKeys struct{}

func (f modelForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type modelUniques struct{}

func (u modelUniques) AsSlice() []constraint {
	return []constraint{}
}

type modelChecks struct{}

func (c modelChecks) AsSlice() []check {
	return []check{}
}
