// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var ModelRoutes = Table[
	modelRouteColumns,
	modelRouteIndexes,
	modelRouteForeignKeys,
	modelRouteUniques,
	modelRouteChecks,
]{
	Schema: "",
	Name:   "model_routes",
	Columns: modelRouteColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ModelID: column{
			Name:      "model_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Provider: column{
			Name:      "provider",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpstreamModel: column{
			Name:      "upstream_model",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Protocol: column{
			Name:      "protocol",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		PriceJSON: column{
			Name:      "price_json",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CapabilitiesJSON: column{
			Name:      "capabilities_json",
			DBType:    "TEXT",
			Default:   "'{}'",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Health: column{
			Name:      "health",
			DBType:    "TEXT",
			Default:   "'healthy'",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Trusted: column{
			Name:      "trusted",
			DBType:    "INTEGER",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ObservedAt: column{
			Name:      "observed_at",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StaleAt: column{
			Name:      "stale_at",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: modelRouteIndexes{
		SqliteAutoindexModelRoutes1: index{
			Type: "pk",
			Name: "sqlite_autoindex_model_routes_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_model_routes",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: modelRouteForeignKeys{
		FKModelRoutes0: foreignKey{
			constraint: constraint{
				Name:    "fk_model_routes_0",
				Columns: []string{"model_id"},
				Comment: "",
			},
			ForeignTable:   "models",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type modelRouteColumns struct {
	ID               column
	ModelID          column
	Provider         column
	UpstreamModel    column
	Protocol         column
	PriceJSON        column
	CapabilitiesJSON column
	Health           column
	Trusted          column
	ObservedAt       column
	StaleAt          column
}

func (c modelRouteColumns) AsSlice() []column {
	return []column{
		c.ID, c.ModelID, c.Provider, c.UpstreamModel, c.Protocol, c.PriceJSON, c.CapabilitiesJSON, c.Health, c.Trusted, c.ObservedAt, c.StaleAt,
	}
}

type modelRouteIndexes struct {
	SqliteAutoindexModelRoutes1 index
}

func (i modelRouteIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexModelRoutes1,
	}
}

type modelRouteForeignKeys struct {
	FKModelRoutes0 foreignKey
}

func (f modelRouteForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKModelRoutes0,
	}
}

type modelRouteUniques struct{}

func (u modelRouteUniques) AsSlice() []constraint {
	return []constraint{}
}

type modelRouteChecks struct{}

func (c modelRouteChecks) AsSlice() []check {
	return []check{}
}
