// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var ProxyAttempts = Table[
	proxyAttemptColumns,
	proxyAttemptIndexes,
	proxyAttemptForeignKeys,
	proxyAttemptUniques,
	proxyAttemptChecks,
]{
	Schema: "",
	Name:   "proxy_attempts",
	Columns: proxyAttemptColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		RequestID: column{
			Name:      "request_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		AttemptNumber: column{
			Name:      "attempt_number",
			DBType:    "INTEGER",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		RouteID: column{
			Name:      "route_id",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Provider: column{
			Name:      "provider",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UpstreamModel: column{
			Name:      "upstream_model",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		State: column{
			Name:      "state",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StartedAt: column{
			Name:      "started_at",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CompletedAt: column{
			Name:      "completed_at",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		HTTPStatus: column{
			Name:      "http_status",
			DBType:    "INTEGER",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ErrorClass: column{
			Name:      "error_class",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ErrorMessage: column{
			Name:      "error_message",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ErrorRaw: column{
			Name:      "error_raw",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		DurationMS: column{
			Name:      "duration_ms",
			DBType:    "INTEGER",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		DeliveryState: column{
			Name:      "delivery_state",
			DBType:    "TEXT",
			Default:   "'nothing_sent'",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StatsDisposition: column{
			Name:      "stats_disposition",
			DBType:    "TEXT",
			Default:   "'included'",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: proxyAttemptIndexes{
		SqliteAutoindexProxyAttempts1: index{
			Type: "pk",
			Name: "sqlite_autoindex_proxy_attempts_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_proxy_attempts",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: proxyAttemptForeignKeys{
		FKProxyAttempts0: foreignKey{
			constraint: constraint{
				Name:    "fk_proxy_attempts_0",
				Columns: []string{"request_id"},
				Comment: "",
			},
			ForeignTable:   "proxy_requests",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type proxyAttemptColumns struct {
	ID               column
	RequestID        column
	AttemptNumber    column
	RouteID          column
	Provider         column
	UpstreamModel    column
	State            column
	StartedAt        column
	CompletedAt      column
	HTTPStatus       column
	ErrorClass       column
	ErrorMessage     column
	ErrorRaw         column
	DurationMS       column
	DeliveryState    column
	StatsDisposition column
}

func (c proxyAttemptColumns) AsSlice() []column {
	return []column{
		c.ID, c.RequestID, c.AttemptNumber, c.RouteID, c.Provider, c.UpstreamModel, c.State, c.StartedAt, c.CompletedAt, c.HTTPStatus, c.ErrorClass, c.ErrorMessage, c.ErrorRaw, c.DurationMS, c.DeliveryState, c.StatsDisposition,
	}
}

type proxyAttemptIndexes struct {
	SqliteAutoindexProxyAttempts1 index
}

func (i proxyAttemptIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexProxyAttempts1,
	}
}

type proxyAttemptForeignKeys struct {
	FKProxyAttempts0 foreignKey
}

func (f proxyAttemptForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKProxyAttempts0,
	}
}

type proxyAttemptUniques struct{}

func (u proxyAttemptUniques) AsSlice() []constraint {
	return []constraint{}
}

type proxyAttemptChecks struct{}

func (c proxyAttemptChecks) AsSlice() []check {
	return []check{}
}
