// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var ProxyRequests = Table[
	proxyRequestColumns,
	proxyRequestIndexes,
	proxyRequestForeignKeys,
	proxyRequestUniques,
	proxyRequestChecks,
]{
	Schema: "",
	Name:   "proxy_requests",
	Columns: proxyRequestColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ClientKeyID: column{
			Name:      "client_key_id",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Protocol: column{
			Name:      "protocol",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		LogicalModel: column{
			Name:      "logical_model",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		State: column{
			Name:      "state",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ReceivedAt: column{
			Name:      "received_at",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CompletedAt: column{
			Name:      "completed_at",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		SelectedProvider: column{
			Name:      "selected_provider",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		SelectedUpstreamModel: column{
			Name:      "selected_upstream_model",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		AttemptCount: column{
			Name:      "attempt_count",
			DBType:    "INTEGER",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DurationMS: column{
			Name:      "duration_ms",
			DBType:    "INTEGER",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ErrorCode: column{
			Name:      "error_code",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ErrorMessage: column{
			Name:      "error_message",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		StatsDisposition: column{
			Name:      "stats_disposition",
			DBType:    "TEXT",
			Default:   "'included'",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: proxyRequestIndexes{
		SqliteAutoindexProxyRequests1: index{
			Type: "pk",
			Name: "sqlite_autoindex_proxy_requests_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_proxy_requests",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type proxyRequestColumns struct {
	ID                    column
	ClientKeyID           column
	Protocol              column
	LogicalModel          column
	State                 column
	ReceivedAt            column
	CompletedAt           column
	SelectedProvider      column
	SelectedUpstreamModel column
	AttemptCount          column
	DurationMS            column
	ErrorCode             column
	ErrorMessage          column
	StatsDisposition      column
}

func (c proxyRequestColumns) AsSlice() []column {
	return []column{
		c.ID, c.ClientKeyID, c.Protocol, c.LogicalModel, c.State, c.ReceivedAt, c.CompletedAt, c.SelectedProvider, c.SelectedUpstreamModel, c.AttemptCount, c.DurationMS, c.ErrorCode, c.ErrorMessage, c.StatsDisposition,
	}
}

type proxyRequestIndexes struct {
	SqliteAutoindexProxyRequests1 index
}

func (i proxyRequestIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexProxyRequests1,
	}
}

type proxyRequestForeignKeys struct{}

func (f proxyRequestForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type proxyRequestUniques struct{}

func (u proxyRequestUniques) AsSlice() []constraint {
	return []constraint{}
}

type proxyRequestChecks struct{}

func (c proxyRequestChecks) AsSlice() []check {
	return []check{}
}
