// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var RequestUsages = Table[
	requestUsageColumns,
	requestUsageIndexes,
	requestUsageForeignKeys,
	requestUsageUniques,
	requestUsageChecks,
]{
	Schema: "",
	Name:   "request_usage",
	Columns: requestUsageColumns{
		RequestID: column{
			Name:      "request_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		InputTokens: column{
			Name:      "input_tokens",
			DBType:    "INTEGER",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		OutputTokens: column{
			Name:      "output_tokens",
			DBType:    "INTEGER",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TotalTokens: column{
			Name:      "total_tokens",
			DBType:    "INTEGER",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CachedReadTokens: column{
			Name:      "cached_read_tokens",
			DBType:    "INTEGER",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CacheWriteTokens: column{
			Name:      "cache_write_tokens",
			DBType:    "INTEGER",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ReasoningTokens: column{
			Name:      "reasoning_tokens",
			DBType:    "INTEGER",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		EstimatedCostPicoUsd: column{
			Name:      "estimated_cost_pico_usd",
			DBType:    "INTEGER",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		OfficialCostPicoUsd: column{
			Name:      "official_cost_pico_usd",
			DBType:    "INTEGER",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DiscountPicoUsd: column{
			Name:      "discount_pico_usd",
			DBType:    "INTEGER",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		DiscountPercentBPS: column{
			Name:      "discount_percent_bps",
			DBType:    "INTEGER",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ActualCostPicoUsd: column{
			Name:      "actual_cost_pico_usd",
			DBType:    "INTEGER",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		RawUsageJSON: column{
			Name:      "raw_usage_json",
			DBType:    "TEXT",
			Default:   "'{}'",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: requestUsageIndexes{
		SqliteAutoindexRequestUsage1: index{
			Type: "pk",
			Name: "sqlite_autoindex_request_usage_1",
			Columns: []indexColumn{
				{
					Name:         "request_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_request_usage",
		Columns: []string{"request_id"},
		Comment: "",
	},
	ForeignKeys: requestUsageForeignKeys{
		FKRequestUsage0: foreignKey{
			constraint: constraint{
				Name:    "fk_request_usage_0",
				Columns: []string{"request_id"},
				Comment: "",
			},
			ForeignTable:   "proxy_requests",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type requestUsageColumns struct {
	RequestID            column
	InputTokens          column
	OutputTokens         column
	TotalTokens          column
	CachedReadTokens     column
	CacheWriteTokens     column
	ReasoningTokens      column
	EstimatedCostPicoUsd column
	OfficialCostPicoUsd  column
	DiscountPicoUsd      column
	DiscountPercentBPS   column
	ActualCostPicoUsd    column
	RawUsageJSON         column
}

func (c requestUsageColumns) AsSlice() []column {
	return []column{
		c.RequestID, c.InputTokens, c.OutputTokens, c.TotalTokens, c.CachedReadTokens, c.CacheWriteTokens, c.ReasoningTokens, c.EstimatedCostPicoUsd, c.OfficialCostPicoUsd, c.DiscountPicoUsd, c.DiscountPercentBPS, c.ActualCostPicoUsd, c.RawUsageJSON,
	}
}

type requestUsageIndexes struct {
	SqliteAutoindexRequestUsage1 index
}

func (i requestUsageIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexRequestUsage1,
	}
}

type requestUsageForeignKeys struct {
	FKRequestUsage0 foreignKey
}

func (f requestUsageForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKRequestUsage0,
	}
}

type requestUsageUniques struct{}

func (u requestUsageUniques) AsSlice() []constraint {
	return []constraint{}
}

type requestUsageChecks struct{}

func (c requestUsageChecks) AsSlice() []check {
	return []check{}
}
