// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var RoutingGroupStages = Table[
	routingGroupStageColumns,
	routingGroupStageIndexes,
	routingGroupStageForeignKeys,
	routingGroupStageUniques,
	routingGroupStageChecks,
]{
	Schema: "",
	Name:   "routing_group_stages",
	Columns: routingGroupStageColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		GroupID: column{
			Name:      "group_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Position: column{
			Name:      "position",
			DBType:    "INTEGER",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "TEXT",
			Default:   "''",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		SelectionStrategy: column{
			Name:      "selection_strategy",
			DBType:    "TEXT",
			Default:   "'lowest_expected_cost'",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		MaximumInputPicoUsdPerToken: column{
			Name:      "maximum_input_pico_usd_per_token",
			DBType:    "INTEGER",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		MaximumOutputPicoUsdPerToken: column{
			Name:      "maximum_output_pico_usd_per_token",
			DBType:    "INTEGER",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		MaximumExpectedCostPicoUsd: column{
			Name:      "maximum_expected_cost_pico_usd",
			DBType:    "INTEGER",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		SameRouteRetries: column{
			Name:      "same_route_retries",
			DBType:    "INTEGER",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		TryRetries: column{
			Name:      "try_retries",
			DBType:    "INTEGER",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: routingGroupStageIndexes{
		SqliteAutoindexRoutingGroupStages2: index{
			Type: "u",
			Name: "sqlite_autoindex_routing_group_stages_2",
			Columns: []indexColumn{
				{
					Name:         "group_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "position",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexRoutingGroupStages1: index{
			Type: "pk",
			Name: "sqlite_autoindex_routing_group_stages_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_routing_group_stages",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: routingGroupStageForeignKeys{
		FKRoutingGroupStages0: foreignKey{
			constraint: constraint{
				Name:    "fk_routing_group_stages_0",
				Columns: []string{"group_id"},
				Comment: "",
			},
			ForeignTable:   "routing_groups",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: routingGroupStageUniques{
		SqliteAutoindexRoutingGroupStages2: constraint{
			Name:    "sqlite_autoindex_routing_group_stages_2",
			Columns: []string{"group_id", "position"},
			Comment: "",
		},
	},

	Comment: "",
}

type routingGroupStageColumns struct {
	ID                           column
	GroupID                      column
	Position                     column
	Name                         column
	SelectionStrategy            column
	MaximumInputPicoUsdPerToken  column
	MaximumOutputPicoUsdPerToken column
	MaximumExpectedCostPicoUsd   column
	SameRouteRetries             column
	TryRetries                   column
}

func (c routingGroupStageColumns) AsSlice() []column {
	return []column{
		c.ID, c.GroupID, c.Position, c.Name, c.SelectionStrategy, c.MaximumInputPicoUsdPerToken, c.MaximumOutputPicoUsdPerToken, c.MaximumExpectedCostPicoUsd, c.SameRouteRetries, c.TryRetries,
	}
}

type routingGroupStageIndexes struct {
	SqliteAutoindexRoutingGroupStages2 index
	SqliteAutoindexRoutingGroupStages1 index
}

func (i routingGroupStageIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexRoutingGroupStages2, i.SqliteAutoindexRoutingGroupStages1,
	}
}

type routingGroupStageForeignKeys struct {
	FKRoutingGroupStages0 foreignKey
}

func (f routingGroupStageForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKRoutingGroupStages0,
	}
}

type routingGroupStageUniques struct {
	SqliteAutoindexRoutingGroupStages2 constraint
}

func (u routingGroupStageUniques) AsSlice() []constraint {
	return []constraint{
		u.SqliteAutoindexRoutingGroupStages2,
	}
}

type routingGroupStageChecks struct{}

func (c routingGroupStageChecks) AsSlice() []check {
	return []check{}
}
