// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var RoutingGroups = Table[
	routingGroupColumns,
	routingGroupIndexes,
	routingGroupForeignKeys,
	routingGroupUniques,
	routingGroupChecks,
]{
	Schema: "",
	Name:   "routing_groups",
	Columns: routingGroupColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Slug: column{
			Name:      "slug",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Description: column{
			Name:      "description",
			DBType:    "TEXT",
			Default:   "''",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Enabled: column{
			Name:      "enabled",
			DBType:    "INTEGER",
			Default:   "1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Revision: column{
			Name:      "revision",
			DBType:    "INTEGER",
			Default:   "1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: routingGroupIndexes{
		SqliteAutoindexRoutingGroups2: index{
			Type: "u",
			Name: "sqlite_autoindex_routing_groups_2",
			Columns: []indexColumn{
				{
					Name:         "slug",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexRoutingGroups1: index{
			Type: "pk",
			Name: "sqlite_autoindex_routing_groups_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_routing_groups",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: routingGroupUniques{
		SqliteAutoindexRoutingGroups2: constraint{
			Name:    "sqlite_autoindex_routing_groups_2",
			Columns: []string{"slug"},
			Comment: "",
		},
	},

	Comment: "",
}

type routingGroupColumns struct {
	ID          column
	Name        column
	Slug        column
	Description column
	Enabled     column
	Revision    column
	CreatedAt   column
	UpdatedAt   column
}

func (c routingGroupColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.Slug, c.Description, c.Enabled, c.Revision, c.CreatedAt, c.UpdatedAt,
	}
}

type routingGroupIndexes struct {
	SqliteAutoindexRoutingGroups2 index
	SqliteAutoindexRoutingGroups1 index
}

func (i routingGroupIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexRoutingGroups2, i.SqliteAutoindexRoutingGroups1,
	}
}

type routingGroupForeignKeys struct{}

func (f routingGroupForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type routingGroupUniques struct {
	SqliteAutoindexRoutingGroups2 constraint
}

func (u routingGroupUniques) AsSlice() []constraint {
	return []constraint{
		u.SqliteAutoindexRoutingGroups2,
	}
}

type routingGroupChecks struct{}

func (c routingGroupChecks) AsSlice() []check {
	return []check{}
}
