// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var RoutingGroupSources = Table[
	routingGroupSourceColumns,
	routingGroupSourceIndexes,
	routingGroupSourceForeignKeys,
	routingGroupSourceUniques,
	routingGroupSourceChecks,
]{
	Schema: "",
	Name:   "routing_group_sources",
	Columns: routingGroupSourceColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StageID: column{
			Name:      "stage_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Position: column{
			Name:      "position",
			DBType:    "INTEGER",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		SourceKind: column{
			Name:      "source_kind",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ModelID: column{
			Name:      "model_id",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		NestedGroupID: column{
			Name:      "nested_group_id",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: routingGroupSourceIndexes{
		SqliteAutoindexRoutingGroupSources2: index{
			Type: "u",
			Name: "sqlite_autoindex_routing_group_sources_2",
			Columns: []indexColumn{
				{
					Name:         "stage_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "position",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexRoutingGroupSources1: index{
			Type: "pk",
			Name: "sqlite_autoindex_routing_group_sources_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_routing_group_sources",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: routingGroupSourceForeignKeys{
		FKRoutingGroupSources0: foreignKey{
			constraint: constraint{
				Name:    "fk_routing_group_sources_0",
				Columns: []string{"nested_group_id"},
				Comment: "",
			},
			ForeignTable:   "routing_groups",
			ForeignColumns: []string{"id"},
		},
		FKRoutingGroupSources1: foreignKey{
			constraint: constraint{
				Name:    "fk_routing_group_sources_1",
				Columns: []string{"stage_id"},
				Comment: "",
			},
			ForeignTable:   "routing_group_stages",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: routingGroupSourceUniques{
		SqliteAutoindexRoutingGroupSources2: constraint{
			Name:    "sqlite_autoindex_routing_group_sources_2",
			Columns: []string{"stage_id", "position"},
			Comment: "",
		},
	},

	Comment: "",
}

type routingGroupSourceColumns struct {
	ID            column
	StageID       column
	Position      column
	SourceKind    column
	ModelID       column
	NestedGroupID column
}

func (c routingGroupSourceColumns) AsSlice() []column {
	return []column{
		c.ID, c.StageID, c.Position, c.SourceKind, c.ModelID, c.NestedGroupID,
	}
}

type routingGroupSourceIndexes struct {
	SqliteAutoindexRoutingGroupSources2 index
	SqliteAutoindexRoutingGroupSources1 index
}

func (i routingGroupSourceIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexRoutingGroupSources2, i.SqliteAutoindexRoutingGroupSources1,
	}
}

type routingGroupSourceForeignKeys struct {
	FKRoutingGroupSources0 foreignKey
	FKRoutingGroupSources1 foreignKey
}

func (f routingGroupSourceForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKRoutingGroupSources0, f.FKRoutingGroupSources1,
	}
}

type routingGroupSourceUniques struct {
	SqliteAutoindexRoutingGroupSources2 constraint
}

func (u routingGroupSourceUniques) AsSlice() []constraint {
	return []constraint{
		u.SqliteAutoindexRoutingGroupSources2,
	}
}

type routingGroupSourceChecks struct{}

func (c routingGroupSourceChecks) AsSlice() []check {
	return []check{}
}
