// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var RoutingGroupStageBillingClasses = Table[
	routingGroupStageBillingClassColumns,
	routingGroupStageBillingClassIndexes,
	routingGroupStageBillingClassForeignKeys,
	routingGroupStageBillingClassUniques,
	routingGroupStageBillingClassChecks,
]{
	Schema: "",
	Name:   "routing_group_stage_billing_classes",
	Columns: routingGroupStageBillingClassColumns{
		StageID: column{
			Name:      "stage_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		BillingClass: column{
			Name:      "billing_class",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: routingGroupStageBillingClassIndexes{
		SqliteAutoindexRoutingGroupStageBillingClasses1: index{
			Type: "pk",
			Name: "sqlite_autoindex_routing_group_stage_billing_classes_1",
			Columns: []indexColumn{
				{
					Name:         "stage_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "billing_class",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_routing_group_stage_billing_classes",
		Columns: []string{"stage_id", "billing_class"},
		Comment: "",
	},
	ForeignKeys: routingGroupStageBillingClassForeignKeys{
		FKRoutingGroupStageBillingClasses0: foreignKey{
			constraint: constraint{
				Name:    "fk_routing_group_stage_billing_classes_0",
				Columns: []string{"stage_id"},
				Comment: "",
			},
			ForeignTable:   "routing_group_stages",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type routingGroupStageBillingClassColumns struct {
	StageID      column
	BillingClass column
}

func (c routingGroupStageBillingClassColumns) AsSlice() []column {
	return []column{
		c.StageID, c.BillingClass,
	}
}

type routingGroupStageBillingClassIndexes struct {
	SqliteAutoindexRoutingGroupStageBillingClasses1 index
}

func (i routingGroupStageBillingClassIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexRoutingGroupStageBillingClasses1,
	}
}

type routingGroupStageBillingClassForeignKeys struct {
	FKRoutingGroupStageBillingClasses0 foreignKey
}

func (f routingGroupStageBillingClassForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKRoutingGroupStageBillingClasses0,
	}
}

type routingGroupStageBillingClassUniques struct{}

func (u routingGroupStageBillingClassUniques) AsSlice() []constraint {
	return []constraint{}
}

type routingGroupStageBillingClassChecks struct{}

func (c routingGroupStageBillingClassChecks) AsSlice() []check {
	return []check{}
}
