// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var RoutingGroupStageProviders = Table[
	routingGroupStageProviderColumns,
	routingGroupStageProviderIndexes,
	routingGroupStageProviderForeignKeys,
	routingGroupStageProviderUniques,
	routingGroupStageProviderChecks,
]{
	Schema: "",
	Name:   "routing_group_stage_providers",
	Columns: routingGroupStageProviderColumns{
		StageID: column{
			Name:      "stage_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ProviderName: column{
			Name:      "provider_name",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: routingGroupStageProviderIndexes{
		SqliteAutoindexRoutingGroupStageProviders1: index{
			Type: "pk",
			Name: "sqlite_autoindex_routing_group_stage_providers_1",
			Columns: []indexColumn{
				{
					Name:         "stage_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "provider_name",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_routing_group_stage_providers",
		Columns: []string{"stage_id", "provider_name"},
		Comment: "",
	},
	ForeignKeys: routingGroupStageProviderForeignKeys{
		FKRoutingGroupStageProviders0: foreignKey{
			constraint: constraint{
				Name:    "fk_routing_group_stage_providers_0",
				Columns: []string{"stage_id"},
				Comment: "",
			},
			ForeignTable:   "routing_group_stages",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type routingGroupStageProviderColumns struct {
	StageID      column
	ProviderName column
}

func (c routingGroupStageProviderColumns) AsSlice() []column {
	return []column{
		c.StageID, c.ProviderName,
	}
}

type routingGroupStageProviderIndexes struct {
	SqliteAutoindexRoutingGroupStageProviders1 index
}

func (i routingGroupStageProviderIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexRoutingGroupStageProviders1,
	}
}

type routingGroupStageProviderForeignKeys struct {
	FKRoutingGroupStageProviders0 foreignKey
}

func (f routingGroupStageProviderForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKRoutingGroupStageProviders0,
	}
}

type routingGroupStageProviderUniques struct{}

func (u routingGroupStageProviderUniques) AsSlice() []constraint {
	return []constraint{}
}

type routingGroupStageProviderChecks struct{}

func (c routingGroupStageProviderChecks) AsSlice() []check {
	return []check{}
}
