// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Sessions = Table[
	sessionColumns,
	sessionIndexes,
	sessionForeignKeys,
	sessionUniques,
	sessionChecks,
]{
	Schema: "",
	Name:   "sessions",
	Columns: sessionColumns{
		ClientKeyID: column{
			Name:      "client_key_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		SessionID: column{
			Name:      "session_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		LastSeenAt: column{
			Name:      "last_seen_at",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: sessionIndexes{
		SessionsLastSeen: index{
			Type: "c",
			Name: "sessions_last_seen",
			Columns: []indexColumn{
				{
					Name:         "last_seen_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexSessions1: index{
			Type: "pk",
			Name: "sqlite_autoindex_sessions_1",
			Columns: []indexColumn{
				{
					Name:         "client_key_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "session_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_sessions",
		Columns: []string{"client_key_id", "session_id"},
		Comment: "",
	},

	Comment: "",
}

type sessionColumns struct {
	ClientKeyID column
	SessionID   column
	CreatedAt   column
	LastSeenAt  column
}

func (c sessionColumns) AsSlice() []column {
	return []column{
		c.ClientKeyID, c.SessionID, c.CreatedAt, c.LastSeenAt,
	}
}

type sessionIndexes struct {
	SessionsLastSeen         index
	SqliteAutoindexSessions1 index
}

func (i sessionIndexes) AsSlice() []index {
	return []index{
		i.SessionsLastSeen, i.SqliteAutoindexSessions1,
	}
}

type sessionForeignKeys struct{}

func (f sessionForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type sessionUniques struct{}

func (u sessionUniques) AsSlice() []constraint {
	return []constraint{}
}

type sessionChecks struct{}

func (c sessionChecks) AsSlice() []check {
	return []check{}
}
