// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var SessionKeys = Table[
	sessionKeyColumns,
	sessionKeyIndexes,
	sessionKeyForeignKeys,
	sessionKeyUniques,
	sessionKeyChecks,
]{
	Schema: "",
	Name:   "session_keys",
	Columns: sessionKeyColumns{
		ClientKeyID: column{
			Name:      "client_key_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		SessionID: column{
			Name:      "session_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		KeyHash: column{
			Name:      "key_hash",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IsAnchor: column{
			Name:      "is_anchor",
			DBType:    "INTEGER",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		LastSeenAt: column{
			Name:      "last_seen_at",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: sessionKeyIndexes{
		SessionKeysRecent: index{
			Type: "c",
			Name: "session_keys_recent",
			Columns: []indexColumn{
				{
					Name:         "client_key_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "session_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "last_seen_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		SessionKeysLookup: index{
			Type: "c",
			Name: "session_keys_lookup",
			Columns: []indexColumn{
				{
					Name:         "client_key_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "key_hash",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexSessionKeys1: index{
			Type: "pk",
			Name: "sqlite_autoindex_session_keys_1",
			Columns: []indexColumn{
				{
					Name:         "client_key_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "session_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "key_hash",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_session_keys",
		Columns: []string{"client_key_id", "session_id", "key_hash"},
		Comment: "",
	},
	ForeignKeys: sessionKeyForeignKeys{
		FKSessionKeys0: foreignKey{
			constraint: constraint{
				Name:    "fk_session_keys_0",
				Columns: []string{"client_key_id", "session_id"},
				Comment: "",
			},
			ForeignTable:   "sessions",
			ForeignColumns: []string{"client_key_id", "session_id"},
		},
	},

	Comment: "",
}

type sessionKeyColumns struct {
	ClientKeyID column
	SessionID   column
	KeyHash     column
	IsAnchor    column
	LastSeenAt  column
}

func (c sessionKeyColumns) AsSlice() []column {
	return []column{
		c.ClientKeyID, c.SessionID, c.KeyHash, c.IsAnchor, c.LastSeenAt,
	}
}

type sessionKeyIndexes struct {
	SessionKeysRecent           index
	SessionKeysLookup           index
	SqliteAutoindexSessionKeys1 index
}

func (i sessionKeyIndexes) AsSlice() []index {
	return []index{
		i.SessionKeysRecent, i.SessionKeysLookup, i.SqliteAutoindexSessionKeys1,
	}
}

type sessionKeyForeignKeys struct {
	FKSessionKeys0 foreignKey
}

func (f sessionKeyForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKSessionKeys0,
	}
}

type sessionKeyUniques struct{}

func (u sessionKeyUniques) AsSlice() []constraint {
	return []constraint{}
}

type sessionKeyChecks struct{}

func (c sessionKeyChecks) AsSlice() []check {
	return []check{}
}
