// Code generated by BobGen sql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Settings = Table[
	settingColumns,
	settingIndexes,
	settingForeignKeys,
	settingUniques,
	settingChecks,
]{
	Schema: "",
	Name:   "settings",
	Columns: settingColumns{
		Key: column{
			Name:      "key",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Value: column{
			Name:      "value",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: settingIndexes{
		SqliteAutoindexSettings1: index{
			Type: "pk",
			Name: "sqlite_autoindex_settings_1",
			Columns: []indexColumn{
				{
					Name:         "key",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_settings",
		Columns: []string{"key"},
		Comment: "",
	},

	Comment: "",
}

type settingColumns struct {
	Key       column
	Value     column
	UpdatedAt column
}

func (c settingColumns) AsSlice() []column {
	return []column{
		c.Key, c.Value, c.UpdatedAt,
	}
}

type settingIndexes struct {
	SqliteAutoindexSettings1 index
}

func (i settingIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexSettings1,
	}
}

type settingForeignKeys struct{}

func (f settingForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type settingUniques struct{}

func (u settingUniques) AsSlice() []constraint {
	return []constraint{}
}

type settingChecks struct{}

func (c settingChecks) AsSlice() []check {
	return []check{}
}
